---
sidebar: sidebar
permalink: alpha-workflows.html
summary: A set of example steps to work through to test out the Project Astra alpha program.
---

= Project Astra Alpha Workflows

If you are getting started with Project Astra, we recommend the following steps as a way of exercising the service.

== Getting Started

These articles will help you get up and running with the Project Astra alpha program.

* link:getting-started.html[Getting Started Guide]
* link:faq.html[FAQ]
* link:invite-users.html[Invite Users]

== Deploy an App

Learn how to deploy MySQL/MariaDB or Postgres from a Helm chart.

* link:deploy-mysql-mariadb-from-helm-chart.html[Deploy MySQL/MariaDB from a Helm chart].
* link:deploy-postgres-from-helm-chart.html[Deploy Postgres from a Helm chart].

== Snapshots

Create and manage point-in-time snapshots of your application.

* link:snapshot-create.html[Create a snapshot].
* link:snapshot-view.html[View your snapshots].
* link:snapshot-add-data.html[Add data to a snapshot].
* link:snapshot-restore.html[Restore from a snapshot].

== Backups

Create and manage backups of your application.

* link:backup-create.html[Create a backup].
* link:backup-view.html[View your backups].
* link:backup-add-data.html[Add data to a backup].
* link:backup-restore.html[Restore from a backup].

== Migrate Clusters

Use the Clone feature to migrate data between clusters.

* link:migrate-between-two-existing.html[Migrate between two existing clusters].
* link:migrate-between-existing-and-new.html[Migrate between an existing and a new cluster].

== Deregister a Cluster

When you are done with the alpha workflow, remove your assets from Project Astra.

1. Deregister the app. Go to **Apps**, select your app, then under **Actions** click **De-register**. This will end your app being managed by Project Astra. It will not remove the app from your cluster.

2. Deregister the cluster. Go to **Compute** select your cluster, under **Actions** click **Deregister**. This will remove your cluster from Project Astra. It will not delete the GKE cluster from your Google Cloud Platform (GCP) account.

3. Optional: Delete the cluster on GCP. Log in to the https://console.cloud.google.com/[Google Cloud Console], click **Kubernetes Engine > Clusters**, select your cluster, then click **Delete**. 

(C) 2020 NetApp, Inc. All rights reserved.

— NETAPP CONFIDENTIAL —

NetApp Confidential Information Subject to the Mutual Nondisclosure Agreement

All information disclosed in this document is furnished in confidence by NetApp to you with the understanding that it is NetApp confidential information pursuant to the Mutual Nondisclosure Agreement between the parties and shall be treated as such by you. The information provided in this document is for exploratory purposes only and is subject to change without notice and without liability or obligation to NetApp. NetApp retains all right, title, and interest in and to all information contained in this document, all derivative works of such information and all intellectual property rights embodied therein.
