---
sidebar: sidebar
permalink: credentials-cvs.html
summary: Learn how to locate your CVS auth credentials, or create a new set of credentials, so that you can use Project Astra.
---

= Set Up NetApp Cloud Volumes Service
:imagesdir: assets/cvs-credentials/

In order to participate in the Project Astra alpha program, you will need to set up NetApp Cloud Volumes Service for Google Cloud.

Before you begin using NetApp CVS, you will need to verify that your role is set up correctly, and complete a few one-time set-up tasks per project. https://cloud.google.com/solutions/partners/netapp-cloud-volumes/before-you-begin-cloud-volumes[See the CVS start-up guide for details and step-by-step instructions.]

You will also need to set up private services access. https://cloud.google.com/solutions/partners/netapp-cloud-volumes/setting-up-private-services-access[Click here for instructions on setting up private services access.]

**External Resources**

* https://cloud.google.com/solutions/partners/netapp-cloud-volumes[NetApp Cloud Volumes Service for Google Cloud documentation]

(C) 2020 NetApp, Inc. All rights reserved.

— NETAPP CONFIDENTIAL —

NetApp Confidential Information Subject to the Mutual Nondisclosure Agreement

All information disclosed in this document is furnished in confidence by NetApp to you with the understanding that it is NetApp confidential information pursuant to the Mutual Nondisclosure Agreement between the parties and shall be treated as such by you. The information provided in this document is for exploratory purposes only and is subject to change without notice and without liability or obligation to NetApp. NetApp retains all right, title, and interest in and to all information contained in this document, all derivative works of such information and all intellectual property rights embodied therein.
