---
sidebar: sidebar
permalink: deploy-mysql-mariadb-from-helm-chart.html
summary: Learn how to deploy MySQL/MariaDB from a Helm chart
---

= Deploy MySQL/MariaDB From a Helm Chart

Learn how to exercise the Project Astra workflow by deploying MariaDB from a Helm chart. After you deploy MariaDB on your cluster, you can register the application with Project Astra.

NOTE: The Project Astra alpha program only supports MySQL 0.3.22 and MariaDB 14.14.

== System Requirements

In order to deploy MySQL/MariaDB from a Helm chart for the Project Astra alpha program, you need the following:

* A fresh GKE cluster which has been added to Project Astra.
* Kubectl and Helm installed.
* Kubeconfig configured using the gcloud tool with a command like `gcloud container clusters get-credentials my-cluster-name`

NOTE: You must deploy your app after the cluster is added to Project Astra, not before.

== Install MariaDB

To exercise the Project Astra alpha workflow, we recommend you use the Helm chart which we have customized for Project Astra. link:assets/mariadb.zip[Click here to download the compressed folder].

NOTE: You must deploy the Helm chart in a namespace other than the default.

The following command creates a namespace `my-mariadb-namespace` deploys MariaDB on that namespace, and creates a database named `test_db`, database user `test_db_user`, and password `CHANGETHISTOYOURPASSWORD`:

----
helm install mariadb ./mariadb --namespace my-mariadb-namespace --create-namespace --set db.database=test_db,db.user=test_db_user,db.password=CHANGETHISTOYOURPASSWORD > /dev/null 2>&1
----

After the Helm chart is deployed, it will be automatically detected by Project Astra, at which point you can register the app with Project Astra. Please note that for the Project Astra alpha program, installed applications can take up to 5 minutes to show up in the Discovered Applications list.

== Custom MySQL/MariaDB Requirements

If you wish to deploy your own MySQL/MariaDB application, please note that Project Astra Alpha requires:

* `global.storageClass` value to be set to the storageClass representing either CVS or Trident (or, that storageClass is set as your cluster's default provisioner).
* The namespace set to something other than default, using the `--namespace` argument.
* A single node deployment. Multi-node and HA deployments will be supported in future releases.

The Project Astra alpha program does not support replicas or failovers. Only single instance versions of the databases are supported. For testing Project Astra in Alpha, leave replication off, and check that the `global.storageClass` value in the Helm values is pointing to the correct storageClass.


(C) 2020 NetApp, Inc. All rights reserved.

— NETAPP CONFIDENTIAL —

NetApp Confidential Information Subject to the Mutual Nondisclosure Agreement

All information disclosed in this document is furnished in confidence by NetApp to you with the understanding that it is NetApp confidential information pursuant to the Mutual Nondisclosure Agreement between the parties and shall be treated as such by you. The information provided in this document is for exploratory purposes only and is subject to change without notice and without liability or obligation to NetApp. NetApp retains all right, title, and interest in and to all information contained in this document, all derivative works of such information and all intellectual property rights embodied therein.
