---
sidebar: sidebar
permalink: deploy-mysql-mariadb-from-helm-chart.html
summary: Learn how to deploy MySQL/MariaDB from a Helm chart
---

= Deploy MySQL/MariaDB From a Helm Chart









This guide describes how to run MariaDB/MySQL using Project Astra.

Combining Project Astra with a stateful app (like a database) is intended to save you time and provide peace of mind. The combination means you will be running with essential guarantees like automated backups, a scalable and robust storage layer, along with all of the benefits of Kubernetes.

For the first iteration, this guide will focus on Helm as the preferred way to deploy MariaDB/MySQL apps. Plain YAML and Operator based deployments may be covered in future guides.

== Setup

In order to follow along with this guide, a few components are required. We’ll need an up-to-date Kubernetes cluster (version 1.17+), kubectl installed, and kubeconfig downloaded and setup. We will also need to connect our Kubernetes cluster with Project Astra.

The link:getting-started.html[Getting Started (Onboarding Guide)] is the best option for creating your GKE cluster, and connecting to Project Astra. The following links are provided in addition, in case instructions are unclear, or you need to troubleshoot your installation.

=== Pre-requisites Covered in the Getting Started Guide

==== GKE

You will need to follow instructions in the link:getting-started.html[Getting Started (Onboarding Guide)] for connecting Project Astra to your clusters.

GKE is supported for the current release (alpha) of Project Astra. In the event that you need help beyond the Getting Started guide, Google Cloud has great https://cloud.google.com/kubernetes-engine/docs/how-to/creating-a-cluster[docs for creating a new GKE cluster].

Additional Kubernetes distributions are planned to be added as Project Astra matures.

==== Kubectl

Downloading kubectl should be covered as a step in the link:getting-started.html[Getting Started (Onboarding Guide)].

Kubectl is a standard tool for interacting with Kubernetes. We’ll use kubectl to manage our initial database application. To get kubectl on your computer, follow this guide to https://kubernetes.io/docs/tasks/tools/install-kubectl/[download and install kubectl].

==== Kubeconfig

Downloading and configuring kubeconfig should be covered as a step in the link:getting-started.html[Getting Started (Onboarding Guide)]

Kubeconfig is a file that contains credentials to allow kubectl to communicate with the Kubernetes cluster (eg GKE). To download your kubeconfig, you could also follow this guide for https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#generate_kubeconfig_entry[configuring cluster access for kubectl].


==== CVS and Cloud Central

Connecting CVS and Cloud Central should be covered as a step in the link:getting-started.html[Getting Started (Onboarding Guide)].

CVS and Cloud Central are the storage layer and connective elements for Project Astra, respectively. More details on how to configure CVS on GCP may be found in their https://cloud.google.com/solutions/partners/netapp-cloud-volumes/workflow[workflow guide for CVS].

=== Pre-requisites for This Guide

==== Helm (v3)

Helm is a popular way to organize and install apps on Kubernetes. If you need to install Helm on your local CLI, you can follow https://helm.sh/docs/intro/install/[their handy install guide].

== Installing MariaDB/MySQL Apps

Installing Postgres or an app backed by MariaDB/MySQL should be as easy as any other Helm chart. The values just need to be set to consume the volumes provisioned by CVS, be deployed in a namespace other than default, and your stateful app should be available for Project Astra to work its magic on.

For instance, the https://hub.helm.sh/charts/bitnami/mariadb[Bitnami MariaDB chart] and https://hub.helm.sh/charts/bitnami/mysql[Bitnami MySQL chart] are popular ways to deploy. The charts are designed to require as few priviliges as possible, and makes use of init containers to accomplish that goal.

To install the Helm charts, you'd need to follow the instructions on the top-right sidebar for `helm repo add` and `helm install`. At the moment, the Alpha version of Project Astra does not support replicas or failovers. For testing Project Astra in Alpha, we would want to leave replication off, and check that the `global.storageClass` value in `values.yaml` is pointing to the correct storageClass. By default the Bitnami charts use a cluster's default dynamic provisioner. Since Trident (part of Project Astra) automatically sets CVS as the default storage class, we should be in good shape. You can doublecheck and see what your cluster's storageClasses are by running `kubectl get sc`. That command will produce output like the following.

----
NAME                           PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
netapp-cvs-extreme             csi.trident.netapp.io   Delete          Immediate           true                   26h
netapp-cvs-premium (default)   csi.trident.netapp.io   Delete          Immediate           true                   26h
netapp-cvs-standard            csi.trident.netapp.io   Delete          Immediate           true                   26h
standard                       kubernetes.io/gce-pd    Delete          Immediate           true                   27h
----

To change settings in your `values.yaml` you have two options. The first is opening the file, and editing it directly. The second is adding an extra argument to your usual Helm CLI command.

To view and export `values.yaml`, we can use the `helm show` command.

----
# mariaDB
helm show values bitnami/mariadb
# mySQL
helm show values bitnami/mysql
----

or

----
# mariaDB
helm show values bitnami/mariadb > my-values.yaml
# mySQL
helm show values bitnami/mysql > my-values.yaml
----

The above command should create a `my-values.yaml` file in your local directory. That file is a copy of the official `values.yaml`. You may edit the values there and test your deployment using the `-f my-values.yaml` and `--dry-run` flags.

----
# mariaDB
helm install -f my-values.yaml --namespace my-test-namespace --generate-name bitnami/mariadb --dry-run
# mySQL
helm install -f my-values.yaml --namespace my-test-namespace --generate-name bitnami/mysql --dry-run
----

If the output looks correct, you may deploy to your cluster by removing `--dry-run`. Please remember that Project Astra Alpha requires:

* `global.storageClass` value to be set to the storageClass representing either CVS or Trident (or, that storageClass is set as your cluster's default provisioner)
* The namespace to be set to something other than default, using the `--namespace` argument
* A single node deployment (multi-node and HA deployments will be supported beyond Alpha)


(C) 2020 NetApp, Inc. All rights reserved.

— NETAPP CONFIDENTIAL —

NetApp Confidential Information Subject to the Mutual Nondisclosure Agreement

All information disclosed in this document is furnished in confidence by NetApp to you with the understanding that it is NetApp confidential information pursuant to the Mutual Nondisclosure Agreement between the parties and shall be treated as such by you. The information provided in this document is for exploratory purposes only and is subject to change without notice and without liability or obligation to NetApp. NetApp retains all right, title, and interest in and to all information contained in this document, all derivative works of such information and all intellectual property rights embodied therein.
