---
sidebar: sidebar
permalink: deploy-postgres-from-helm-chart.html
summary: Learn how to deploy Postgres from a Helm chart
---

= Deploy Postgres From a Helm Chart

Coming soon.

Jira: POLARIS-360

User Story 10: As a k8s Developer/App Admin, on k8s cluster registered with Polaris I want to deploy using heml/kubectl a pre-curated PostgreSQL/MySQL application with PVC yaml file that use storage classes provided by Polaris so that I can easily manage the Application data life cycle. Engineering shall provide the versions and tested configurations of supported applications that use at least two volumes, namely PostgreSQL, MySQL/Mariadb and ready to use PVC yaml files.

== Why Project Astra and Postgres?

This guide describes how to run PostgeSQL (or Postgres) using Project Astra.  

Combining Project Astra with a stateful app (like a database) is intended to save you time and provide peace of mind. The combination means you will be running with essential guarantees like automated backups, a scalable and robust storage layer, along with all of the benefits of Kubernetes. 
 
For the first iteration, this guide will focus on Helm as the preferred way to deploy Postgres apps. Plain YAML and Operator based deployments may be covered in future guides. 

== Requirements

In order to follow along with this guide, a few components are required. We’ll need an up-to-date Kubernetes cluster (version 1.17+), kubectl installed, and kubeconfig downloaded and setup. We will also need to connect our Kubernetes cluster with Project Astra.

The link:getting-started.html[Getting Started (Onboarding Guide)] is the best option for creating your GKE cluster, and connecting to Project Astra. 

=== GKE 

GKE is supported for the current release (alpha) of Project Astra. Google Cloud has great docs for creating a new GKE cluster. 

=== Kubectl 

Kubectl is a standard tool for interacting with Kubernetes. We’ll use kubectl to deploy our initial database application. To get kubectl on your computer, follow this guide to download and install kubectl. 

=== Kubeconfig 

Kubeconfig is a file that contains credentials to allow kubectl to communicate with the Kubernetes cluster (eg GKE). To download your kubeconfig, follow this guide for configuring cluster access for kubectl. 

=== Helm (v3) 