---
sidebar: sidebar
permalink: deploy-postgres-from-helm-chart.html
summary: Learn how to deploy Postgres from a Helm chart
---

= Deploy Postgres From a Helm Chart

Learn how to exercise the Project Astra workflow by deploying Postgres from a Helm chart. After you deploy Postgres on your cluster, you can register the application with Project Astra.


NOTE: The Project Astra Alpha Program only supports Postgres 11.7.

== System Requirements

In order to deploy Postgres from a Helm chart for the Project Astra alpha program, you need the following:

* A fresh GKE cluster which has been added to Project Astra.
* Kubectl and Helm installed.
* Kubeconfig configured using the gcloud tool with a command like `gcloud container clusters get-credentials my-cluster-name`

NOTE: You must deploy your app after the cluster is added to Project Astra, not before.

== Install Postgres

To exercise the Project Astra alpha workflow, we recommend the https://hub.helm.sh/charts/bitnami/postgresql[Bitnami Postgres chart].

To install this chart, first add the repo:

----
helm repo add bitnami https://charts.bitnami.com/bitnami
----

You must deploy the chart in a namespace other than the default. Create a namespace `my-postgres-namespace`:

----
kubectl create namespace my-postgres-namespace
----

Export the default Bitnami values into a file named `my-values.yaml`. You can edit this file to change the default Bitnami values later, if necessary:

----
helm show values bitnami/postgresql > my-values.yaml
----

Deploy the Helm chart to your cluster:

----
helm install -f my-values.yaml --namespace my-postgres-namespace --generate-name bitnami/postgresql
----

After the Helm chart is deployed, it will be automatically detected by Project Astra, at which point you can register the app with Project Astra. Please note that for the Project Astra alpha program, installed applications can take up to 5 minutes to show up in the Discovered Applications list.

== Using psql

During the Project Astra alpha program, if you need to perform operations on Postgres pods (such as creating or restoring from backup), be sure to exit out of the psql client if you are using it on the pod.

Project Astra requires psql access to freeze and thaw the databases. If there is a pre-existing connection the snapshot/backup/clone operation will fail.

== Custom Postgres Requirements

If you wish to deploy your own Postgres application, please note that Project Astra Alpha requires:

* `global.storageClass` value to be set to the storageClass representing either CVS or Trident (or, that storageClass is set as your cluster's default provisioner).
* The namespace set to something other than default, using the `--namespace` argument.
* A single node deployment. Multi-node and HA deployments will be supported in future releases.

The Project Astra alpha program does not support replicas or failovers. Only single instance versions of the databases are supported. For testing Project Astra in Alpha, leave replication off, and check that the `global.storageClass` value in the Helm values is pointing to the correct storageClass.


(C) 2020 NetApp, Inc. All rights reserved.

— NETAPP CONFIDENTIAL —

NetApp Confidential Information Subject to the Mutual Nondisclosure Agreement

All information disclosed in this document is furnished in confidence by NetApp to you with the understanding that it is NetApp confidential information pursuant to the Mutual Nondisclosure Agreement between the parties and shall be treated as such by you. The information provided in this document is for exploratory purposes only and is subject to change without notice and without liability or obligation to NetApp. NetApp retains all right, title, and interest in and to all information contained in this document, all derivative works of such information and all intellectual property rights embodied therein.
