---
sidebar: sidebar
permalink: faq.html
summary: Astra FAQs
---

= Project Astra Alpha Frequently Asked Questions

== Overview

Welcome to Project Astra Alpha!

Project Astra aims to simplify your application data lifecycle management operations for Kubernetes native applications. In Alpha preview, Project Astra support is limited to Kubernetes clusters running on Google Kubernetes Engine (GKE) on Google Compute Platform (GCP). Other cloud providers will be added in later phases of the project.

Refer to the link:getting-started.html[Project Astra Alpha User Guide] for detailed instructions on going through the supported workflows in Project Astra Alpha.

The following sections provide answers to some additional questions you may come across as you go through the Alpha workflows. For any additional clarifications, please reach out to projectastra.support@netapp.com

== Access to Project Astra Alpha

**How can I access Project Astra Alpha?**

Visit Project Astra Alpha at https://astra.netapp.io.

**How can I get an invitation to Project Astra Alpha?**

Alpha preview access is limited to a select few partners. Please contact Astra Product Management, Gunna Marripudi (gunna.marripudi@netapp.com) to request access to Project Astra Alpha.

**I received an invitation to participate in Project Astra Alpha. Where do I register my company?**

Project Astra access is granted to your organization email address. This is the same email address that is registered with NetApp Cloud Central.

If you do not have a NetApp Cloud Central account yet, sign up using the same email in the invitation. You can create a NetApp Cloud Central account here: https://cloud.netapp.com.

**I’ve added my colleagues to Project Astra Alpha, but they haven’t received any email yet. What shall I do?**

Please send an email to projectastra.support@netapp.com with your organization name and the email addresses of people you wish to add to your Project Astra Alpha organization.

== Registering Kubernetes Clusters

**Where can I find my service account credentials on GCP?**

After you log in to https://console.cloud.google.com/[Google Cloud Console], your service account details will be in the **IAM and Admin** section. For more details, refer creating and managing GCP service accounts.

**I’ve set permissions as suggested in the link:getting-started.html[Getting Started Guide] on the service credentials on my GCP account. It still does not work. What shall I do?**

Please send an email to projectastra.support@netapp.com with a description of your problem and any error messages you have received.

**I’ve changed my GCP service account credentials. How do I update them on Project Astra?**

Service account details are used when adding a GKE Kubernetes cluster to Project Astra. If the required roles and permissions are retained in the Service account, then you will not need to update anything on Project Astra.

If you rename or delete the Service account, this will impact the Application and Cluster Management features of Project Astra.

**How many GCP service accounts can I register?**

Different service accounts can be used when adding GKE clusters to Project Astra as long as they have the required roles and permissions. At a minimum, for each project, you need to provide one Service account with the required roles and permissions.

**How many Kubernetes clusters can I register?**

You will need to register a minimum of two GKE Kubernetes clusters in order to exercise the Project Astra alpha features. The maximum number of clusters for the alpha program is 100.

**Do I need to install CSI drivers on my GKE cluster before adding it to Project Astra?**

No. Once a Kubernetes cluster on GKE is registered with Astra, Astra will install NetApp’s Trident CSI driver on the Kubernetes cluster. This CSI driver will be used to provision persistent volumes off of NetApp Cloud Volume Service on GCP.

**I have a GKE cluster that’s running a different Kubernetes version than supported by Project Astra. Can I add that cluster to Project Astra?**

The cluster discovery phase will not add a GKE cluster with an unsupported Kubernetes version. Project Astra provides information about supported Kubernetes version when it discovers a cluster running an unsupported Kubernetes version.

**Can Project Astra identify the required GCP services account roles and permission?**

Project Astra validates the service account roles and required permission before discovering the cluster. If any permissions or roles are missing, it provides this information in the user interface.

**How do I verify my GKE Kubernetes cluster is running supported Kubernetes version for Project Astra?**

There are two ways you can verify the GKE Kubernetes cluster version:

1. Verify it from Google cloud console. Go to **Kubernetes Engine > Cluster** and select the relevant cluster. Check the Release Channel and Master Version.

2. Project Astra checks to make sure the GKE cluster is running a supported version when the cluster is added. If Project Astra identifies an unsupported Kubernetes version, it provides this information in the user interface.

**How do I know the worker nodes in the GKE Kubernetes cluster are running a supported image type?**

The cluster discovery phase will not add a GKE cluster if the worker nodes are running an unsupported image type. If this happens, Project Astra will provide details on the supported image version (Ubuntu) in the user interface. Alternatively, you can verify the worker node image version from https://console.cloud.google.com/[Google Cloud Console].

**How do I create a GKE cluster with supported worker node image type?**

When you create a GKE cluster or node pool, you can choose the operating system image that runs on each node. You can also upgrade an existing cluster to use a different node image type.

**I would like to add different GKE clusters from different GCP projects. Is this supported in Project Astra?**

Yes, you can add different GKE clusters from different GCP projects as long as;

* The clusters and worker nodes are running a supported version
* Service accounts have required roles and permissions
* The network configuration within GCP projects allows it to communicate with the GCP object store.

**How do I verify my GKE cluster was added successfully to Project Astra?**

When you add the cluster, the user interface will show the status update and any error messages. When the cluster is added successfully, the status of the GKE cluster in the **Compute** section will be `Available`.

Alternatively, you can also verify if trident operator and CSI drivers deployed successfully under the namespace `trident` by running the kubectl commands:

----
kubectl get pods -n trident
----

or

----
kubectl get pods -|grep trident
----

**I have added additional worker nodes to my GKE cluster after adding to Project Astra. The new nodes are not showing up in the Project Astra Compute section. What should I do next?**

New worker nodes will be automatically discovered by Project Astra. If the new nodes are not visible in Project Astra, check if the new worker nodes are running the supported image type. You can also verify the health of the new worker nodes by using the `kubectl get nodes` command.

**Can I remove my Kubernetes cluster from Project Astra?**

Yes, you can remove one or more Kubernetes cluster from Project Astra at the same time. Be sure to delete any snapshots or backups and de-register the applications before removing the cluster.

**What happens to my applications and data after removing the GKE cluster from Project Astra?**

Applications, data, snapshots, and backups will remain available in Project Astra until you delete them.

**Will NetApp Trident be uninstalled when I remove a GKE cluster from Project Astra?**

Trident will not be uninstalled from a cluster when you remove it from Project Astra.

== Registering Applications

**I have deployed my applications using Helm and kubectl. My newly-deployed application is not showing up on the Discovered Apps list. What can I check to identify the problem?**

When an application is successfully deployed, Project Astra will automatically discover the application and add it to the Discovered Apps list. When applications are not listed in **Discovered Apps**, check the status and health of the Kubernetes pod by running `kubectl get pod -A |grep [pod name]`. If the pods are healthy and running, check to see if the application is listed under **Ignored Apps**.

**I’ve deployed my applications using Helm and kubectl. I don’t see any of my application’s PVCs bound to GCP CVS. What could be wrong?**

The NetApp Trident operator sets the default storage class to `netapp-cvs-premium` after it is successfully added to Project Astra. When an application's PVCs are not bound to Cloud Volumes Services GCP, there are a few steps you can take:

* Run `kubectl get sc` and check to see if the default `storageclass` is set to `netapp-cvs`.
* Check the yaml file or helm chart that used to deploy application and see if a different storage class is defined.
* Check to make sure the worker node image type is Ubuntu and the NFS mount succeeded.

**I’ve an existing cluster with applications using GCP persistent disks. Can I register those applications with Astra?**

Applications using GCP PVCs will be discovered and registered by Project Astra. However, these applications will not support any of the data management operations offered by Project Astra.

**How many applications can I simultaneously register with Project Astra Alpha?**

Multiple applications from different GKE cluster can be registered at the same time.

**I moved my application to the Ignored list by mistake. Can I register the applications that are on the Ignore list?**

Yes, applications on the Ignored list can be registered successfully. Data management operations will function as usual after successful registration.

**Can I register applications that are not MySQL or PostgreSQL?**

Yes; we can use data management services offered by Project Astra on any persistent volumes managed by GCP CVS. However, application-level consistent snapshots, backup/migration, etc. will not be orchestrated through Project Astra.

**Can Project Astra deploy an application?**

Astra does not deploy an application. Applications must be deployed outside of Astra by using kubectl or helm charts.

**What storage classes can I use in my PVCs to support Astra data management operations?**

As part of adding the GKE cluster to Project Astra, NetApp Trident will create three different storage classes for Cloud Volume Services in GCP. Astra data management operations are only supported on storage class `netapp-cvs-extreme`, `netapp-cvs-premium` (default), and `netapp-cvs-standard`.

**What happens to applications after de-registering from Project Astra?**

Applications, data and any backups or snapshots existing will remain available. Data management operations will not be available for de-registered applications or any backups or snapshots which belong to it.

== Data Management Operations

**My application uses several PVs; why don’t I see volume level snapshots?**

Project Astra aims to simplify application data lifecycle management. Using Project Astra eliminates the need for individual volume-level data management operations. A snapshot operation on an application by Project Astra includes snapshot of all the PVs which are bound to the application’s PVCs.

**Can I create snapshot schedules and assign retention schedules?**

The Project Astra Alpha program supports on-demand snapshot, backup and retention. We expect to add schedule-based snapshot, backup and retention in the Project Astra Beta program.

**What is the different between snapshot and backup?**

**Snapshot** refers to local snapshots, where data is stored as part of the provisioned volumes. Given that they are stored on the same provisioned volume, they are usually faster. Local snapshots are used to restore the application to an earlier point in time.

**Backups** are stored on object storage. They could be slower compared to the local snapshots. However, they can be accessed across regions in the cloud. Backups are used for migrating applications across regions in the cloud. Also, a user can choose to have longer retention period for backups.

**Can I manage snapshots taken by Astra directly through CVS snapshot management interface or object storage?**

Snapshots and backups taken through Project Astra can only be managed through Project Astra. Project Astra provides interfaces to create, view and delete the snapshots and backups. If data objects associated with these snapshots are managed outside of Astra interface, it can result in intermittent behavior.

(C) 2020 NetApp, Inc. All rights reserved.

— NETAPP CONFIDENTIAL —

NetApp Confidential Information Subject to the Mutual Nondisclosure Agreement

All information disclosed in this document is furnished in confidence by NetApp to you with the understanding that it is NetApp confidential information pursuant to the Mutual Nondisclosure Agreement between the parties and shall be treated as such by you. The information provided in this document is for exploratory purposes only and is subject to change without notice and without liability or obligation to NetApp. NetApp retains all right, title, and interest in and to all information contained in this document, all derivative works of such information and all intellectual property rights embodied therein.
