---
sidebar: sidebar
permalink: gcp-permissions-checklist.html
summary: Check your GCP account permissions before adding it to Project Astra.
---

= GCP Account Permissions Checklist
:imagesdir: assets/gcp-credentials/

Before you add your GCP account to Project Astra, check to be sure you have all the correct permissions. You need to check two sets of permissions:

* API access for your Project
* Roles for your service account

WARNING: The free introductory tier for Google Cloud Platform only allows you to create one Kubernetes cluster at a time, among other limitations.

== Project: API Access

Your project needs to have the following APIs enabled:

* Google Kubernetes Engine
* NetApp Cloud Volumes Service
* Cloud Storage
* Cloud Storage JSON API
* Service Usage
* Cloud Resource Manager API

**Related Article**

* link:/gcp-create-project.html[Create a GCP Project]

== Service Account: Roles

Your service account needs to have the following roles enabled:

* Kubernetes Engine Admin
* Cloud Volumes Admin
* Storage Admin
* Service Usage Viewer

**Related Articles**

* link:/gcp-create-service-account-browser.html[Create a Service Account (browser)]
* link:/gcp-create-service-account-gcloud.html[Create a Service Account (gcloud)]


'''

(C) 2020 NetApp, Inc. All rights reserved.

— NETAPP CONFIDENTIAL —

NetApp Confidential Information Subject to the Mutual Nondisclosure Agreement
All information disclosed in this document is furnished in confidence by NetApp to you with the understanding that it is NetApp confidential information pursuant to the Mutual Nondisclosure Agreement between the parties and shall be treated as such by you. The information provided in this document is for exploratory purposes only and is subject to change without notice and without liability or obligation to NetApp. NetApp retains all right, title, and interest in and to all information contained in this document, all derivative works of such information and all intellectual property rights embodied therein.
