---
sidebar: sidebar
permalink: index.html
summary: Welcome to the documentation portal for Project Astra (Alpha).
---

= Project Astra Documentation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

Welcome to the Project Astra documentation.

== Getting Started

* link:getting-started.html[Getting Started Guide]
* link:install-kubectl.html[Install Kubectl]
* link:invite-users.html[Invite Users]
* link:test-plan.html[Test Plan]

Access the Project Astra alpha program at: https://astra.netapp.io

(C) 2020 NetApp, Inc. All rights reserved.

— NETAPP CONFIDENTIAL —

NetApp Confidential Information Subject to the Mutual Nondisclosure Agreement

All information disclosed in this document is furnished in confidence by NetApp to you with the understanding that it is NetApp confidential information pursuant to the Mutual Nondisclosure Agreement between the parties and shall be treated as such by you. The information provided in this document is for exploratory purposes only and is subject to change without notice and without liability or obligation to NetApp. NetApp retains all right, title, and interest in and to all information contained in this document, all derivative works of such information and all intellectual property rights embodied therein.
