---
sidebar: sidebar
permalink: mongodb-deploy-from-helm-chart.html
summary: Learn how to deploy MongoDB from a Helm chart
---

= Deploy MongoDB From a Helm Chart

Learn how to exercise the Project Astra workflow by deploying MongoDB from a Helm chart. After you deploy MongoDB on your cluster, you can register the application with Project Astra.

== System Requirements

In order to deploy MongoDB from a Helm chart for the Project Astra alpha program, you need the following:

* A fresh GKE cluster which has been added to Project Astra.
* Updated versions of Helm (version 3.2+) and Kubectl installed.
* Kubeconfig configured using the gcloud tool with a command like `gcloud container clusters get-credentials my-cluster-name`

== Namespace Requirements

**You must deploy your app in a namespace other than the default.** In the following example, we create and use the namespace `testdb` for the deployment.

**A namespace which is empty for more than 60 seconds will be ignored by Project Astra.** Thus, you want to be sure to deploy your app into your namespace within one minute after you create the namespace.

In the following example, we use `&&` to concatenate the commands for creating the namespace and deploying the app. We recommend this approach, as it ensures the commands are run in sequence even if you get interrupted.

We recommend the use of `&&` instead of `;` to concatenate commands. `&&` is conditional, and only runs the second command if the first command completes successfully.


NOTE: You must deploy your app after the cluster is added to Project Astra, not before.

== Install MongoDB

To exercise the Project Astra alpha workflow, we recommend you use the Helm chart which we have customized for Project Astra. Contact our TME team to get a copy of this chart.

NOTE: You must deploy the Helm chart in a namespace other than the default.

Create the namespace and deploy MongoDB with the command:

----
kubectl create namespace testdb && helm install ./mongodb --namespace testdb --generate-name
----

After the Helm chart is deployed, it will be automatically detected by Project Astra, at which point you can register the app with Project Astra. Please note that for the Project Astra alpha program, it can take up to 5 minutes for applications to show up in the Discovered Applications list after being installed.



'''


(C) 2020 NetApp, Inc. All rights reserved.

— NETAPP CONFIDENTIAL —

NetApp Confidential Information Subject to the Mutual Nondisclosure Agreement

All information disclosed in this document is furnished in confidence by NetApp to you with the understanding that it is NetApp confidential information pursuant to the Mutual Nondisclosure Agreement between the parties and shall be treated as such by you. The information provided in this document is for exploratory purposes only and is subject to change without notice and without liability or obligation to NetApp. NetApp retains all right, title, and interest in and to all information contained in this document, all derivative works of such information and all intellectual property rights embodied therein.
