---
sidebar: sidebar
permalink: deploy-mongodb-from-helm-chart.html
summary: Learn how to deploy MongoDB from a Helm chart
---

= Deploy MongoDB From a Helm Chart

Learn how to exercise the Project Astra workflow by deploying MongoDB from a Helm chart. After you deploy MongoDB on your cluster, you can register the application with Project Astra.

== System Requirements

In order to deploy MongoDB from a Helm chart for the Project Astra alpha program, you need the following:

* A fresh GKE cluster which has been added to Project Astra.
* Kubectl and Helm installed.
* Kubeconfig configured using the gcloud tool with a command like `gcloud container clusters get-credentials my-cluster-name`

NOTE: You must deploy your app after the cluster is added to Project Astra, not before.

== Install MongoDB

To exercise the Project Astra alpha workflow, we recommend the Helm chart from the default repo.

To install this chart, first add the repo:

----
helm repo add stable https://kubernetes-charts.storage.googleapis.com
----

NOTE: You must deploy the Helm chart in a namespace other than the default.

Deploy MongoDB with the command:

----
helm install stable/mongodb --namespace testdb --create-namespace --generate-name
----

This command does the following:

* Creates a new namespace `testdb`.
* Deploys MongoDB on that namespace.


After the Helm chart is deployed, it will be automatically detected by Project Astra, at which point you can register the app with Project Astra. Please note that for the Project Astra alpha program, it can take up to 5 minutes for applications to show up in the Discovered Applications list after being installed.



'''


(C) 2020 NetApp, Inc. All rights reserved.

— NETAPP CONFIDENTIAL —

NetApp Confidential Information Subject to the Mutual Nondisclosure Agreement

All information disclosed in this document is furnished in confidence by NetApp to you with the understanding that it is NetApp confidential information pursuant to the Mutual Nondisclosure Agreement between the parties and shall be treated as such by you. The information provided in this document is for exploratory purposes only and is subject to change without notice and without liability or obligation to NetApp. NetApp retains all right, title, and interest in and to all information contained in this document, all derivative works of such information and all intellectual property rights embodied therein.
