---
sidebar: sidebar
permalink: mysql-mariadb-work-with-project-astra.html
summary: Learn how to deploy MySQL/MariaDB from a Helm chart
---

= Work With MySQL/MariaDB on Project Astra

This guide focuses on Helm as the preferred way to deploy Postgres apps. Plain YAML and Operator-based deployments may be covered in future guides.

For express instructions on launching MySQL/MariaDB on Project Astra, see link:mysql-mariadb-deploy-from-helm-chart.html[Deploy MySQL/MariaDB from a Helm Chart].

NOTE: MySQL 0.3.22 and MariaDB 14.14 are the only versions supported in the Project Astra alpha program.


== Requirements

In order to deploy MySQL/MariaDB from a Helm chart on a cluster registered with Project Astra, you will need the following:

**GKE Cluster**

An up-to-date Kubernetes cluster (version 1.17+) which is connected to Project Astra. For help creating your GKE cluster and connecting it to Project Astra, see the link:getting-started.html[Getting Started Guide].

**Kubectl**

Kubectl is a standard tool for interacting with Kubernetes. For more information, see the guide https://kubernetes.io/docs/tasks/tools/install-kubectl/[Install and Set Up kubectl] in the official Kubernetes documentation.

**Kubeconfig**

The Kubeconfig file contains the credentials which let kubectl communicate with your Kubernetes cluster. to learn how to download your GKE Kubeconfig file, see the Google Cloud guide for https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#generate_kubeconfig_entry[configuring cluster access for kubectl].

**CVS and Cloud Central**

CVS and Cloud Central are the storage layer and connective elements for Project Astra, respectively. More details on how to configure CVS on GCP may be found in the https://cloud.google.com/solutions/partners/netapp-cloud-volumes/workflow[workflow guide for CVS].

**Helm (v3)**

Helm is a popular way to organize and install apps on Kubernetes. To install Helm on your local computer, follow https://helm.sh/docs/intro/install/[their handy install guide].

**MySQL/MariaDB Requirements**

For a MySQL/MariaDB application, Project Astra Alpha requires:

* `global.storageClass` value to be set to the storageClass representing either CVS or Trident (or, that storageClass is set as your cluster's default provisioner)
* The namespace to be set to something other than default, using the `--namespace` argument
* A single node deployment. Multi-node and HA deployments will be supported in future releases.

The Project Astra alpha program does not support replicas or failovers. Only single instance versions of the databases are supported. For testing Project Astra in Alpha, leave replication off, and check that the `global.storageClass` value in `values.yaml` is pointing to the correct storageClass.


== Install MariaDB/MySQL

For the Project Astra alpha program, we recommend the custom Helm chart we have created for this purpose. For instructions on how to deploy from this custom chart, see link:mysql-mariadb-deploy-from-helm-chart.html[Deploy MySQL/MariaDB from a Helm Chart].

The values need to be set to consume the volumes provisioned by CVS, be deployed in a namespace other than default, and your stateful app needs to be available to Project Astra.

By default the Bitnami Postgres chart uses a cluster's default dynamic provisioner. Since Trident (part of Project Astra) automatically sets CVS as the default storage class, you should be in good shape. Use `kubectl get sc` to see what your cluster's storageClasses are. This produces output like the following:

----
NAME                           PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
netapp-cvs-extreme             csi.trident.netapp.io   Delete          Immediate           true                   26h
netapp-cvs-premium (default)   csi.trident.netapp.io   Delete          Immediate           true                   26h
netapp-cvs-standard            csi.trident.netapp.io   Delete          Immediate           true                   26h
standard                       kubernetes.io/gce-pd    Delete          Immediate           true                   27h
----

You have two options for changing settings in your `values.yaml`. The first option is to open the file and edit it directly. The second option is to add an extra argument to your usual Helm CLI command.

To view and export `values.yaml`, use the `helm show` command:

----
# mariaDB
helm show values bitnami/mariadb
# mySQL
helm show values bitnami/mysql
----

or

----
# mariaDB
helm show values bitnami/mariadb > my-values.yaml
# mySQL
helm show values bitnami/mysql > my-values.yaml
----

This creates a `my-values.yaml` file in your local directory. That file is a copy of the official `values.yaml`.

== Dry Run

Before deploying, you can do a dry run to make sure everything is set up correctly.

To do this, edit the values in the `my-values.yaml` file you created in the previous step. Test your deployment using the `-f my-values.yaml` and `--dry-run` flags:

----
# MariaDB
helm install -f my-values.yaml --namespace testdb --generate-name bitnami/mariadb --dry-run

# MySQL
helm install -f my-values.yaml --namespace testdb --generate-name bitnami/mysql --dry-run
----

Before we can run the helm charts for real, we need to first create the namespace. We've chosen `testdb` and may use kubectl to create that namespace.

----
kubectl create namespace testdb
----

If the output from our dry run looks correct, we may deploy to your cluster by removing `--dry-run`.

NOTE: For the Project Astra alpha program, installed applications can take up to 5 minutes to show up in the Discovered Applications list.a)




'''

(C) 2020 NetApp, Inc. All rights reserved.

— NETAPP CONFIDENTIAL —

NetApp Confidential Information Subject to the Mutual Nondisclosure Agreement

All information disclosed in this document is furnished in confidence by NetApp to you with the understanding that it is NetApp confidential information pursuant to the Mutual Nondisclosure Agreement between the parties and shall be treated as such by you. The information provided in this document is for exploratory purposes only and is subject to change without notice and without liability or obligation to NetApp. NetApp retains all right, title, and interest in and to all information contained in this document, all derivative works of such information and all intellectual property rights embodied therein.
