---
sidebar: sidebar
permalink: postgres-deploy-from-helm-chart.html
summary: Learn how to deploy Postgres from a Helm chart
---

= Deploy Postgres From a Helm Chart

Learn how to exercise the Project Astra workflow by deploying Postgres from a Helm chart. After you deploy Postgres on your cluster, you can register the application with Project Astra.


NOTE: The Project Astra Alpha Program only supports Postgres 11.7.

== System Requirements

In order to deploy Postgres from a Helm chart for the Project Astra alpha program, you need the following:

* A fresh GKE cluster which has been added to Project Astra.
* Updated versions of Helm (version 3.2+) and Kubectl installed.
* Kubeconfig configured using the gcloud tool with a command like `gcloud container clusters get-credentials my-cluster-name`

== Namespace Requirements

**You must deploy your app in a namespace other than the default.** In the following example, we create and use the namespace `testdb` for the deployment.

**A namespace which is empty for more than 60 seconds will be ignored by Project Astra.** Thus, you want to be sure to deploy your app into your namespace within one minute after you create the namespace.

In the following example, we use `&&` to concatenate the commands for creating the namespace and deploying the app. We recommend this approach, as it ensures the commands are run in sequence even if you get interrupted.

We recommend the use of `&&` instead of `;` to concatenate commands. `&&` is conditional, and only runs the second command if the first command completes successfully.

NOTE: You must deploy your app after the cluster is added to Project Astra, not before.

== Install Postgres

To exercise the Project Astra alpha workflow, we recommend the https://hub.helm.sh/charts/bitnami/postgresql[Bitnami Postgres chart].

To install this chart, first add the repo:

----
helm repo add bitnami https://charts.bitnami.com/bitnami
----

NOTE: You must deploy the Helm chart in a namespace other than the default.

Deploy Postgres with the command:

----
kubectl create namespace testdb && helm install bitnami/postgresql --namespace testdb --set postgresqlPassword=U9dH9HT4pWS,postgresqlDatabase=test_db --generate-name
----

This does the following:

* Creates the `testdb` namespace.
* Deploys Postgres on the `testdb` namespace.
* Creates a database named `test_db`
* Creates a user `test_db_user` with password `U9dH9HT4pWS`

WARNING: This method of setting the password at deployment is insecure. Only use this command when setting up Postgres for a sandbox deployment to use Project Astra alpha program. We do not recommend this for a production environment.

After the Helm chart is deployed, it will be automatically detected by Project Astra, at which point you can register the app with Project Astra. Please note that for the Project Astra alpha program, it can take up to 5 minutes for applications to show up in the Discovered Applications list after being installed.



'''


(C) 2020 NetApp, Inc. All rights reserved.

— NETAPP CONFIDENTIAL —

NetApp Confidential Information Subject to the Mutual Nondisclosure Agreement

All information disclosed in this document is furnished in confidence by NetApp to you with the understanding that it is NetApp confidential information pursuant to the Mutual Nondisclosure Agreement between the parties and shall be treated as such by you. The information provided in this document is for exploratory purposes only and is subject to change without notice and without liability or obligation to NetApp. NetApp retains all right, title, and interest in and to all information contained in this document, all derivative works of such information and all intellectual property rights embodied therein.
