sidebar:
  entries:
    - title: Project Astra docs
      url: /index.html
    - section: get-started
    - section: use
    - section: learn
    - section: solutions
    - section: support

homepage:
  tiles:
    - title: Get Started
      image: ./media/outline_directions_run_black_18dp.png
      links:
        - title: Learn about Project Astra
          summary: Understand how Project Astra works.
          url: /get-started/intro.html
        - title: Quick start
          summary: Get started quickly with Project Astra.
          url: /get-started/quick-start.html
        - title: FAQ
          summary: Read frequently asked questions.
          url: /get-started/faq.html
    - title: Use Project Astra
      links:
        - title: Register applications
          summary: Start managing your apps from Project Astra.
          url: /use/manage-apps.html
        - title: Protect your apps
          summary: Create recovery points for your apps in case of failure.
          url: /use/protect-apps.html
        - title: Migrate an app
          summary: Migrate an app to another cluster.
          url: /use/coming-soon.html
    - title: Demos & tutorials
      links:
        - title: Project Astra videos
          summary: Watch videos that show how to use Project Astra.
          url: /get-started/videos.html
        - title: Deploy MariaDB
          summary: Deploy MariaDB from a Helm chart and register it with Project Astra.
          url: /solutions/mariadb-deploy-from-helm-chart.html
        - title: Deploy MySQL
          summary: Deploy MySQL from a Helm chart and register it with Project Astra.
          url: /solutions/mysql-deploy-from-helm-chart.html
    - title: Blogs & community
      links:
        - title: Project Astra - Stateful Lessons for a Multi-Cloud World
          summary: How Project Astra provides robust storage, easy-to-consume data services, and application and data portability.
          url: https://blog.netapp.com/project-astra-stateful-lessons
        - title: Kubernetes Hub
          summary: A curated collection of blog postings to learn more about Kubernetes and persistent storage.
          url: https://cloud.netapp.com/kubernetes-hub
        - title: Community Forum
          summary: Ask questions, exchange ideas, and share best practices.
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
