sidebar:
  entries:
    - title: Astra Control Service docs
      url: /index.html
    - section: release-notes
    - section: get-started
    - section: use
    - title: Automate with REST
      url: /automation.html
    - section: learn
    - section: solutions
    - section: support
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
    - title: Get started
      #image: ./media/outline_directions_run_black_18dp.png
      links:
        - title: Learn about Astra Control Service
          url: /get-started/intro.html
        - title: Quick start
          url: /get-started/quick-start.html
        - title: FAQ
          url: /get-started/faq.html
    - title: Use Astra Control Service
      links:
        - title: Manage applications
          url: /use/manage-apps.html
        - title: Protect your apps
          url: /use/protect-apps.html
        - title: Migrate an app
          url: /use/clone-apps.html
        - title: Set up billing
          url: /use/set-up-billing.html
    - title: Demos & tutorials
      links:
        - title: Astra Control Service videos
          url: /get-started/videos.html
        - title: Deploy MariaDB
          url: /solutions/mariadb-deploy-from-helm-chart.html
        - title: Deploy MySQL
          url: /solutions/mysql-deploy-from-helm-chart.html
    - title: Solution briefs
      links:
        - title: DataStax Enterprise & Apache Cassandra with Astra Control
          url: https://cloud.netapp.com/hubfs/SB-4134-0321-DataStax-Cassandra-Guide%20(1).pdf
        - title: PostgreSQL DBaaS with Astra Control
          url: https://cloud.netapp.com/hubfs/SB-4122-0221-PostgresSQL-DBaaS-with-Astra%20(2).pdf
        - title: MySQL DBaaS with Astra Control
          url: https://cloud.netapp.com/hubfs/SB-4110-0221-MySQL-Astra%20(2).pdf
        - title: Simplify Jenkins lifecycle management
          url: https://cloud.netapp.com/hubfs/SB-4100-Jenkins%20(2).pdf
    - title: Blogs & community
      links:
        - title: Slack channel
          url: https://netapppub.slack.com/#astra
        - title: Astra Control – Simplifying appl data management for the hybrid cloud
          url: https://cloud.netapp.com/blog/blg-astra-control-simplifying-kubernetes-application-data-management-for-the-hybrid-cloud
        - title: Kubernetes Hub on Cloud Central
          url: https://cloud.netapp.com/kubernetes-hub
