---
settings:
  name: Astra Control Service
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  filter:
    label: Cloud provider
    default: All cloud providers
    options:
      - name: Google Cloud
        alias: Google Cloud
        id: gcp
      - name: Microsoft Azure
        alias: Azure
        id: azure
sidebar:
  entries:
    - title: Astra Control Service docs
      url: /index.html
    - section: release-notes
    - section: get-started
    - section: use
    - title: Automate with the Astra Control REST API
      url: /automation.html
    - section: learn
  #  - section: solutions (retired with DOC-4309)
    - section: support
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Astra
  repo: astra-family

homepage:
  tiles:
    - title: Get started
      #image: ./media/outline_directions_run_black_18dp.png
      links:
        - title: Learn about Astra Control Service
          url: /get-started/intro.html
        - title: Quick start
          url: /get-started/quick-start.html
        - title: FAQ
          url: /get-started/faq.html
    - title: Use Astra Control Service
      links:
        - title: Manage applications
          url: /use/manage-apps.html
        - title: Protect your apps
          url: /use/protect-apps.html
        - title: Migrate an app
          url: /use/clone-apps.html
        - title: Set up billing
          url: /use/set-up-billing.html
    - title: Use the Astra Control REST API
      links:
        - title: Get started
          url: https://docs.netapp.com/us-en/astra-automation/get-started/before_get_started.html
        - title: API reference
          url: https://docs.netapp.com/us-en/astra-automation/reference/api_reference.html
        - title: API workflows
          url: https://docs.netapp.com/us-en/astra-automation/workflows/workflows_before.html
    - title: Demos & tutorials
      links:
        - title: Astra Control Service videos
          url: /get-started/videos.html
        - title: Deploy Jenkins
          url: /solutions/jenkins-deploy-from-helm-chart.html
        - title: Deploy MariaDB
          url: /solutions/mariadb-deploy-from-helm-chart.html
        - title: Deploy MySQL
          url: /solutions/mysql-deploy-from-helm-chart.html
        - title: Deploy Postgres
          url: /solutions/postgres-deploy-from-helm-chart.html
    - title: Astra Control Center
      links:
        - title: Intro to Astra Control Center
          url: https://docs.netapp.com/us-en/astra-control-center/concepts/intro.html
        - title: What's new
          url: https://docs.netapp.com/us-en/astra-control-center/release-notes/whats-new.html
        - title: Quick start
          url: https://docs.netapp.com/us-en/astra-control-center/get-started/quick-start.html
    - title: Solution briefs
      links:
        - title: DataStax Enterprise & Apache Cassandra with Astra Control
          url: https://cloud.netapp.com/hubfs/SB-4134-0321-DataStax-Cassandra-Guide%20(1).pdf
        - title: PostgreSQL DBaaS with Astra Control
          url: https://cloud.netapp.com/hubfs/SB-4122-0221-PostgresSQL-DBaaS-with-Astra%20(2).pdf
        - title: MySQL DBaaS with Astra Control
          url: https://cloud.netapp.com/hubfs/SB-4110-0221-MySQL-Astra%20(2).pdf
        - title: Simplify Jenkins lifecycle management
          url: https://cloud.netapp.com/hubfs/SB-4100-Jenkins%20(2).pdf
    - title: Blogs & community
      links:
        - title: Slack "containers" channel
          url: https://netapp.io/slack
        - title: Astra Control blog
          url: https://cloud.netapp.com/blog/topic/astra
        - title: Astra Control – Simplifying app data management for the hybrid cloud
          url: https://cloud.netapp.com/blog/blg-astra-control-simplifying-kubernetes-application-data-management-for-the-hybrid-cloud
        - title: Kubernetes Hub on Cloud Central
          url: https://cloud.netapp.com/kubernetes-hub
