---
settings:
  name: Astra Control Service
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  filter:
    label: Cloud provider
    default: All cloud providers
    options:
      - name: Amazon Web Services
        alias: Amazon Web Services
        id: aws
      - name: Google Cloud
        alias: Google Cloud
        id: gcp
      - name: Microsoft Azure
        alias: Azure
        id: azure
  rss_page: "release-notes/whats-new.html"

sidebar:
  entries:
    - title: Astra Control Service docs
      url: /index.html
    - section: release-notes
    - section: get-started
    - section: learn
    - section: use
    - section: use-acp
    - title: Automate with the Astra Control REST API
      url: /automation.html
  #  - section: solutions (retired with DOC-4309)
    - section: support
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Astra
  repo: astra-family
  sidebar_label: All Astra documentation
    
