---
sidebar: sidebar
permalink: learn/aws-storage.html
keywords: service level, storage class, storage classes, pv size, persistent volume size, volume size, bandwidth, performance
summary: Astra Control Service can use Amazon Elastic Block Store (EBS) or Amazon FSxN as the storage backends for Elastic Kubernetes Service (EKS) clusters. You should understand how choosing a storage class and persistent volume size can help you meet your performance objectives.
---

= Storage classes and performance for AWS clusters
:hardbreaks:
:icons: font
:imagesdir: ../media/learn/

[.lead]
Astra Control Service can use Amazon Elastic Block Store (EBS) or Amazon FSxN as the storage backends for Amazon Elastic Kubernetes Service (EKS) clusters.

== Amazon Elastic Block Store (EBS)
When you use EBS as the storage backend for EKS clusters, you can configure some storage class parameters. For more information about what the parameters mean and how to configure them, see https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs[the Kubernetes documentation^].

You can use several different types of volumes with EBS:

* Solid state drives (SSD)
* Hard disk drives (HDD)
* Previous generation

For more information on each type of volume and their performance, see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html[the Amazon EBS documentation^]. For pricing information, see https://aws.amazon.com/ebs/pricing/[Amazon EBS pricing^].

== Amazon FSxN
When you use FSxN as the storage backend for AWS clusters, I/O performance depends on the configuration of the filesystem and the characteristics of your workloads. For specific information on FSxN performance, see https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/performance.html[Amazon FSx for NetApp ONTAP performance^]. For pricing information, see https://aws.amazon.com/fsx/netapp-ontap/pricing/[Amazon FSx for NetApp ONTAP Pricing^].
