---
sidebar: sidebar
permalink: learn/azure-storage.html
keywords: service level, cvs, cvs-performance, storage class, storage classes, pv size, persistent volume size, volume size, bandwidth, performance
summary: Astra Control Service uses Azure NetApp Files as the storage backend for Azure Kubernetes Service (AKS) clusters. You should understand how choosing a storage class and persistent volume size can help you meet your performance objectives.
---

= Storage classes and PV size for AKS clusters
:hardbreaks:
:icons: font
:imagesdir: ../media/learn/

[.lead]
Astra Control Service supports Azure NetApp Files, Azure managed disks, or or NetApp Cloud Volumes ONTAP as the storage backend for Azure Kubernetes Service (AKS) clusters.

== Azure NetApp Files

Astra Control Service supports Azure NetApp Files as the storage backend for Azure Kubernetes Service (AKS) clusters. You should understand how choosing a storage class and persistent volume size can help you meet your performance objectives.

=== Service levels and storage classes

Azure NetApp Files supports three service levels: Ultra storage, Premium storage, and Standard storage. Each of these service levels are designed for different performance needs:

Ultra storage:: Provides up to 128 MiB/s of throughput per 1 TiB.
Premium storage:: Provides up to 64 MiB/s of throughput per 1 TiB.
Standard storage:: Provides up to 16 Mib/s of throughput per 1 TiB.

These service levels are an attribute of a capacity pool. You need to set up a capacity pool for each service level that you want to use with your Kubernetes clusters. link:../get-started/set-up-microsoft-azure-with-anf.html[Learn how to set up capacity pools].

Astra Control Service uses these service levels as storage classes for your persistent volumes. When you add Kubernetes clusters to Astra Control Service, you're prompted to choose either Ultra, Premium, or Standard as the default storage class. The names of the storage classes are _netapp-anf-perf-ultra_, _netapp-anf-perf-premium_, and _netapp-anf-perf-standard_.

https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-service-levels[Learn more about these service levels in the Azure NetApp Files docs^].

=== Persistent volume size and performance

As described above, the throughput for each service level is per 1 TiB of provisioned capacity. That means larger volumes provide better performance. So you should take both capacity and performance needs into consideration when provisioning volumes.

=== Minimum volume size

Astra Control Service provisions persistent volumes using a minimum volume size of 100 GiB, even if the PVC asks for a smaller volume size. For example, if the PVC in a Helm chart asks for 6 GiB, Astra Control Service automatically provisions a 100 GiB volume.

=== Application backups
If you back up an application that resides on Azure NetApp Files storage, Astra Control Service automatically temporarily expands the capacity pool if there is not enough capacity for Astra Control Service to use during the backup operation. After the backup is complete, Astra Control Service shrinks the capacity pool to its previous size. Depending on your Azure subscription, you might incur storage charges when this happens. You can see a history of capacity pool resize events in the *Activity* page event log.

If the capacity pool exceeds the maximum size allowed by the Azure subscription during the resize operation, the backup operation fails, and a warning is triggered from the Azure API.

== Azure managed disks

Astra Control Service supports Azure managed disks as a storage backend option. This service provides block-level storage that is managed by Azure.

https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview[Learn more about Azure managed disks^].

== NetApp Cloud Volumes ONTAP
For specific information on configuring NetApp Cloud Volumes ONTAP, including performance recommendations, visit the https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/[NetApp Cloud Volumes ONTAP documentation^].