---
sidebar: sidebar
permalink: learn/choose-class-and-size.html
keywords: service level, cvs, cvs-performance, storage class, storage classes, pv size, persistent volume size, volume size, bandwidth, performance
summary: Astra uses Cloud Volumes Service for Google Cloud as the backend storage for persistent volumes. You should understand how choosing a service level, storage class, and persistent volume size can help you meet your performance objectives.
---

= Choosing a service type, storage class, and PV size
:hardbreaks:
:icons: font
:imagesdir: ../media/learn/

[.lead]
Astra uses Cloud Volumes Service for Google Cloud as the backend storage for persistent volumes. You should understand how choosing a service type, storage class, and persistent volume size can help you meet your performance objectives.

== Service types for Cloud Volumes Service for Google Cloud

Cloud Volumes Service for Google Cloud provides two service types: _CVS_ and _CVS-Performance_. These service types are supported in specific Google Cloud regions. https://cloud.netapp.com/cloud-volumes-global-regions#cvsGcp[Go to NetApp Cloud Central's Global Regions Maps^] to identify the service type that's supported in the Google Cloud region where your cluster resides.

If your Kubernetes clusters must reside in a specific region, then you'll be using the service type supported in that region.

But if you have the flexibility to select between Google Cloud regions, then we recommend the following based on your performance requirements:

* For K8s applications that have medium-to-high performance storage needs, choose a Google Cloud region that supports CVS-Performance and use the Premium or Extreme storage class. Such workloads include AI/ML pipelines, CI/CD pipelines, media processing, and databases including relational, noSQL, time series, etc.

* For K8s applications that have low-to-medium storage performance needs (web apps, general purpose file storage, etc.), choose a Google Cloud region that supports CVS or CVS-Performance, with the Standard storage class.

== Service level for CVS

One service level is supported with the CVS service type: Standard. https://cloud.google.com/solutions/partners/netapp-cloud-volumes/service-levels[Learn more about this service level in the Cloud Volumes Service for Google Cloud documentation^].

== Service level for CVS-Performance

Three service levels are supported with the CVS-Performance service type: Standard, Premium, and Extreme. When you add compute to Astra, you're prompted to choose Standard, Premium, or Extreme as the default storage class for the cluster. Each of these service levels are designed for different capacity and bandwidth needs.

https://cloud.google.com/solutions/partners/netapp-cloud-volumes/selecting-the-appropriate-service-level-and-allocated-capacity-for-netapp-cloud-volumes-service#service_levels[Learn more about these service levels in the Cloud Volumes Service for Google Cloud documentation^].

== PV size

As you can see from the Google Cloud docs, the allowed bandwidth for each service level is per GiB of provisioned capacity. That means larger volumes will provide better performance.

Be sure to read through the pages linked to above. They include cost comparisons and examples that can help you better understand how to couple a service level with volume size to meet your performance objectives.

TIP: Astra provisions persistent volumes using a minimum volume size of 100 GiB, and defaults to the Premium service level.
