---
sidebar: sidebar
permalink: get-started/gcp-create-service-account-gcloud.html
keywords:
summary: Learn how to create a new service account using the CLI gcloud tool.
---

= Create a New Service Account (gcloud)
:hardbreaks:
:icons: font
:imagesdir: ../media/gcp-credentials/

Learn how to create a new service account for your Google Cloud Platform account from the command line, using the `gcloud` tool.

For instructions on creating a new service account from the GCP console using a web browser, see link:gcp-create-service-account-browser.html[Create a New Service Account (Browser)].

**Requirements**

* An active GCP account.
* A GCP project. link:gcp-create-project.html[Create a New GCP Project].
* Google Cloud SDK (the `gcloud` tool) installed.

**External Resources**

To install the Google Cloud SDK so that you can use the `gcloud` tool, see the official Google Cloud user guides:

* https://cloud.google.com/sdk/install[Install Google Cloud SDK]
* https://cloud.google.com/sdk/docs/initializing[Set Up Google Cloud SDK]

To learn more about GCP service accounts, https://cloud.google.com/iam/docs/service-accounts[see the official Google Cloud documentation].

== Set Your Project

Verify that your default `gcloud` configuration points to the project where you want to create the new service account:

----
gcloud config list
----

This command returns all of your GCP configurations:

----
jdoe@jdoe-laptop:~$ gcloud config list
[compute]
region = us-central1
zone = us-central1-c
[core]
account = jdoe@example.com
disable_usage_reporting = False
project = astra-sandbox

Your active configuration is: [default]
----

In this example, `astra-sandbox` is set as the GCP project.

To change the project, https://cloud.google.com/sdk/gcloud/reference/config/set[follow the Google Cloud instructions for changing your default configuration].

== Create a Service Account

Create a name for your new service account.

* The name must be between 6 and 30 characters.
* It can contain upper- and lower-case alphanumeric characters and dashes, but no spaces or special characters.
* You can't change the service account name after you create it.
* The name is a unique identifier, which will appear in the service account's email address that Google creates, like sa-name@project-id.iam.gserviceaccount.com.

Set the new name as an environmental variable:

----
SA=[service account name]
----

For example, the command to set `example-service-account` is:

----
SA=example-service-account
----

Set the project ID as an environmental variable:

----
PROJECT_ID=`gcloud config list --format="text(core.project)" | awk '{print $NF}'`
----

Create the new service account:

----
gcloud iam service-accounts create ${SA}
----

== Add the Required Roles

If the policy role binding is set up with conditions, please select the correct condition from the list of conditions. If none of the conditions are required, select `None`.

**Compute Network Viewer**

----
gcloud projects add-iam-policy-binding ${PROJECT_ID} --member=serviceAccount:${SA}@${PROJECT_ID}.iam.gserviceaccount.com --role=roles/compute.networkViewer
----

**Kubernetes Engine Admin**

----
gcloud projects add-iam-policy-binding ${PROJECT_ID} --member=serviceAccount:${SA}@${PROJECT_ID}.iam.gserviceaccount.com --role=roles/container.admin
----

**Cloud Volumes Admin**

----
gcloud projects add-iam-policy-binding ${PROJECT_ID} --member=serviceAccount:${SA}@${PROJECT_ID}.iam.gserviceaccount.com --role=roles/netappcloudvolumes.admin
----

**Storage Admin**

----
gcloud projects add-iam-policy-binding ${PROJECT_ID} --member=serviceAccount:${SA}@${PROJECT_ID}.iam.gserviceaccount.com --role=roles/storage.admin
----

**Service Usage Viewer**

----
gcloud projects add-iam-policy-binding ${PROJECT_ID} --member=serviceAccount:${SA}@${PROJECT_ID}.iam.gserviceaccount.com --role=roles/serviceusage.serviceUsageViewer
----

== Verify Roles

Check to make sure that all roles were added correctly.

----
gcloud projects get-iam-policy ${PROJECT_ID} --flatten="bindings[].members" --format="table(bindings.role)" --filter=bindings.members:${SA}@${PROJECT_ID}.iam.gserviceaccount.com
----

The output should match:

----
ROLE
roles/compute.networkViewer
roles/container.admin
roles/netappcloudvolumes.admin
roles/serviceusage.serviceUsageViewer
roles/storage.admin
----

== Create a Key

Create the service account JSON file:

----
gcloud iam service-accounts keys create ${SA}_keys.json --iam-account=${SA}@${PROJECT_ID}.iam.gserviceaccount.com
----

This command creates a new file named `[service account name]_keys.json` in your current directory. In step one of the "Add Compute" wizard, you will be asked to upload this file to Astra.

== Next Steps

Now that you have created a service account and the JSON key file, you are ready to provision a new GKE cluster and add it to Astra. See our link:getting-started.html[Getting Started Guide] for instructions.
