---
sidebar: sidebar
permalink: solutions/jenkins-deploy-from-helm-chart.html
keywords: helm, jenkins, deploy apps, deploy jenkins, bitnami, helm chart
summary: Learn how to deploy Jenkins from the Bitnami Helm chart. After you deploy Jenkins on your cluster, you can register the application with Astra Control.
---

= Deploy Jenkins from a Helm chart
:hardbreaks:
:icons: font
:imagesdir: ../media/

Learn how to deploy Jenkins from the Bitnami Helm chart. After you deploy Jenkins on your cluster, you can register the application with Astra Control.

Jenkins is a validated app for Astra Control. link:../learn/validated-vs-standard.html[Learn the difference between Validated and Standard apps].

NOTE: Applications deployed from Google Marketplace have not been validated. Some users report issues with discovery and/or backup with Google Marketplace deployments of Postgres, MariaDB, and MySQL.

== Requirements

* A GKE cluster that has been added to Astra Control Service.
* Updated versions of Helm (version 3.2+) and Kubectl installed.
* Kubeconfig configured using the gcloud tool with a command like `gcloud container clusters get-credentials my-cluster-name`

Astra Control does not currently support the https://plugins.jenkins.io/kubernetes/[Kubernetes plugin for Jenkins]. You can run Jenkins in a Kubernetes cluster without the plugin. The plugin provides scalability to your Jenkins cluster.


== Install Jenkins

Two important notes on this process:

* You must deploy your app after the cluster is added to Astra Control, not before.
* You must deploy the Helm chart in a namespace other than the default.

Add the Bitnami chart repo:

----
helm repo add bitnami https://charts.bitnami.com/bitnami
----

Create the `jenkins` namespace and deploy Jenkins into it with the command:

----
kubectl create namespace jenkins && helm install jenkins --namespace jenkins --set persistence.storageClass=netapp-cvs-perf-premium,persistence.size=100Gi bitnami/jenkins
----

This does the following:

* Creates the `jenkins` namespace.
* Sets the correct storage class.
* Sets the persistent volume storage size to 100Gi.

After the pods are online, you can manage the app with Astra Control. Astra Control allows you to manage an app at the namespace level or using a helm label
