---
sidebar: sidebar
permalink: solutions/jenkins-deploy-from-helm-chart.html
keywords: helm, jenkins, deploy apps, deploy jenkins, bitnami, helm chart, astra, astra control, kubernetes
summary: Learn how to deploy Jenkins from the Bitnami Helm chart. After you deploy Jenkins on your cluster, you can register the application with Astra Control.
---

= Deploy Jenkins from a Helm chart
:hardbreaks:
:icons: font
:imagesdir: ../media/

Learn how to deploy Jenkins from the Bitnami Helm chart. After you deploy Jenkins on your cluster, you can register the application with Astra Control.

Jenkins is a validated app for Astra Control. link:../learn/validated-vs-standard.html[Learn the difference between Validated and Standard apps].

These instructions apply to both Astra Control Service and Astra Control Center.

== Requirements

* A cluster that has been added to Astra Control.
+
NOTE: For Astra Control Center, you can add the cluster to Astra Control Center first or add the app first.

* Updated versions of Helm (version 3.2+) and Kubectl installed on a local machine with the proper kubeconfig for the cluster

Astra Control does not currently support the https://plugins.jenkins.io/kubernetes/[Kubernetes plugin for Jenkins^]. You can run Jenkins in a Kubernetes cluster without the plugin. The plugin provides scalability to your Jenkins cluster.

== Install Jenkins

Two important notes on this process:

* You must deploy your app after the cluster is added to Astra Control Service, not before. Astra Control Center will accept applications before or after the cluster is added to Astra Control Center.
* You must deploy the Helm chart in a namespace other than the default.

.Steps

. Add the Bitnami chart repo:
+
----
helm repo add bitnami https://charts.bitnami.com/bitnami
----

. Create the `jenkins` namespace and deploy Jenkins into it with the command:
+
----
Helm install <name> --namespace <namespace> --create-namespace -–set persistence.storageClass=<storage_class>
----
+
NOTE: If the volume size is changed, use Kibibyte (Ki), Mebibyte (Mi) or Gibibyte (Gi) units.
+
You need to define the storage class only in these situations:

*	You are using Astra Control Service and you don’t want to use the default storage class.
*	You are using Astra Control Center and haven’t yet imported the cluster into Astra Control Center. Or, you have imported the cluster, but don't want to use the default storage class.

.Result

This does the following:

* Creates a namespace.
* Sets the correct storage class.

After the pods are online, you can manage the app with Astra Control. Astra Control enables you to manage an app at the namespace level or by using a helm label.
