---
sidebar: sidebar
permalink: solutions/mariadb-deploy-from-helm-chart.html
keywords: helm chart, mariadb
summary: Learn how to exercise the Project Astra Beta program workflow by deploying MariaDB from a Helm chart. After you deploy MariaDB on your cluster, you can manage the application with Project Astra.
---

= Deploy MariaDB From a Helm Chart
:hardbreaks:
:icons: font
:imagesdir: ../media/

Learn how to exercise the Project Astra Beta program workflow by deploying MariaDB from a Helm chart. After you deploy MariaDB on your cluster, you can manage the application with Project Astra.

MariaDB is a validated app for the Project Astra Beta program. link:../learn/validated-vs-standard.html[Learn the difference between Validated and Standard apps].

NOTE: The Project Astra Beta program only supports MySQL 0.3.22 and MariaDB 14.14.

== System Requirements

In order to deploy MariaDB from a Helm chart for the Project Astra Beta program, you need the following:

* A GKE cluster which has been added to Project Astra.
* Updated versions of Helm (version 3.2+) and Kubectl installed.
* Kubeconfig configured using the gcloud tool with a command like `gcloud container clusters get-credentials my-cluster-name`

== Install MariaDB

To exercise the Project Astra Beta program workflow, we recommend you use the Helm chart.

Deploy MariaDB with the command:

----
helm install mariadb bitnami/mariadb --namespace testdb --create-namespace --set db.database=test_db,db.user=test_db_user,db.password=NKhjs2wQPt8 > /dev/null 2>&1
----

This does the following:

* Creates the `testdb` namespace.
* Deploys MariaDB on the `testdb` namespace.
* Creates a database named `test_db`
* Creates a user `test_db_user` with password `NKhjs2wQPt8`

WARNING: This method of setting the password at deployment is insecure. Only use this command when setting up MariaDB for a sandbox deployment to use Project Astra Beta program. We do not recommend this for a production environment.

After the Helm chart is deployed, it will be automatically discovered by Project Astra, at which point you can manage the app with Project Astra.
