---
sidebar: sidebar
permalink: solutions/mariadb-deploy-from-helm-chart.html
keywords: helm chart, mariadb, deploy mariadb, helm chart, bitnami
summary: Learn how to exercise the Astra Beta program workflow by deploying MariaDB from a Helm chart. After you deploy MariaDB on your cluster, you can manage the application with Astra.
---

= Deploy MariaDB from a Helm chart
:hardbreaks:
:icons: font
:imagesdir: ../media/

Learn how to deploy MariaDB from the Bitnami Helm chart. After you deploy MariaDB on your cluster, you can manage the application with Astra.

MariaDB is a validated app for Astra. link:../learn/validated-vs-standard.html[Learn the difference between Validated and Standard apps].

NOTE: Applications deployed from Google Marketplace have not been validated. Some users report issues with discovery and/or backup with Google Marketplace deployments of Postgres, MariaDB, and MySQL.

== Requirements

* A GKE cluster which has been added to Astra.
* Updated versions of Helm (version 3.2+) and Kubectl installed.
* Kubeconfig configured using the gcloud tool with a command like `gcloud container clusters get-credentials my-cluster-name`

== Install MariaDB

Two important notes on this process:

* You must deploy your app after the cluster is added to Astra, not before.
* You must deploy the Helm chart in a namespace other than the default.

Add the Bitnami chart repo:

----
helm repo add bitnami https://charts.bitnami.com/bitnami
----

Deploy MariaDB with the command:

----
helm install mariadb bitnami/mariadb --namespace testdb --create-namespace --set db.database=test_db,db.user=test_db_user,db.password=NKhjs2wQPt8 > /dev/null 2>&1
----

This does the following:

* Creates the `testdb` namespace.
* Deploys MariaDB on the `testdb` namespace.
* Creates a database named `test_db`
* Creates a user `test_db_user` with password `NKhjs2wQPt8`

WARNING: This method of setting the password at deployment is insecure. We do not recommend this for a production environment.

After the pods are online, you can manage the app with Astra. Astra allows you to manage an app at the namespace level or using a helm label
