---
sidebar: sidebar
permalink: solutions/mysql-deploy-from-helm-chart.html
keywords: helm, mysql, helm chart, deploy mysql, astra, astra control, kubernetes
summary: Learn how to deploy MySQL from the standard stable chart. After you deploy MySQL on your Kubernetes cluster, you can manage the application with Astra Control.
---

= Deploy MySQL from a Helm chart
:hardbreaks:
:icons: font
:imagesdir: ../media/

Learn how to deploy MySQL from the https://github.com/helm/charts/tree/master/stable/mysql[standard stable chart^]. After you deploy MySQL on your Kubernetes cluster, you can manage the application with Astra Control.

MySQL is a validated app for Astra Control. link:../learn/validated-vs-standard.html[Learn the difference between Validated and Standard apps].

These instructions apply to both Astra Control Service and Astra Control Center.

== Requirements

* A cluster that has been added to Astra Control.
+
NOTE: For Astra Control Center, you can add the cluster to Astra Control Center first or add the app first.

* Updated versions of Helm (version 3.2+) and Kubectl installed on a local machine with the proper kubeconfig for the cluster

== Install MySQL

Two important notes on this process:

* You must deploy your app after the cluster is added to Astra Control Service, not before. Astra Control Center will accept applications before or after the cluster is added to Astra Control Center.
* We recommend that you deploy the Helm chart in a namespace other than the default.

Add the Bitnami chart repo:

----
helm repo add bitnami https://charts.bitnami.com/bitnami
----

Deploy MySQL with the command:

----
helm install mysql bitnami/mysql --namespace testdb --create-namespace --set db.database=test_db,db.user=test_db_user,db.password=NKhjs2wQPt8
----

This does the following:

* Creates the `testdb` namespace.
* Deploys MySQL on the `testdb` namespace.
* Creates a database named `test_db`
* Creates a user `test_db_user` with password `NKhjs2wQPt8`

WARNING: This method of setting the password at deployment is insecure. We do not recommend this for a production environment.

After the pods are online, you can manage the app with Astra Control. Astra Control allows you to manage an app with its name, at the namespace level, or by using a helm label.
