---
sidebar: sidebar
permalink: solutions/mysql-deploy-from-helm-chart.html
keywords: helm, mysql
summary: Learn how to exercise the Project Astra Beta workflow by deploying MySQL from a Helm chart. After you deploy MySQL on your Kubernetes cluster, you can manage the application with Project Astra.
---

= Deploy MySQL From a Helm Chart
:hardbreaks:
:icons: font
:imagesdir: ../media/

Learn how to exercise the Project Astra Beta workflow by deploying MySQL from a Helm chart. After you deploy MySQL on your Kubernetes cluster, you can manage the application with Project Astra.

NOTE: The Project Astra beta program only supports MySQL 0.3.22 and MariaDB 14.14.

== System Requirements

In order to deploy MySQL from a Helm chart for the Project Astra Beta program, you need the following:

* A GKE cluster which has been added to Project Astra.
* Updated versions of Helm (version 3.2+) and Kubectl installed.
* Kubeconfig configured using the gcloud tool with a command like `gcloud container clusters get-credentials my-cluster-name`

NOTE: You must deploy your app after the cluster is added to Project Astra, not before.

== Install MySQL

To exercise the Project Astra Beta workflow, we recommend the https://github.com/helm/charts/tree/master/stable/mysql[standard stable chart^].

NOTE: You must deploy the Helm chart in a namespace other than the default.

Deploy MySQL with the command:

----
helm install mysql stable/mysql --namespace testdb--set db.database=test_db,db.user=test_db_user,db.password=NKhjs2wQPt8
if you need to deploy mysql under a new namespace; please use the following command
helm install mysql stable/mysql --namespace testdb --create-namespace --set db.database=test_db,db.user=test_db_user,db.password=NKhjs2wQPt8
----

This does the following:

* Creates the `testdb` namespace.
* Deploys MySQL on the `testdb` namespace.
* Creates a database named `test_db`
* Creates a user `test_db_user` with password `NKhjs2wQPt8`

WARNING: This method of setting the password at deployment is insecure. You can use own secrets and config maps and passing along with helm command.

After the Helm chart is deployed, it will be automatically discovered by Project Astra, at which point you can manage the app with Project Astra.
