---
sidebar: sidebar
permalink: solutions/mysql-deploy-from-helm-chart.html
keywords: helm, mysql, helm chart, deploy mysql
summary: Learn how to deploy MySQL from the standard stable chart. After you deploy MySQL on your Kubernetes cluster, you can manage the application with Astra.
---

= Deploy MySQL from a Helm chart
:hardbreaks:
:icons: font
:imagesdir: ../media/

Learn how to deploy MySQL from the https://github.com/helm/charts/tree/master/stable/mysql[standard stable chart^]. After you deploy MySQL on your Kubernetes cluster, you can manage the application with Astra.

MySQL is a validated app for Astra. link:../learn/validated-vs-standard.html[Learn the difference between Validated and Standard apps].

NOTE: Applications deployed from Google Marketplace have not been validated. Some users report issues with discovery and/or backup with Google Marketplace deployments of Postgres, MariaDB, and MySQL.

== Requirements

* A GKE cluster which has been added to Astra.
* Updated versions of Helm (version 3.2+) and Kubectl installed.
* Kubeconfig configured using the gcloud tool with a command like `gcloud container clusters get-credentials my-cluster-name`

== Install MySQL

Two important notes on this process:

* You must deploy your app after the cluster is added to Astra, not before.
* We recommend that you deploy the Helm chart in a namespace other than the default.

Add the Bitnami chart repo:

----
helm repo add bitnami https://charts.bitnami.com/bitnami
----

Deploy MySQL with the command:

----
helm install mysql bitnami/mysql --namespace testdb --create-namespace --set db.database=test_db,db.user=test_db_user,db.password=NKhjs2wQPt8
----

This does the following:

* Creates the `testdb` namespace.
* Deploys MySQL on the `testdb` namespace.
* Creates a database named `test_db`
* Creates a user `test_db_user` with password `NKhjs2wQPt8`

WARNING: This method of setting the password at deployment is insecure. We do not recommend this for a production environment.

After the pods are online, you can manage the app with Astra. Astra allows you to manage an app with its name, at the namespace level, or by using a helm label.
