---
sidebar: sidebar
permalink: solutions/postgres-deploy-from-helm-chart.html
keywords: deploy apps, deploy postgres, helm chart, astra, astra control, kubernetes
summary: Learn how to deploy Postgres from a Helm chart. After you deploy Postgres on your cluster, you can register the application with Astra Control.
---

= Deploy Postgres from a Helm chart
:hardbreaks:
:icons: font
:imagesdir: ../media/

Learn how to deploy Postgres from the Bitnami Helm chart. After you deploy Postgres on your cluster, you can register the application with Astra Control.

Postgres is a validated app for Astra. link:../learn/validated-vs-standard.html[Learn the difference between Validated and Standard apps].

These instructions apply to both Astra Control Service and Astra Control Center.

== Requirements

* A cluster that has been added to Astra Control.
+
NOTE: For Astra Control Center, you can add the cluster to Astra Control Center first or add the app first.

* Updated versions of Helm (version 3.2+) and Kubectl installed on a local machine with the proper kubeconfig for the cluster

== Install Postgres

Two important notes on this process:

* You must deploy your app after the cluster is added to Astra Control Service, not before. Astra Control Center will accept applications before or after the cluster is added to Astra Control Center.
* You must deploy the Helm chart in a namespace other than the default.

Add the Bitnami chart repo:

----
helm repo add bitnami https://charts.bitnami.com/bitnami
----

Deploy Postgres with the command:

----
kubectl create namespace testdb && helm install bitnami/postgresql --namespace testdb --set postgresqlPassword=U9dH9HT4pWS,postgresqlDatabase=test_db --generate-name
----

This does the following:

* Creates the `testdb` namespace.
* Deploys Postgres on the `testdb` namespace.
* Creates a database named `test_db`
* Creates a user `test_db_user` with password `U9dH9HT4pWS`

WARNING: This method of setting the password at deployment is insecure. We do not recommend this for a production environment.

After the pods are online, you can manage the app with Astra Control. Astra Control enables you to manage an app at the namespace level or by using a helm label.
