---
sidebar: sidebar
permalink: use/manage-buckets.html
keywords: bucket, buckets, add buckets, change default bucket, default, default bucket, remove bucket, delete bucket, S3, s3, storage, object storage, object store, store, object
summary: Manage the buckets that Astra uses for backups and clones by adding additional buckets and by changing the default bucket for the clusters in your cloud provider.
---

= Manage buckets
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
Manage the buckets that Astra uses for backups and clones by adding additional buckets and by changing the default bucket for the Kubernetes clusters in your cloud instance.

Only Admins can add and modify buckets.

== How Astra Control uses buckets

When you start managing your first Kubernetes cluster, Astra Control Service creates the default bucket for your cloud provider in the same geography as the managed cluster.

Astra Control Service uses this default bucket for the backups and clones that you create. You can then use the backups to restore and clone apps between clusters.

If you add additional buckets to Astra Control Service, you can select from those buckets when you create a protection policy. You can also change the default bucket that Astra Control Service uses for ad-hoc backups and clones. You can not clone a bucket from one cloud provider to another cloud provider. To migrate data from one cloud provider to another, clone the associated application instead.

TIP: Astra Control Service checks whether a destination bucket is accessible prior to starting a backup or a clone.

== View existing buckets

View the list of buckets that are available to Astra Control Service to determine their status and to identify the default bucket for your cloud provider.

A bucket can have any of the following states:

Pending:: After you add a bucket, it starts in the pending state while Astra Control looks at it for the first time.

Available:: The bucket is available for use by Astra Control.

Removed:: The bucket isn't operational at the moment. Hover your mouse over the status icon to identify what the problem is.
+
If a bucket is in the Removed state, you can still set it as the default bucket and assign it to a protection schedule. But if the bucket isn't in the Available state by the time a data protection operation starts, then that operation will fail.

.Step

. Go to *Buckets*.
+
The list of buckets available to Astra Control Service displays.

== Add an additional bucket

After you start managing a cluster in your cloud provider, you can add additional buckets at any time. This enables you to choose between buckets when creating a protection policy and to change the default bucket for ad-hoc backups and clones.

.What you'll need

* The name of an existing bucket in your cloud provider.
ifdef::azure[]
* If your bucket is in Azure: 
** The bucket must belong to the resource group named _astra-backup-rg_.
** If the Azure storage account instance performance setting is set to "Premium", the "Premium account type" setting must be set to "Block blobs".
endif::azure[]

.Steps

. Go to *Buckets*.

. Select *Add* and follow the prompts to add the bucket.
+
* *Type*: Choose your cloud provider.
+
Your cloud provider is available only after Astra Control Service has started managing a cluster that's running in that cloud provider.

* *Existing bucket name*: Enter the name of the bucket.

* *Description*: Optionally enter a description of the bucket.
ifdef::azure[]
* *Storage account* (Azure only): Enter the name of your Azure storage account. This bucket must belong to the resource group named _astra-backup-rg_.
endif::azure[]
ifdef::aws[]
* *S3 server name or IP address* (AWS only): Enter the fully qualified domain name of the S3 endpoint that corresponds with your region, without `https://`. Refer to https://docs.aws.amazon.com/general/latest/gr/s3.html[the Amazon documentation^] for more information.
endif::aws[]

* *Select credentials*: Choose the credentials that provide Astra Control Service with the permissions that it needs to manage the bucket.

. Select *Add* to add the bucket.

.Result

Astra Control Service adds the additional bucket. You can now choose the bucket when creating a protection policy.

== Change the default bucket

Change the default bucket that Astra Control Service should use for backups and clones. Each cloud instance has its own default bucket.

Astra Control Service uses the default bucket for a cloud instance for ad-hoc backups and for ad-hoc clones when you don't choose to clone from an existing backup.

NOTE: Astra Control does not automatically assign a default bucket for any cloud instance. You need to manually set a default bucket for a cloud instance before performing app clone operations between two clusters.

.Steps

. Go to *Cloud instances*.

. Select the configuration menu in the *Actions* column for the cloud instance that you want to edit.

. Select *Edit*.

. In the list of buckets, select the bucket you want to make the default bucket for this cloud instance.

. Select *Update*.

== Remove a bucket

You can remove a bucket that is no longer in use or is not healthy. You might want to do this to keep your object store configuration simple and up-to-date.

You cannot remove a default bucket. If you want to remove that bucket, first select another bucket as the default.

.What you'll need

* You should check to ensure that there are no running or completed backups for this bucket before you begin.
* You should check to ensure that the bucket is not being used for any scheduled backups.

If there are, you will not be able to continue.


.Steps
. Go to *Buckets*.
. From the *Actions* menu, select *Remove*.

+
NOTE: Astra Control ensures first that there are no schedule policies using the bucket for backups and that there are no active backups in the bucket you are about to remove.

. Type "remove" to confirm the action.
. Select *Yes, remove bucket*.

== Find more information

* https://docs.netapp.com/us-en/astra-automation/index.html[Use the Astra Control API^]
