---
sidebar: sidebar
permalink: use/manage-buckets.html
keywords: bucket, buckets, add buckets, change default bucket, default, default bucket, remove bucket, delete bucket, S3, s3, storage, object storage, object store, store, object
summary: Manage the buckets that Astra uses for backups and clones by adding additional buckets and by changing the default bucket for the clusters in your cloud provider.
---

= Manage buckets
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
You can manage the buckets that Astra uses for backups and clones. You can add additional buckets, remove existing buckets, and change the default bucket for the Kubernetes clusters in a cloud instance.

Only Owners and Admins can manage buckets.

== How Astra Control uses buckets

When you start managing your first Kubernetes cluster for a cloud instance, Astra Control Service creates the initial bucket for that link:manage-cloud-instances.html[cloud instance^]. 

You can manually designate a bucket as the default bucket for a cloud instance. If you do so, Astra Control Service uses this bucket by default for the backups and clones that you create on any managed cluster in that cloud instance (you can select a different bucket for backups). If you perform a live clone of an application from any of the managed clusters in a cloud instance to another cluster, Astra Control Service uses the default bucket for the source cloud instance to perform the clone operation.

You can set the same bucket as the default bucket for multiple cloud instances.

//You can then use the backups to restore and clone apps between clusters.
// To migrate data from one cloud provider to another, clone the associated application.

You can select from any buckets when you create a protection policy or start an ad-hoc backup. 

TIP: Astra Control Service checks whether a destination bucket is accessible prior to starting a backup or a clone.

== View existing buckets

View the list of buckets that are available to Astra Control Service to determine their status and to identify the default bucket (if defined) for your cloud instance.

A bucket can have any of the following states:

Pending:: After you add a bucket, it starts in the pending state while Astra Control discovers it.

Available:: The bucket is available for use by Astra Control.

Removed:: The bucket isn't operational at the moment. Hover your mouse over the status icon to identify what the problem is.
+
If a bucket is in the Removed state, you can still set it as the default bucket and assign it to a protection schedule. But if the bucket isn't in the Available state by the time a data protection operation starts, then that operation will fail.

.Step

. Go to *Buckets*.
+
The list of buckets available to Astra Control Service is displayed.

== Add an additional bucket

You can add additional buckets at any time. This enables you to choose between buckets when creating a protection policy or starting an ad-hoc backup, and enables you to change the default bucket that a cloud instance uses.

You can add the following types of buckets:

* Amazon Web Services
* Generic S3
* Google Cloud Platform
* Microsoft Azure
* NetApp ONTAP S3
* NetApp StorageGRID S3

.Before you begin

* Ensure you know the name of an existing bucket.
* Ensure you have credentials for the bucket that provide Astra Control with the permissions that it needs to manage the bucket.
ifdef::azure[]
* If your bucket is in Microsoft Azure: 
** The bucket must belong to the resource group named _astra-backup-rg_.
** If the Azure storage account instance performance setting is set to "Premium", the "Premium account type" setting must be set to "Block blobs".
endif::azure[]

.Steps

. Go to *Buckets*.

. Select *Add* and follow the prompts to add the bucket.
+
* *Type*: Choose your cloud provider.
// +
// Your cloud provider is available only after Astra Control Service has started managing a cluster that's running in that cloud provider.

* *Existing bucket name*: Enter the name of the bucket.

* *Description*: Optionally enter a description of the bucket.
ifdef::azure[]
* *Storage account* (Azure only): Enter the name of your Azure storage account. This bucket must belong to the resource group named _astra-backup-rg_.
endif::azure[]
ifdef::aws[]
* *S3 server name or IP address* (AWS and S3 bucket types only): Enter the fully qualified domain name of the S3 endpoint that corresponds with your region, without `https://`. Refer to https://docs.aws.amazon.com/general/latest/gr/s3.html[the Amazon documentation^] for more information.
endif::aws[]

* *Select credentials*: Enter the credentials that provide Astra Control Service with the permissions that it needs to manage the bucket. The information you need to provide varies depending on the bucket type.

. Select *Add* to add the bucket.

.Result

Astra Control Service adds the bucket. You can now choose this bucket when creating a protection policy or performing an ad-hoc backup. You can also set this bucket as the default bucket for a cloud instance.

== Change the default bucket

You can change the default bucket for a cloud instance. Astra Control Service will use this bucket by default for backups and clones. Each cloud instance has its own default bucket.

NOTE: Astra Control does not automatically assign a default bucket for any cloud instance. You need to manually set a default bucket for a cloud instance before performing app clone operations between two clusters.

.Steps

. Go to *Cloud instances*.

. Select the configuration menu in the *Actions* column for the cloud instance that you want to edit.

. Select *Edit*.

. In the list of buckets, select the bucket you want to make the default bucket for this cloud instance.

. Select *Update*.

== Remove a bucket

You can remove a bucket that is no longer in use or is not healthy. You might want to do this to keep your object store configuration simple and up-to-date.

[NOTE]
===============================
* You cannot remove a default bucket. If you want to remove that bucket, first select another bucket as the default.
* You cannot remove a write once read many (WORM) bucket before the bucket's cloud provider retention period has expired. WORM buckets are denoted with "Locked" next to the bucket name.
===============================

.Before you begin

* You should check to ensure that there are no running or completed backups for this bucket before you begin.
* You should check to ensure that the bucket is not being used for any scheduled backups.

If there are, you will not be able to continue.


.Steps
. Go to *Buckets*.
. From the *Actions* menu, select *Remove*.

+
NOTE: Astra Control ensures first that there are no schedule policies using the bucket for backups and that there are no active backups in the bucket you are about to remove.

. Type "remove" to confirm the action.
. Select *Yes, remove bucket*.

== [Tech preview] Manage a bucket using a custom resource

You can add a bucket using the an Astra Control custom resource (CR) on the application cluster. Adding object store bucket providers is essential if you want to back up your applications and persistent storage or if you want to clone applications across clusters. Astra Control stores those backups or clones in the object store buckets that you define. If you are using the custom resource method, application snapshots functionality requires a bucket.

You don't need a bucket in Astra Control if you are cloning your application configuration and persistent storage to the same cluster. 

The bucket custom resource for Astra Control is known as an AppVault. This CR contains the configurations necessary for a bucket to be used in protection operations.

.Before you begin

* Ensure you have a bucket that is reachable from your clusters managed by Astra Control Center.
* Ensure you have credentials for the bucket.
* Ensure the bucket is one of the following types:

** NetApp ONTAP S3
** NetApp StorageGRID S3
** Microsoft Azure
** Generic S3

NOTE: Amazon Web Services (AWS) and Google Cloud Platform (GCP) use the Generic S3 bucket type.

NOTE: Although Astra Control Center supports Amazon S3 as a Generic S3 bucket provider, Astra Control Center might not support all object store vendors that claim Amazon's S3 support.

.Steps

. Create the custom resource (CR) file and name it (for example, `astra-appvault.yaml`).

. Configure the following attributes:
+
* *metadata.name*: _(Required)_ The name of the AppVault custom resource.
* *spec.prefix*: _(Optional)_ A path that is prefixed to the names of all entities stored in the AppVault.
* *spec.providerConfig*: _(Required)_ Stores the configuration necessary to access the AppVault using the specified provider.
* *spec.providerCredentials*: Stores references to any credential required to access the AppVault using the specified provider.
** *spec.providerCredentials.valueFromSecret*: _(Optional)_ Indicates that the credential value should come from a secret.
*** *key*: _(Required if valueFromSecret is used)_ The valid key of the secret to select from.
*** *name*: _(Required if valueFromSecret is used)_ Name of the secret containing the value for this field. Must be in the same namespace.
* *spec.providerType*: _(Required)_ Determines what provides the backup; for example, NetApp ONTAP S3 or Microsoft Azure.
+
Example YAML:
+
[source,yaml]
----
apiVersion: astra.netapp.io/v1
kind: AppVault
metadata:
  name: astra-appvault
spec:
  providerType: generic-s3
  providerConfig:
    path: testpath
    endpoint: 192.168.1.100:80
    bucketName: bucket1
    secure: "false"
  providerCredentials:
    accessKeyID:
      valueFromSecret:
        name: s3-creds
        key: accessKeyID
    secretAccessKey:
      valueFromSecret:
        name: s3-creds
        key: secretAccessKey
----

. After you populate the `astra-appvault.yaml` file with the correct values, apply the CR:
+
[source,console]
----
kubectl apply -f astra-appvault.yaml -n astra-connector
----
+
NOTE: When you add a bucket, Astra Control marks one bucket with the default bucket indicator. The first bucket that you create becomes the default bucket. As you add buckets, you can later decide to link:../use/manage-buckets.html#set-the-default-bucket[set another default bucket^].

== Find more information

* https://docs.netapp.com/us-en/astra-automation/index.html[Use the Astra Control API^]
