---
sidebar: sidebar
permalink: use/manage-buckets.html
keywords: bucket, buckets, add buckets, change default bucket, default, default bucket, remove bucket, delete bucket, S3, s3, storage, object storage, object store, store, object
summary: Manage the buckets that Astra uses for backups and clones by adding additional buckets and by changing the default bucket for the clusters in your cloud provider.
---

= Manage buckets
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
You can manage the buckets that Astra uses for backups and clones. You can add additional buckets, remove existing buckets, and change the default bucket for the Kubernetes clusters in a cloud instance.

Only Owners and Admins can add and modify buckets.

== How Astra Control uses buckets

When you start managing your first Kubernetes cluster for a cloud instance, Astra Control Service creates the initial bucket for that link:manage-cloud-instances.html[cloud instance^]. 

You can manually designate a bucket as the default bucket for a cloud instance. If you do so, Astra Control Service uses this bucket by default for the backups and clones that you create on any managed cluster in that cloud instance (you can select a different bucket if you need to). If you perform a live clone of an application from any of the managed clusters in a cloud instance to another cluster, Astra Control Service uses the default bucket for the source cloud instance to perform the clone operation.

//You can then use the backups to restore and clone apps between clusters.
// To migrate data from one cloud provider to another, clone the associated application.

You can select from any buckets when you create a protection policy or start an ad-hoc backup. 

TIP: Astra Control Service checks whether a destination bucket is accessible prior to starting a backup or a clone.

== View existing buckets

View the list of buckets that are available to Astra Control Service to determine their status and to identify the default bucket (if defined) for your cloud instance.

A bucket can have any of the following states:

Pending:: After you add a bucket, it starts in the pending state while Astra Control discovers it.

Available:: The bucket is available for use by Astra Control.

Removed:: The bucket isn't operational at the moment. Hover your mouse over the status icon to identify what the problem is.
+
If a bucket is in the Removed state, you can still set it as the default bucket and assign it to a protection schedule. But if the bucket isn't in the Available state by the time a data protection operation starts, then that operation will fail.

.Step

. Go to *Buckets*.
+
The list of buckets available to Astra Control Service is displayed.

== Add an additional bucket

You can add additional buckets at any time. This enables you to choose between buckets when creating a protection policy or starting an ad-hoc backup, and enables you to change the default bucket that a cloud instance uses.

You can add the following types of buckets:

* Amazon Web Services
* Generic S3
* Google Cloud Platform
* Microsoft Azure
* NetApp ONTAP S3
* NetApp StorageGRID S3

.What you'll need

* The name of an existing bucket.
* The credentials for the bucket that provide Astra Control Service with the permissions that it needs to manage the bucket.
ifdef::azure[]
* If your bucket is in Microsoft Azure: 
** The bucket must belong to the resource group named _astra-backup-rg_.
** If the Azure storage account instance performance setting is set to "Premium", the "Premium account type" setting must be set to "Block blobs".
endif::azure[]

.Steps

. Go to *Buckets*.

. Select *Add* and follow the prompts to add the bucket.
+
* *Type*: Choose your cloud provider.
// +
// Your cloud provider is available only after Astra Control Service has started managing a cluster that's running in that cloud provider.

* *Existing bucket name*: Enter the name of the bucket.

* *Description*: Optionally enter a description of the bucket.
ifdef::azure[]
* *Storage account* (Azure only): Enter the name of your Azure storage account. This bucket must belong to the resource group named _astra-backup-rg_.
endif::azure[]
ifdef::aws[]
* *S3 server name or IP address* (AWS and S3 bucket types only): Enter the fully qualified domain name of the S3 endpoint that corresponds with your region, without `https://`. Refer to https://docs.aws.amazon.com/general/latest/gr/s3.html[the Amazon documentation^] for more information.
endif::aws[]

* *Select credentials*: Enter the credentials that provide Astra Control Service with the permissions that it needs to manage the bucket. The information you need to provide varies depending on the bucket type.

. Select *Add* to add the bucket.

.Result

Astra Control Service adds the bucket. You can now choose this bucket when creating a protection policy or performing an ad-hoc backup. You can also set this bucket as the default bucket for a cloud instance.

== Change the default bucket

Change the default bucket that Astra Control Service should use for backups and clones. Each cloud instance has its own default bucket.

Astra Control Service uses the default bucket for a cloud instance for ad-hoc backups and for ad-hoc clones when you don't choose to clone from an existing backup.

NOTE: Astra Control does not automatically assign a default bucket for any cloud instance. You need to manually set a default bucket for a cloud instance before performing app clone operations between two clusters.

.Steps

. Go to *Cloud instances*.

. Select the configuration menu in the *Actions* column for the cloud instance that you want to edit.

. Select *Edit*.

. In the list of buckets, select the bucket you want to make the default bucket for this cloud instance.

. Select *Update*.

== Remove a bucket

You can remove a bucket that is no longer in use or is not healthy. You might want to do this to keep your object store configuration simple and up-to-date.

You cannot remove a default bucket. If you want to remove that bucket, first select another bucket as the default.

.What you'll need

* You should check to ensure that there are no running or completed backups for this bucket before you begin.
* You should check to ensure that the bucket is not being used for any scheduled backups.

If there are, you will not be able to continue.


.Steps
. Go to *Buckets*.
. From the *Actions* menu, select *Remove*.

+
NOTE: Astra Control ensures first that there are no schedule policies using the bucket for backups and that there are no active backups in the bucket you are about to remove.

. Type "remove" to confirm the action.
. Select *Yes, remove bucket*.

== Find more information

* https://docs.netapp.com/us-en/astra-automation/index.html[Use the Astra Control API^]
