---
sidebar: sidebar
permalink: use/monitor-running-tasks.html
keywords: activity, log, activities, running, tasks, monitor, status, state
summary: You can view details about running tasks in Astra Control. For example, when you perform a snapshot, backup, or clone. 
---

= Monitor running tasks
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
You can view details about running tasks in Astra Control. For example, you can view the status of a running snapshot, backup, or clone operation. You can view the status of a running scheduled operation or an operation that you started manually. 

While viewing a running or completed task, you can expand the task details to see the status of each of the subtasks. The task progress bar is green for ongoing or completed tasks, blue for cancelled tasks, and red for tasks that failed because of an error.

NOTE: For clone operations, the task subtasks consist of a snapshot and a snapshot restore operation.

To see more information about failed tasks, see link:monitor-account-activity.html[Monitor account activity].

.Steps

. While a task is running, go to *Applications*.
. Select the *Tasks* tab.

NOTE: Tasks are retained in the *Tasks* list for up to 24 hours.
