---
sidebar: sidebar
permalink: use/unmanage.html
keywords: unmanage app, remove app, stop managing app, stop managing clusters, unmanage cluster, remove cluster
summary: Remove any apps or clusters that you no longer want to manage from Astra Control.
---

= Unmanage apps and clusters
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

Remove any apps or clusters that you no longer want to manage from Astra Control.

== Stop managing an app

Stop managing apps that you no longer want to back up, snapshot, or clone from Astra Control.

* Any existing backups and snapshots will be deleted.

* Applications and data remain available.

.Steps

. Click *Applications*.

. Click the checkbox for the apps that you no longer want to manage.

. Click the *Action* drop-down and select *Unmanage application/s*.

. Confirm that you want to unmanage the apps and then click *Yes, Unmanage Applications*.

.Result

Astra Control stops managing the app.

== Stop managing a cluster

Stop managing the cluster that you no longer want to manage from Astra Control. As a best practice, we recommend that you remove the cluster from Astra Control before you delete it through GCP.

* This action stops your cluster from being managed by Astra Control. It doesn't make any changes to the cluster's configuration and it doesn't delete the cluster.

* Astra Trident won't be uninstalled from the cluster. https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html[Learn how to uninstall Astra Trident^].

.Steps

. Click *Clusters*.

. Click the checkbox for the cluster that you no longer want to manage.

. Click the *Actions* drop-down and select *Unmanage*.

. Confirm that you want to unmanage the cluster and then click *Yes, Unmanage cluster*.

.Result

Astra Control stops managing the cluster.

== Deleting clusters from your cloud provider

Before you delete a Kubernetes cluster that has persistent volumes (PV) residing on NetApp storage classes, you need to first delete the persistent volume claims (PVC) following one of the methods below. Deleting the PVC and PV before deleting the cluster ensures that you don’t receive unexpected bills from your cloud provider.

* *Method #1*: Delete the application workload namespaces from the cluster. Do _not_ delete the Trident namespace.
* *Method #2*: Delete the PVCs and the pods, or the deployment where the PVs are mounted.

When you manage a Kubernetes cluster from Astra Control, applications on that cluster use Cloud Volumes Service or Azure NetApp Files as the backend storage for persistent volumes. If you delete the cluster from your cloud provider without first removing the PVs, the backend volumes are _not_ deleted along with the cluster.

Using one of the above methods will delete the corresponding PVs from your cluster. Make sure that there are no PVs residing on NetApp storage classes on the cluster before you delete it.

If you didn’t delete the persistent volumes before you deleted the cluster, then you’ll need to manually delete the backend volumes from Cloud Volumes Service for Google Cloud or from Azure NetApp Files.
