---
sidebar: sidebar
permalink: use/unmanage.html
keywords: unmanage app, remove app, stop managing app, stop managing clusters, unmanage cluster, remove cluster
summary: Remove any apps or clusters that you no longer want to manage from Astra Control.
---

= Unmanage apps and clusters
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
Remove any apps or clusters that you no longer want to manage from Astra Control.

== Stop managing an app

Stop managing apps that you no longer want to back up, snapshot, or clone from Astra Control.

When you unmanage an app:

* Any existing backups and snapshots will be deleted.

* Applications and data remain available.

.Steps

. From the left navigation bar, select *Applications*.

. Select the app.

. From the Options menu in the Actions column, select *Unmanage*. 

. Review the information.

. Type "unmanage" to confirm.

. Select *Yes, Unmanage Application*.

.Result

Astra Control stops managing the app.

== Stop managing a cluster

Stop managing the cluster that you no longer want to manage from Astra Control.
ifdef::gcp[]

NOTE: Before you unmanage the cluster, you should unmanage the apps associated with the cluster.

As a best practice, we recommend that you remove the cluster from Astra Control before you delete it through GCP.
endif::gcp[]

When you unmanage a cluster:

* This action stops your cluster from being managed by Astra Control. It doesn't make any changes to the cluster's configuration and it doesn't delete the cluster.

* Astra Control Provisioner won't be uninstalled from the cluster. https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html[Learn how to uninstall Astra Trident^].

.Steps

. Select *Clusters*.

. Select the checkbox for the cluster that you no longer want to manage.

. From the options menu in the *Actions* column, select *Unmanage*.

. Confirm that you want to unmanage the cluster and then select *Yes, unmanage*.

.Result

The status of the cluster changes to *Removing*. After that, the cluster will be removed from the *Clusters* page and it is no longer managed by Astra Control.

== Deleting clusters from your cloud provider

Before you delete a Kubernetes cluster that has persistent volumes (PV) residing on NetApp storage classes, you need to first delete the persistent volume claims (PVC) following one of the methods below. Deleting the PVC and PV before deleting the cluster ensures that you don't receive unexpected bills from your cloud provider.

* *Method #1*: Delete the application workload namespaces from the cluster. Do _not_ delete the Trident namespace.
* *Method #2*: Delete the PVCs and the pods, or the deployment where the PVs are mounted.

When you manage a Kubernetes cluster from Astra Control, applications on that cluster use your cloud provider as the storage backend for persistent volumes. If you delete the cluster from your cloud provider without first removing the PVs, the backend volumes are _not_ deleted along with the cluster.

Using one of the above methods will delete the corresponding PVs from your cluster. Make sure that there are no PVs residing on NetApp storage classes on the cluster before you delete it.

If you didn't delete the persistent volumes before you deleted the cluster, then you'll need to manually delete the backend volumes from your cloud provider.
