---
sidebar: sidebar
permalink: use/unmanage.html
keywords: unmanage app, remove app, stop managing app, stop managing clusters, unmanage cluster, remove cluster
summary: Remove any apps or clusters that you no longer want to manage from Astra.
---

= Unmanage apps and clusters
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

Remove any apps or clusters that you no longer want to manage from Astra.

== Stop managing an app

Stop managing apps that you no longer want to back up, snapshot, or clone from Astra.

* Any existing backups and snapshots will be deleted.

* Applications and data remain available.

.Steps

. Click *Apps*.

. Click the checkbox for the apps that you no longer want to manage.

. Click the *Action* drop-down and select *Unmanage application/s*.

. Confirm that you want to unmanage the apps and then click *Yes, Unmanage Applications*.

.Result

Astra stops managing the app.

== Stop managing compute

Stop managing the compute that you no longer want to manage from Astra. As a best practice, we recommend that you remove compute from Astra before you delete it through GCP.

* This action stops your compute from being managed by Astra. It doesn't make any changes to the cluster's configuration and it doesn't delete the cluster.

* Trident won't be uninstalled from the cluster. https://netapp-trident.readthedocs.io/en/stable-v20.04/kubernetes/operations/tasks/managing.html#uninstalling-trident[Learn how to uninstall Trident^].

.Steps

. Click *Compute*.

. Click the checkbox for the compute that you no longer want to manage.

. Click the *Actions* drop-down and select *Unmanage compute/s*.

. Confirm that you want to unmanage the compute and then click *Yes, Unmanage Compute*.

.Result

Astra stops managing the compute.
