---
sidebar: sidebar
permalink: use/unmanage.html
keywords: unmanage app, remove app, stop managing app, stop managing clusters, unmanage cluster, remove cluster
summary: Remove any apps or clusters that you no longer want to manage from Astra.
---

= Unmanage apps and clusters
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

Remove any apps or clusters that you no longer want to manage from the Astra beta program.

== Stop managing an app

Stop managing apps that you no longer want to back up, snapshot, or clone from Astra.

* Any existing backups and snapshots will be deleted.

* Applications and data remain available.

.Steps

. Click *Apps*.

. Click the checkbox for the apps that you no longer want to manage.

. Click the *Action* drop-down and select *Unmanage application/s*.

. Confirm that you want to unmanage the apps and then click *Yes, Unmanage Applications*.

.Result

Astra stops managing the app.

== Stop managing clusters

Stop managing the clusters that you no longer want to manage from Astra. As a best practice, we recommend that you remove a cluster from Astra before you delete it through GCP.

* This action stops your cluster from being managed by Astra. It doesn't make any changes to the cluster's configuration and it doesn't delete the cluster.
+
Trident won't be uninstalled from the cluster. https://netapp-trident.readthedocs.io/en/stable-v20.04/kubernetes/operations/tasks/managing.html#uninstalling-trident[Learn how to uninstall Trident^].

* Apps associated with this cluster will no longer be managed and will go into a Detached state.

.Steps

. Click *Compute*.

. Click the checkbox for the clusters that you no longer want to manage.

. Click the *Actions* drop-down and select *Unmanage compute/s*.

. Confirm that you want to unmanage the clusters and then click *Yes, Unmanage Compute*.

.Result

Astra stops managing the clusters.

== Cleaning up after the Beta

A few things remain after you've removed apps and clusters from Astra:

* The object store that was created in your Google Cloud account
* The Admin role that was installed on each managed Kubernetes cluster
* The service account that you created

You'll need to manually remove these.
