---
sidebar: sidebar
permalink: get-started/astra-connector-overview.html
keywords: connector, install, astra connector, manage cluster, add cluster, cluster, add, manage
summary: You need to install the Astra Connector on private clusters managed by the legacy Astra Control architecture and all clusters that are managed by the new Astra Control architecture.
---

= Install Astra Connector to manage clusters
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
Astra Connector is software that resides on your managed clusters and facilitates communication between the managed cluster and Astra Control. For clusters managed using Astra Control Service, there are two avalable versions of Astra Connector:

* *Legacy Astra Connector*: link:install-astra-connector-legacy.html[Install the legacy Astra Connector] on your managed cluster if you plan to manage the cluster using the legacy architecture of Astra Control.
* [Tech preview] *Current Astra Connector*: link:install-astra-connector-declarative.html[Install the current Astra Connector] on your managed cluster if you plan to manage the cluster using the new architecture of Astra Control. After you install the current Astra Connector on your cluster, the cluster is automatically added to Astra Control.

NOTE: The current Astra Connector is available only as part of the Astra Control Early Adopter Program (EAP). Contact your NetApp sales representative for information about joining the EAP.