---
sidebar: sidebar
permalink: get-started/check-astra-trident-version.html
keywords: astra trident, check, version, astra control provisioner
summary: For self-managed clusters, you might need to make sure you are using the correct Astra Trident version.
---

= Check the Astra Trident version
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
To add a self-managed cluster that uses Astra Control Provisioner or Astra Trident for storage services, ensure that the installed version of Astra Trident is 23.10 or latest. 
//acp to trident revert

.Steps

. Determine the Astra Trident version you are running:
+
[source,console]
----
kubectl get tridentversions -n trident
----
+
If Astra Trident is installed, you see output similar to the following:
+
----
NAME      VERSION
trident   24.02.0
----
+
If Astra Trident is not installed, you see output similar to the following:
+
----
error: the server doesn't have a resource type "tridentversions"
----

. Do one of the following:

* If you are running Astra Trident 23.01 or earlier, use these https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-trident.html[instructions^] to upgrade to a more recent version of Astra Trident before upgrading to the Astra Control Provisioner. You can link:../use/enable-acp.html[perform a direct upgrade] to Astra Control Provisioner 24.02 if your Astra Trident is within a four-release window of version 24.02. For example, you can directly upgrade from Astra Trident 23.04 to Astra Control Provisioner 24.02.

* If you are running Astra Trident 23.10 or later, verify that Astra Control Provisioner has been link:../use/faq.html#running-acp-check[enabled]. Astra Control Provisioner will not work with releases of Astra Control Center earlier than 23.10. link:../get-started/enable-acp.html[Upgrade your Astra Control Provisioner] so that it has the same version as the Astra Control Center you are upgrading to access the latest functionality.

. Ensure that the pods are running:
+
[source,console]
----
kubectl get pods -n trident
----

. Check if the storage classes are using the supported Astra Trident drivers. The provisioner name should be `csi.trident.netapp.io`. Refer to the following example:
+
[source,console]
----
kubectl get sc
----
+
Sample response:
+
----
NAME                   PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
ontap-gold (default)   csi.trident.netapp.io          Delete          Immediate           true                   5d23h
----
