---
sidebar: sidebar
permalink: get-started/credentials-gcp.html
keywords:
summary: Learn how to create or locate existing GCP credentials so that you can use Project Astra.
---

= Google Cloud Platform (GCP) Credentials Overview
:hardbreaks:
:icons: font
:imagesdir: ../media/gcp-credentials/

Project Astra requires that you have a Google Cloud Platform (GCP) project and service account. The service account needs permissions to access specific Google Cloud APIs. This allows Project Astra to interact with GCP resources such as Google Kubernetes Engine (GKE) clusters and NetApp Cloud Volumes Service (CVS) storage.

WARNING: The free introductory tier for Google Cloud Platform only allows you to create one Kubernetes cluster at a time, among other limitations.

Instead of providing a username and password to Project Astra, you will create a service account key. The service account key is plaintext stored in the JavaScript Object Notation (JSON) format. It contains information about the GCP resources you have permission to access. You can either create a new GCP project, or generate a new service account key inside an existing GCP project.



== Create a New Set of GCP Credentials

To create a new set of GCP credentials you will need to:

1. Create or Sign in to your Google account.
2. Create a new project or use an existing one.
3. Enable specific Google Cloud APIs.
4. Create and save a service account key.

== Create a Project

To use Project Astra you will need to have a GCP project created with the correct APIs enabled. If you don't already have a GCP project, follow link:gcp-create-project.html[the steps in this article] to create one.


=== Create a New Service Account

You can create a new service account through the Google Cloud Console, or on the command line with the `gcloud` tool:

* link:gcp-create-service-account-browser.html[Google Cloud Console (browser)]
* link:gcp-create-service-account-gcloud.html[Command Line (gcloud)]

== Find Your Existing GCP Credentials

You can only view or download the Service Account key (JSON) file when you create the key. However, you can create a new key at any time.

Learn how to link:gcp-create-new-service-account-key.html[Create a New Service Account Key].
