---
sidebar: sidebar
permalink: get-started/faq.html
keywords: faq, frequently asked questions
summary: This FAQ can help if you're just looking for a quick answer to a question.
---

= Frequently asked questions for Astra Control Service
:hardbreaks:
:icons: font
:imagesdir: ../media/

This FAQ can help if you're just looking for a quick answer to a question.

== Overview

Astra Control aims to simplify your application data lifecycle management operations for Kubernetes native applications. Astra Control Service supports Kubernetes clusters running on multiple cloud provider environments.

The following sections provide answers to some additional questions that you might come across as you use Astra Control. For any additional clarifications, please reach out to astra.feedback@netapp.com

== Access to Astra Control

*Why do I need to provide so many details when registering for Astra Control?*

Astra Control requires accurate customer information when registering. This information is required to go through a Global Trade Compliance (GTC) check.

*Why am I getting a “Registration Failed” error when registering for Astra Control?*

Astra Control requires you to provide accurate customer information in the onboarding section. You will get a "Registration Failed" error if you provided incorrect information. Other accounts that you are a member of also get locked.

*What's the Astra Control Service URL?*

You can access Astra Control Service at https://astra.netapp.io.

*I sent an email invitation to a colleague, but they haven't received it. What should I do?*

Ask them to check their spam folder for an email from do-not-reply@netapp.com, or search their inbox for "invitation." You can also remove the user and attempt to re-add them.

*I upgraded to the Premium PayGO Plan from the Free Plan. Will I get charged for the first 10 applications?*

Yes. After upgrading to the Premium Plan, Astra Control starts charging you for all managed applications in your account.

*I upgraded to the Premium PayGO Plan in the middle of a month. Will I get charged for the entire month?*

No, billing starts from the time that you upgraded to the Premium Plan.

*I am using the Free Plan, will I get charged for the Persistent Volume Claims?*

Yes, you will be charged for the Persistent Volumes used by the clusters from your cloud provider.

== Registering Kubernetes clusters

*Do I need to install CSI drivers on my cluster before adding it to Astra Control Service?*

No. When your cluster is added to Astra Control, the service will automatically install NetApp’s Trident Container Storage Interface (CSI) driver on the Kubernetes cluster. This CSI driver is used to provision persistent volumes for clusters backed by your cloud provider.

*I need to add worker nodes to my cluster after adding to Astra Control Service. What should I do?*

New worker nodes can be added to existing pools, or new pools can be created as long as they are the Ubuntu image type. These will be automatically discovered by Astra Control. If the new nodes are not visible in Astra Control, check if the new worker nodes are running the supported image type. You can also verify the health of the new worker nodes by using the `kubectl get nodes` command.

ifdef::aws[]
== Registering Elastic Kubernetes Service (EKS) clusters
*Can I add a private EKS cluster to Astra Control Service?*

Private EKS clusters are not supported in Astra Control Service at this time.

endif::aws[]

ifdef::azure[]
== Registering Azure Kubernetes Service (AKS) clusters

*Can I add a private AKS cluster to Astra Control Service?*

Yes, you can add private AKS clusters to Astra Control Service.  To add a private AKS cluster, see link:add-first-cluster.html[Start managing Kubernetes clusters from Astra Control Service].

*Can I use Active Directory to manage authentication for my AKS clusters?*

Yes, you can configure your AKS clusters to use Azure Active Directory (Azure AD) for authentication and identity management. When you create the cluster, follow the instructions in the https://docs.microsoft.com/en-us/azure/aks/managed-aad[official documentation^] to configure the cluster to use Azure AD. You'll need to make sure your clusters meet the requirements for AKS-managed Azure AD integration.
endif::azure[]

ifdef::gcp[]
== Registering Google Kubernetes Engine (GKE) clusters

*Can I add a private GKE cluster to Astra Control Service?*

Yes, you can add private GKE clusters to Astra Control Service. To create a private GKE cluster, https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Project_Astra/How_to_create_a_private_GKE_cluster_to_work_with_project_Astra[follow the instructions in this knowledgebase article^].

Private clusters must have the https://cloud.google.com/kubernetes-engine/docs/concepts/private-cluster-concept[authorized networks^] set to allow the Astra Control IP address:

52.188.218.166/32

//* 54.164.233.140/32
//* 3.218.120.204/32
//* 34.193.99.138/32

*Can my GKE cluster reside on a shared VPC?*

Yes, Astra Control can manage clusters that reside in a shared VPC. link:set-up-google-cloud.html[Learn how to set up the Astra service account for a shared VPC configuration].

*Where can I find my service account credentials on GCP?*

After you log in to the https://console.cloud.google.com/[Google Cloud Console^], your service account details will be in the *IAM and Admin* section. For more details, refer to link:set-up-google-cloud.html[how to set up Google Cloud for Astra Control].

*I would like to add different GKE clusters from different GCP projects. Is this supported in Astra Control?*

No, this isn't a supported configuration. Only a single GCP project is supported.
endif::gcp[]

== Removing clusters

*How do I properly unregister, bring down a cluster, and delete the associated volumes?*

.	link:../use/unmanage.html[Unmanage the applications from Astra Control].
.	link:../use/unmanage.html#stop-managing-compute[Unregister the cluster from Astra Control].
.	link:../use/unmanage.html#deleting-clusters-from-your-cloud-provider[Delete the persistent volume claims].
.	Delete the cluster.

*What happens to my applications and data after removing the cluster from Astra Control?*

Removing a cluster from Astra Control will not make any changes to the cluster's configuration (applications and persistent storage). Any Astra Control snapshots or backups taken of applications on that cluster will be unavailable to restore. Volume snapshot data stored within the storage backend will not be removed. Persistent Storage backups created by Astra Control will remain within your cloud provider's object store, but they are unavailable for restore.

ifdef::gcp[]
WARNING: Always remove a cluster from Astra Control before you delete it through GCP. Deleting a cluster from GCP while it's still being managed by Astra Control can cause problems for your Astra Control account.
endif::gcp[]

*Will Astra Trident be uninstalled when I remove a cluster from Astra Control?*

Astra Trident will not be uninstalled from a cluster when you remove the cluster from Astra Control.

== Managing applications

*Can Astra Control deploy an application?*

Astra Control doesn't deploy applications. Applications must be deployed outside of Astra Control.

ifdef::gcp[]
*I don’t see any of my application’s PVCs bound to GCP CVS. What's wrong?*

The Astra Trident operator sets the default storage class to `netapp-cvs-perf-premium` after it's successfully added to Astra Control. When an application's PVCs are not bound to Cloud Volumes Service for Google Cloud, there are a few steps that you can take:

* Run `kubectl get sc` and check the default storage class.
* Check the yaml file or Helm chart that was used to deploy the application and see if a different storage class is defined.
* Check to make sure that the worker node image type is Ubuntu and the NFS mount succeeded.
endif::gcp[]

*What happens to applications after I stop managing them from Astra Control?*

Any existing backups or snapshots will be deleted. Applications and data remain available. Data management operations will not be available for unmanaged applications or any backups or snapshots that belong to it.

== Data management operations

*Where does Astra Control create the object store bucket?*

The geography of the first managed cluster determines the location of the object store. For example, if the first cluster that you add is in a European zone, then the bucket is created in that same geography. If needed, you can link:../use/manage-buckets.html[add additional buckets].

*There are snapshots in my account that I didn't create. Where did they come from?*

In some situations, Astra Control will automatically create a snapshot as part of performing another process. If these snapshots are more than a few minutes old, you can safely delete them.

*My application uses several PVs. Will Astra Control take snapshots and backups of all these PVCs?*

Yes. A snapshot operation on an application by Astra Control includes snapshot of all the PVs that are bound to the application’s PVCs.

*Can I manage snapshots taken by Astra Control directly through my cloud provider?*

No. Snapshots and backups taken by Astra Control can only be managed with Astra Control.
