---
sidebar: sidebar
permalink: get-started/gcp-permissions-checklist.html
keywords:
summary: Check your GCP account permissions before adding it to Project Astra.
---

= GCP Account Permissions Checklist
:hardbreaks:
:icons: font
:imagesdir: ../media/gcp-credentials/

Before you add your GCP account to Project Astra, check to be sure you have all the correct permissions. You need to check two sets of permissions:

* API access for your Project
* Roles for your service account

WARNING: The free introductory tier for Google Cloud Platform only allows you to create one Kubernetes cluster at a time, among other limitations.

== Project: API Access

Your project needs to have the following APIs enabled:

* Google Kubernetes Engine
* NetApp Cloud Volumes Service
* Cloud Storage
* Cloud Storage JSON API
* Service Usage
* Cloud Resource Manager API

**Related Article**

* link:/gcp-create-project.html[Create a GCP Project]

== Service Account: Roles

Your service account needs to have the following roles enabled:

* Compute Network Viewer
* Kubernetes Engine Admin
* NetApp Cloud Volumes Admin
* Service Usage Viewer
* Storage Admin

**Related Articles**

* link:/gcp-create-service-account-browser.html[Create a Service Account (browser)]
* link:/gcp-create-service-account-gcloud.html[Create a Service Account (gcloud)]
