---
sidebar: sidebar
permalink: get-started/install-astra-connector.html
keywords: connector, install, astra connector, manage cluster, add cluster, cluster, add, manage
summary: You can install the Astra Connector to help with managing private clusters.
---

= Install the Astra Connector
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
The Astra Connector is required to be installed on the cluster you want to manage if the cluster is private. The version of the Astra Connector that you need to install depends on your environment. Install the latest version of the Astra Connector on private Red Hat OpenShift Service on AWS (ROSA) clusters, and the older version on other types of private clusters and self-managed clusters.

* <<Install the Astra Connector for private ROSA clusters>>
* <<Install the Astra Connector for all other private clusters>>

== Install the Astra Connector for private ROSA clusters
To add private ROSA clusters, you need to install the latest version of the Astra Connector on the cluster. (For all other private clusters, including self-managed clusters, <<Install the Astra Connector for all other private clusters,install the older version of the Astra Connector>>). If you are using a bastion host, issue these commands from the command line of the bastion host. 

NOTE: After you install the Astra Connector on your ROSA cluster, the cluster is automatically added to Astra Control Service.

.Steps

. Apply the Astra Connector operator. When you run this command, the correct namespace for the Astra Connector is created and the configuration is applied to the namespace:
+
[source,console]
----
kubectl apply -f https://github.com/NetApp/astra-connector-operator/release-23.10/download/astraconnector_operator.yaml
----
. Verify that the operator is installed and ready:
+
[source,console]
----
kubectl get all -n astra-connector-operator
----
. Get an API token from Astra Control. Refer to the https://docs.netapp.com/us-en/astra-automation/get-started/get_api_token.html[Astra Automation docs^] for instructions.
. Create a secret using the token. Replace <API_TOKEN> with the token you received from Astra Control:
+
[source,console]
----
kubectl create secret generic astra-token \
--from-literal=apiToken=<API_TOKEN> \
-n neptune-system
----
. Create a Docker secret to use to pull the Astra Connector image. Replace values in brackets <> with information from your environment:
+
[source,console]
----
kubectl create secret docker-registry regcred \
--docker-username=<ASTRA_ACCOUNT_ID> \
--docker-password=<API_TOKEN> \
-n neptune-system \
--docker-server=cr.astra.netapp.io
----
. Create the Astra Connector CR file and name it `astra-connector-cr.yaml`. Update the values in brackets <> to match your Astra Control environment and cluster configuration:
+
[source,yaml]
----
apiVersion: astra.netapp.io/v1
kind: AstraConnector
metadata:
  name: astra-connector
  namespace: neptune-system
spec:
  astra:
    accountId: <ASTRA_ACCOUNT_ID>
    clusterName: <CLUSTER_NAME>
    skipTLSValidation: true
    tokenRef: astra-token
  natsSyncClient:
    cloudBridgeURL: <ASTRA_CONTROL_HOST_URL>
    hostAliasIP: <ASTRA_HOST_ALIAS_IP_ADDRESS>
  imageRegistry:
    name: cr.astra.netapp.io/astra
    secret: regcred
----
. Apply the `astra-connector-cr.yaml` file after you populate it with the correct values:
+
[source,console]
----
kubectl apply -n neptune-system -f astra-connector-cr.yaml
----
. Verify that the Astra Connector is fully deployed:
+
[source,console]
----
kubectl get all -n neptune-system
----
. Verify that the cluster is registered with Astra Control:
+
[source,console]
----
kubectl get astraconnectors.astra.netapp.io -A
----
+
You should see output similar to the following:
+
----
NAMESPACE         NAME              REGISTERED   ASTRACONNECTORID                       STATUS
neptune-system   astra-connector   true         00a821c8-2cef-41ac-8777-ed05a417883e   Registered with Astra
----

== Install the Astra Connector for all other private clusters
You need to install the older version of the Astra Connector on your private cluster if the cluster is not a ROSA cluster, or is a self-managed cluster. (For ROSA clusters, <<Install the Astra Connector for private ROSA clusters,install the latest version of the Astra Connector>>). If you are using a bastion host, issue these commands from the command line of the bastion host. 

.Steps

. Apply the Astra Connector operator. When you run this command, the correct namespace for the Astra Connector is created and the configuration is applied to the namespace:
+
[source,console]
----
kubectl apply -f https://github.com/NetApp/astra-connector-operator/release-23.07/download/astraconnector_operator.yaml
----
. Verify that the operator is installed and ready:
+
[source,console]
----
kubectl get all -n astra-connector-operator
----

. Create a namespace for the private cluster components.
+
[source,console]
----
kubectl create ns astra-connector
----

. Generate an Astra Control API token using the instructions in the https://docs.netapp.com/us-en/astra-automation/get-started/get_api_token.html[Astra Automation documentation^].

. Modify the example configuration file in the config/samples directory of the Astra Connector operator repository to include values specific to your environment for the following keys:
+
* `spec.natssync-client.cloud-bridge-url`
* `spec.astra.token`
* `spec.astra.clusterName`
* `spec.astra.accountId`
+
NOTE: `spec.astra.clusterName` is only needed if you are importing a private AKS cluster and not providing the kubeconfig file to Astra Control Service. Remove this line if this is not the case.

* `spec.astra.accountId`
+
For example:
+
[source,yaml]
----
apiVersion: netapp.astraconnector.com/v1
kind: AstraConnector
metadata:
  name: astra-connector
spec:
  natssync-client:
    image: natssync-client:2.0
    cloud-bridge-url: <ASTRA_CONTROL_SERVICE_URL>
  nats:
    image: nats:2.6.1-alpine3.14
  httpproxy-client:
    image: httpproxylet:2.0
  echo-client:
    image: echo-proxylet:2.0
  imageRegistry:
    name: theotw
    secret: otw-secret
  astra:
    token: <ASTRA_CONTROL_SERVICE_API_TOKEN>
    clusterName: <PRIVATE_AKS_CLUSTER_NAME>
    accountId: <ASTRA_CONTROL_ACCOUNT_ID>
    acceptEULA: yes
----

. Apply the Astra Connector Custom Resource Definition (CRD).
+
[source,console]
----
kubectl apply -f config/samples/astraconnector_v1.yaml -n astra-connector
----

. Check the status of the Astra Connector.
+
[source,console]
----
kubectl get astraconnector astra-connector -n astra-connector
----
+
You should see output similar to the following:
+
[source,console]
----
NAME              REGISTERED   ASTRACONNECTORID
astra-connector   true         22b839aa-8b85-445a-85dd-0b1f53b5ea19
----