---
sidebar: sidebar
permalink: get-started/install-astra-connector.html
keywords: connector, install, astra connector, manage cluster, add cluster, cluster, add, manage
summary: You can install the Astra Connector to help with managing private clusters.
---

= Install Astra Connector for private clusters
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
Astra Control Service uses Astra Connector to enable communication between Astra Control Service and private clusters. You need to install Astra Connector on private clusters that you want to manage.

Astra Connector supports the following types of private clusters:

* Amazon Elastic Kubernetes Service (EKS)
* Azure Kubernetes Service (AKS)
* Google Kubernetes Engine (GKE)
* Red Hat OpenShift Service on AWS (ROSA)
* ROSA with AWS PrivateLink
* Red Hat OpenShift Container Platform on-premise

//The Astra Connector is required to be installed on private clusters that you want to manage. The version of the Astra Connector that you need to install depends on the type of cluster. Install Astra Connector version 23.10 on private Red Hat OpenShift Service on AWS (ROSA) clusters, and Astra Connector version 23.07 on other types of private clusters and self-managed clusters.

//To add private ROSA clusters, you need to install version 23.10 of the Astra Connector on the cluster. For all other private clusters, including self-managed clusters, install Astra Connector version 23.07.  

//You need to install the older version of the Astra Connector on your private cluster if the cluster is not a ROSA cluster, or is a self-managed cluster. (For ROSA clusters, <<Install the Astra Connector for private ROSA clusters,install the latest version of the Astra Connector>>). 

== Install Astra Connector

.About this task

* When you perform these steps, execute these commands against the private cluster that you want to manage with Astra Control Service.
* If you are using a bastion host, issue these commands from the command line of the bastion host. 
//* *ROSA clusters only*: After you install Astra Connector on your ROSA cluster, the cluster is automatically added to Astra Control Service.

.Before you begin

* You need access to the private cluster you want to manage with Astra Control Service.
* You need Kubernetes administrator permissions to install the Astra Connector operator on the cluster.

.Steps

////

. Apply the correct Astra Connector operator for your cluster type. When you run this command, the correct namespace for the Astra Connector is created and the configuration is applied to the namespace:
+
[role="tabbed-block"]
====

.23.10 (Private ROSA clusters)
--
[source,console]
----
kubectl apply -f https://github.com/NetApp/astra-connector-operator/release-23.10/download/astraconnector_operator.yaml
----
--

.23.07 (All other private clusters)
--
[source,console]
----
kubectl apply -f https://github.com/NetApp/astra-connector-operator/release-23.07/download/astraconnector_operator.yaml
----
--
====

////

. Install the Astra Connector operator on the private cluster you want to manage with Astra Control Service. When you run this command, the namespace `astra-connector-operator` is created and the configuration is applied to the namespace:
+
[source,console]
----
kubectl apply -f https://github.com/NetApp/astra-connector-operator/releases/download/23.07.0-202310251519/astraconnector_operator.yaml
----

. Verify that the operator is installed and ready:
+
[source,console]
----
kubectl get all -n astra-connector-operator
----
. Get an API token from Astra Control. Refer to the https://docs.netapp.com/us-en/astra-automation/get-started/get_api_token.html[Astra Automation documentation^] for instructions.

. Create the astra-connector namespace:
+
[source,console]
----
kubectl create ns astra-connector
----
//. (Astra Connector 23.10 only) Create a secret using the token. Replace <API_TOKEN> with the token you received from Astra Control:
//+
//[source,console]
//----
//kubectl create secret generic astra-token \
//--from-literal=apiToken=<API_TOKEN> \
//-n astra-connector
//----
. Create the Astra Connector CR file and name it `astra-connector-cr.yaml`. Update the values in brackets <> to match your Astra Control environment and cluster configuration:
+
* *<ASTRA_CONTROL_SERVICE_URL>*: The web UI URL of Astra Control Service. For example:
+
----
https://astra.netapp.io
----
* *<ASTRA_CONTROL_SERVICE_API_TOKEN>*: The Astra Control API token you obtained in the preceding step.
* *<PRIVATE_AKS_CLUSTER_NAME>*: (AKS clusters only) - The cluster name of the private Azure Kubernetes Service cluster. Uncomment and populate this line only if you are adding a private AKS cluster.
* *<ASTRA_CONTROL_ACCOUNT_ID>*: Obtained from the Astra Control web UI. Select the figure icon at the top right of the page and select *API access*.
+
[source,yaml]
----
apiVersion: netapp.astraconnector.com/v1
kind: AstraConnector
metadata:
  name: astra-connector
  namespace: astra-connector
spec:
  natssync-client:
    cloud-bridge-url: <ASTRA_CONTROL_SERVICE_URL>
  imageRegistry:
    name: theotw
    secret: ""
  astra:
    token: <ASTRA_CONTROL_SERVICE_API_TOKEN>
    #clusterName: <PRIVATE_AKS_CLUSTER_NAME>
    accountId: <ASTRA_CONTROL_ACCOUNT_ID>
    acceptEULA: yes
----
. After you populate the `astra-connector-cr.yaml` file with the correct values, apply the CR:
+
[source,console]
----
kubectl apply -f astra-connector-cr.yaml
----
. Verify that the Astra Connector is fully deployed:
+
[source,console]
----
kubectl get all -n astra-connector
----
. Verify that the cluster is registered with Astra Control:
+
[source,console]
----
kubectl get astraconnector -n astra-connector
----
+
You should see output similar to the following:
+
----
NAME              REGISTERED   ASTRACONNECTORID                       STATUS
astra-connector   true         be475ae5-1511-4eaa-9b9e-712f09b0d065   Registered with Astra
----
+
TIP: Make note of the ASTRACONNECTORID; you will need it when you add the cluster to Astra Control.

////

.Steps

. Apply the Astra Connector operator. When you run this command, the correct namespace for the Astra Connector is created and the configuration is applied to the namespace:
+
[source,console]
----
kubectl apply -f https://github.com/NetApp/astra-connector-operator/release-23.07/download/astraconnector_operator.yaml
----
. Verify that the operator is installed and ready:
+
[source,console]
----
kubectl get all -n astra-connector-operator
----

. Create a namespace for the private cluster components.
+
[source,console]
----
kubectl create ns astra-connector
----

. Generate an Astra Control API token using the instructions in the https://docs.netapp.com/us-en/astra-automation/get-started/get_api_token.html[Astra Automation documentation^].

. Modify the example configuration file in the config/samples directory of the Astra Connector operator repository to include values specific to your environment for the following keys:
+
* `spec.natssync-client.cloud-bridge-url`
* `spec.astra.token`
* `spec.astra.clusterName`
* `spec.astra.accountId`
+
NOTE: `spec.astra.clusterName` is only needed if you are importing a private AKS cluster and not providing the kubeconfig file to Astra Control Service. Remove this line if this is not the case.

* `spec.astra.accountId`
+
For example:
+
[source,yaml]
----

----

. Apply the Astra Connector Custom Resource Definition (CRD).
+
[source,console]
----
kubectl apply -f config/samples/astraconnector_v1.yaml -n astra-connector
----

. Check the status of the Astra Connector.
+
[source,console]
----
kubectl get astraconnector astra-connector -n astra-connector
----
+
You should see output similar to the following:
+
[source,console]
----
NAME              REGISTERED   ASTRACONNECTORID
astra-connector   true         22b839aa-8b85-445a-85dd-0b1f53b5ea19
----

////


////
. (Astra Connector 23.10 only) Create a Docker secret to use to pull the Astra Connector image. Replace values in brackets <> with information from your environment:
+
[source,console]
----
kubectl create secret docker-registry regcred \
--docker-username=<ASTRA_ACCOUNT_ID> \
--docker-password=<API_TOKEN> \
-n astra-connector \
--docker-server=cr.astra.netapp.io
----

. Create the correct Astra Connector CR file for the version of the Astra Connector you downloaded and name it `astra-connector-cr.yaml`. Update the values in brackets <> to match your Astra Control environment and cluster configuration:
+
[role="tabbed-block"]
====
.23.10 (Private ROSA clusters)
--
[source,yaml]
----
apiVersion: astra.netapp.io/v1
kind: AstraConnector
metadata:
  name: astra-connector
  namespace: astra-connector
spec:
  astra:
    accountId: <ASTRA_ACCOUNT_ID>
    clusterName: <CLUSTER_NAME>
    skipTLSValidation: true
    tokenRef: astra-token
  natsSyncClient:
    cloudBridgeURL: <ASTRA_CONTROL_HOST_URL>
    hostAliasIP: <ASTRA_HOST_ALIAS_IP_ADDRESS>
  imageRegistry:
    name: cr.astra.netapp.io/astra
    secret: regcred
----
--
.23.07 (All other private clusters)
--
[source,yaml]
----
apiVersion: netapp.astraconnector.com/v1
kind: AstraConnector
metadata:
  name: astra-connector
  namespace: astra-connector
spec:
  natssync-client:
    image: natssync-client:2.0
    cloud-bridge-url: <ASTRA_CONTROL_SERVICE_URL>
  nats:
    image: nats:2.6.1-alpine3.14
  httpproxy-client:
    image: httpproxylet:2.0
  echo-client:
    image: echo-proxylet:2.0
  imageRegistry:
    name: theotw
    secret: otw-secret
  astra:
    token: <ASTRA_CONTROL_SERVICE_API_TOKEN>
    clusterName: <PRIVATE_AKS_CLUSTER_NAME>
    accountId: <ASTRA_CONTROL_ACCOUNT_ID>
    acceptEULA: yes
----
--
====

////


== What's next?

Now that you've installed Astra Connector, you're ready to add your private cluster to Astra Control Service.

* link:add-private-provider-managed-cluster.html[Add a private provider-managed cluster to Astra Control Service^]: Use these steps to add a cluster that has a private IP address and is managed by a cloud provider. You will need the Service Principal account, service account, or user account for the cloud provider.
* link:add-private-self-managed-cluster.html[Add a private self-managed cluster to Astra Control Service^]: Use these steps to add a cluster that has a private IP address and is managed by your organization. You will need to create a kubeconfig file for the cluster you want to add.

== For more information

* link:add-first-cluster.html[Add a cluster^]


