---
sidebar: sidebar
permalink: get-started/install-astra-connector-previous.html
keywords: connector, install, astra connector, manage cluster, add cluster, cluster, add, manage
summary: You can install the Astra Connector to help with managing private clusters.
---

= Install the previous version of Astra Connector
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
Astra Control Service uses the previous version of Astra Connector to enable communication between Astra Control Service and private clusters managed with non-Kubernetes-native workflows. You need to install Astra Connector on private clusters that you want to manage with non-Kubernetes-native workflows.

The previous version of Astra Connector supports the following types of private clusters managed with non-Kubernetes-native workflows:

* Amazon Elastic Kubernetes Service (EKS)
* Azure Kubernetes Service (AKS)
* Google Kubernetes Engine (GKE)
* Red Hat OpenShift Service on AWS (ROSA)
* ROSA with AWS PrivateLink
* Red Hat OpenShift Container Platform on-premise

.About this task

* When you perform these steps, execute these commands against the private cluster that you want to manage with Astra Control Service.
* If you are using a bastion host, issue these commands from the command line of the bastion host. 

.Before you begin

* You need access to the private cluster you want to manage with Astra Control Service.
* You need Kubernetes administrator permissions to install the Astra Connector operator on the cluster.

.Steps

. Install the previous Astra Connector operator on the private cluster you want to manage with non-Kubernetes-native workflows. When you run this command, the namespace `astra-connector-operator` is created and the configuration is applied to the namespace:
+
[source,console]
----
kubectl apply -f https://github.com/NetApp/astra-connector-operator/releases/download/23.07.0-202310251519/astraconnector_operator.yaml
----

. Verify that the operator is installed and ready:
+
[source,console]
----
kubectl get all -n astra-connector-operator
----
. Get an API token from Astra Control. Refer to the https://docs.netapp.com/us-en/astra-automation/get-started/get_api_token.html[Astra Automation documentation^] for instructions.

. Create the astra-connector namespace:
+
[source,console]
----
kubectl create ns astra-connector
----
. Create the Astra Connector CR file and name it `astra-connector-cr.yaml`. Update the values in brackets <> to match your Astra Control environment and cluster configuration:
+
* *<ASTRA_CONTROL_SERVICE_URL>*: The web UI URL of Astra Control Service. For example:
+
----
https://astra.netapp.io
----
* *<ASTRA_CONTROL_SERVICE_API_TOKEN>*: The Astra Control API token you obtained in the preceding step.
* *<PRIVATE_AKS_CLUSTER_NAME>*: (AKS clusters only) - The cluster name of the private Azure Kubernetes Service cluster. Uncomment and populate this line only if you are adding a private AKS cluster.
* *<ASTRA_CONTROL_ACCOUNT_ID>*: Obtained from the Astra Control web UI. Select the figure icon at the top right of the page and select *API access*.
+
[source,yaml]
----
apiVersion: netapp.astraconnector.com/v1
kind: AstraConnector
metadata:
  name: astra-connector
  namespace: astra-connector
spec:
  natssync-client:
    cloud-bridge-url: <ASTRA_CONTROL_SERVICE_URL>
  imageRegistry:
    name: theotw
    secret: ""
  astra:
    token: <ASTRA_CONTROL_SERVICE_API_TOKEN>
    #clusterName: <PRIVATE_AKS_CLUSTER_NAME>
    accountId: <ASTRA_CONTROL_ACCOUNT_ID>
    acceptEULA: yes
----
. After you populate the `astra-connector-cr.yaml` file with the correct values, apply the CR:
+
[source,console]
----
kubectl apply -f astra-connector-cr.yaml
----
. Verify that the Astra Connector is fully deployed:
+
[source,console]
----
kubectl get all -n astra-connector
----
. Verify that the cluster is registered with Astra Control:
+
[source,console]
----
kubectl get astraconnector -n astra-connector
----
+
You should see output similar to the following:
+
----
NAME              REGISTERED   ASTRACONNECTORID                       STATUS
astra-connector   true         be475ae5-1511-4eaa-9b9e-712f09b0d065   Registered with Astra
----
+
TIP: Make note of the ASTRACONNECTORID; you will need it when you add the cluster to Astra Control.

== What's next?

Now that you've installed Astra Connector, you're ready to add your private cluster to Astra Control Service.

* link:add-private-provider-managed-cluster.html[Add a private provider-managed cluster to Astra Control Service^]: Use these steps to add a cluster that has a private IP address and is managed by a cloud provider. You will need the Service Principal account, service account, or user account for the cloud provider.
* link:add-private-self-managed-cluster.html[Add a private self-managed cluster to Astra Control Service^]: Use these steps to add a cluster that has a private IP address and is managed by your organization. You will need to create a kubeconfig file for the cluster you want to add.

== For more information

* link:add-first-cluster.html[Add a cluster^]


