---
sidebar: sidebar
permalink: get-started/install-astra-connector.html
keywords: connector, install, astra connector, manage cluster, add cluster, cluster, add, manage
summary: You can install the Astra Connector to help with managing private clusters.
---

= Install the Astra Connector
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
The Astra Connector is required to be installed on the cluster you want to manage if the cluster is private. The version of the Astra Connector that you need to install depends on your environment. Install the latest version of the Astra Connector on Red Hat OpenShift clusters that are on-premises or hosted in Amazon EKS, and the older version on other types of private clusters.

* <<Install the Astra Connector for on-premises or private EKS OpenShift clusters>>
* <<Install the Astra Connector for all other private clusters>>

== Install the Astra Connector for on-premises or private EKS OpenShift clusters
If your private cluster is based on Red Hat OpenShift and is hosted on-premesis or in Amazon EKS, you need to install the latest version of the Astra Connector on the cluster. (For all other clusters, <<Install the Astra Connector for all other private clusters,install the older version of the Astra Connector>>). If you are using a bastion host, issue these commands from the command line of the bastion host. 

.Steps

. Apply the Astra Connector Operator:
+
[source,console]
----
kubectl apply -f https://github.com/NetApp/astra-connector-operator/releases/latest/download/astraconnector_operator.yaml
----
. Verify that the operator is installed and ready:
+
[source,console]
----
kubectl get all -n astra-connector-operator
----
. Get an API token from Astra Control. Refer to the https://docs.netapp.com/us-en/astra-automation/get-started/get_api_token.html[Astra Automation docs^] for instructions.
. Create a secret using the token. Replace <API_TOKEN> with the token you received from Astra Control:
+
[source,console]
----
kubectl create secret generic astra-token --from-literal=apiToken=<API_TOKEN> -n neptune-system
secret/astra-token created
----
. Create a Docker secret to use to pull the Astra Connector image. Replace <DOCKER_PASSWORD> with your Docker password:
+
[source,console]
----
kubectl create secret docker-registry regcred --docker-username=astra-control-downloaders-staging --docker-password=<DOCKER_PASSWORD> -n neptune-system --docker-server=netappdownloads.jfrog.io
----
. Create the Astra Connector CR file and name it `astra-connector-cr.yaml`. Update the values to match your Astra Control environment and cluster configuration:
+
[source,yaml]
----
apiVersion: astra.netapp.io/v1
kind: AstraConnector
metadata:
  name: astra-connector
  namespace: neptune-system
spec:
  astra:
    accountId: <ASTRA_ACCOUNT_ID>
    clusterName: <CLUSTER_NAME_YOU_WANT_TO_USE>
    skipTLSValidation: true
    tokenRef: astra-token
  natsSyncClient:
    cloudBridgeURL: <ASTRA_HOST_URL>
    hostAliasIP: <ASTRA_HOST_ALIAS_IP>
  imageRegistry:
    name: netappdownloads.jfrog.io/docker-astra-control-staging/arch30/neptune
    secret: regcred
----
. Apply the `astra-connector-cr.yaml` file after you populate it with the correct values:
+
[source,console]
----
kubectl apply -n neptune-system -f astra-connector-cr.yaml
----
. Verify that the Astra Connector is fully deployed:
+
[source,console]
----
kubectl get all -n neptune-system
----
. Verify that the cluster is registered with Astra Control:
+
[source,console]
----
kubectl get astraconnectors.astra.netapp.io -A
----
+
You should see output similar to the following:
+
----
NAMESPACE         NAME              REGISTERED   ASTRACONNECTORID                       STATUS
neptune-system   astra-connector   true         00a821c8-2cef-41ac-8777-ed05a417883e   Registered with Astra
----

== Install the Astra Connector for all other private clusters
You need to install the older version of the Astra Connector on the private cluster if your cluster is not based on Red Hat OpenShift. (For OpenShift clusters, <<Install the Astra Connector for on-premises or private EKS OpenShift clusters,install the latest version of the Astra Connector>>). If you are using a bastion host, issue these commands from the command line of the bastion host. 

.Steps

. Clone the Astra Connector operator GitHub repository:
+
[source,console]
----
git clone https://github.com/NetApp/astra-connector-operator.git
----
. Change directories to the top level of the unpacked operator package, so that you can see the `astraconnector_operator.yaml` file with the `ls` command.

. Create a namespace for the Astra Connector operator.
+
[source,console]
----
kubectl create ns astra-connector-operator
----

. Apply the `astraconnector_operator.yaml` file to the operator namespace.
+
[source,console]
----
kubectl apply -f astraconnector_operator.yaml -n astra-connector-operator
----

. Create a namespace for the private cluster components.
+
[source,console]
----
kubectl create ns astra-connector
----

. Generate an Astra Control API token using the instructions in the https://docs.netapp.com/us-en/astra-automation/get-started/get_api_token.html[Astra Automation documentation^].

. Modify the example configuration file in the config/samples directory of the Astra Connector operator repository to include values specific to your environment for the following keys:
+
* `spec.natssync-client.cloud-bridge-url`
* `spec.astra.token`
* `spec.astra.clusterName`
+
NOTE: `spec.astra.clusterName` is only needed if you are importing a private AKS cluster and not providing the kubeconfig file to Astra Control Service. Remove this line if this is not the case.

* `spec.astra.accountId`
+
For example:
+
----
apiVersion: netapp.astraconnector.com/v1
kind: AstraConnector
metadata:
  name: astra-connector
spec:
  natssync-client:
    image: natssync-client:2.0
    cloud-bridge-url: https://<your.astra.control.service.url>
  nats:
    image: nats:2.6.1-alpine3.14
  httpproxy-client:
    image: httpproxylet:2.0
  echo-client:
    image: echo-proxylet:2.0
  imageRegistry:
    name: theotw
  astra:
    token: <Astra Control API token>
    clusterName: <your-private-AKS-cluster-name>
    accountId: <Astra Control account id>
    acceptEULA: yes
----

. Apply the Astra Connector Custom Resource Definition (CRD).
+
[source,console]
----
kubectl apply -f config/samples/astraconnector_v1.yaml -n astra-connector
----

. Check the status of the Astra Connector.
+
[source,console]
----
kubectl get astraconnector astra-connector -n astra-connector
----
+
You should see output similar to the following:
+
[source,console]
----
NAME              REGISTERED   ASTRACONNECTORID
astra-connector   true         22b839aa-8b85-445a-85dd-0b1f53b5ea19
----