---
sidebar: sidebar
permalink: get-started/intro.html
keywords: introduction, how astra works, how Astra works, what Astra is, concept, understanding, overview
summary: Astra Control is a Kubernetes application data lifecycle management solution that simplifies operations for stateful applications. Easily protect, back up, and migrate Kubernetes workloads, and instantly create working application clones.
---

= Learn about Astra Control
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

//Remote includes from ACC repo
//include::https://raw.githubusercontent.com/NetAppDocs/astra-control-center/main/_include/source-intro.adoc[]

Astra Control is a Kubernetes application data lifecycle management solution that simplifies operations for stateful applications. Easily protect, back up, and migrate Kubernetes workloads, and instantly create working application clones.

== Features

Astra Control offers critical capabilities for Kubernetes application data lifecycle management:

* Automatically manage persistent storage
* Create application-aware, on-demand snapshots and backups
* Automate policy-driven snapshot and backup operations
* Migrate applications and data from one Kubernetes cluster to another
* Easily clone an application from production to staging
* Visualize application health and protection status
* Use a user interface or an API to implement your backup and migration workflows

Astra Control continually watches your compute for state changes, so it’s aware of any new apps that you add along the way.


== Deployment models
Astra Control is available in two deployment models:

* *Astra Control Service*: A NetApp-managed service that provides application-aware data management of Kubernetes clusters in multiple cloud provider environments.
* *Astra Control Center*: Self-managed software that provides application-aware data management of Kubernetes clusters running in your on-premises environment.

[cols=3*,options="header",cols="1h,2d,2a"]
|===
|
| Astra Control Service
| Astra Control Center
| How is it offered? | As a fully managed cloud service from NetApp | As software that you download, install, and manage
| Where is it hosted? | On a public cloud of NetApp's choice | On your provided Kubernetes cluster
| How is it updated? | Managed by NetApp | You manage any updates
| What are the app data management capabilities? | Same capabilities on both platforms with exceptions to storage backend or to external services | Same capabilities on both platforms with exceptions to storage backend or to external services
| What is the storage backend support? | NetApp cloud service offerings |

* NetApp ONTAP AFF and FAS systems
* Astra Data Store as storage backend
* Cloud Volumes ONTAP storage backend
|===

== Supported apps

//Astra Control Center does not support apps that are deployed with Operator Lifecycle Manager (OLM)-enabled operators or cluster-scoped operators.

NetApp has validated some apps to ensure the safety and consistency of the snapshots and backups.

* https://docs.netapp.com/us-en/astra/learn/validated-vs-standard.html[Learn the difference between a validated app and a standard app in Astra Control Service^].
* https://docs.netapp.com/us-en/astra-control-center/concepts/validated-vs-standard.html[Learn the difference between a validated app and a standard app in Astra Control Center^].

No matter which type of app that you use with Astra Control, you should always test the backup and restore workflow yourself to ensure that you can meet your disaster recovery requirements.

== How Astra Control Service works

Astra Control Service is a NetApp-managed cloud service that is always on and updated with the latest capabilities. It utilizes several components to enable application data lifecycle management.


At a high level, Astra Control Service works like this:

* You get started with Astra Control Service by setting up your cloud provider and by registering for an Astra account.
ifdef::gcp[]
+
** For GKE clusters, Astra Control Service uses https://cloud.netapp.com/cloud-volumes-service-for-gcp[NetApp Cloud Volumes Service for Google Cloud^] or Google Persistent Disks as the storage backend for your persistent volumes.
endif::gcp[]
ifdef::azure[]
+
** For AKS clusters, Astra Control Service uses https://cloud.netapp.com/azure-netapp-files[Azure NetApp Files^] or Azure Disk Storage as the storage backend for your persistent volumes.
endif::azure[]
ifdef::aws[]
+
** For Amazon EKS clusters, Astra Control Service uses https://docs.aws.amazon.com/ebs/[Amazon Elastic Block Store^] or https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html[Amazon FSx for NetApp ONTAP^] as the storage backend for your persistent volumes.

* You add your first Kubernetes compute to Astra Control Service. Astra Control Service then does the following:

** Creates an object store in your cloud provider account, which is where backup copies are stored.
ifdef::azure[]
+
In Azure, Astra Control Service also creates a resource group, a storage account, and keys for the Blob container.
endif::azure[]
** Creates a new admin role and Kubernetes service account on the cluster.

** Uses that new admin role to install https://docs.netapp.com/us-en/trident/index.html[Astra Trident^] on the cluster and to create one or more storage classes.

+
** If you use a cloud provider storage service as your storage backend, Astra Control Service uses Astra Trident to provision persistent volumes for your apps.

* At this point, you can add apps to your cluster. Persistent volumes will be provisioned on the new default storage class.

* You then use Astra Control Service to manage these apps, and start creating snapshots, backups, and clones.
+
Astra Control Service continually watches your compute for state changes, so it's aware of any new apps that you add along the way.

Astra Control's Free Plan enables you to manage up to 10 apps in your account. If you want to manage more than 10 apps, then you'll need to set up billing by upgrading from the Free Plan to the Premium Plan.


== How Astra Control Center works

Astra Control Center runs locally in your own private cloud.

Astra Control Center supports OpenShift Kubernetes clusters with:

* Trident storage backends with ONTAP 9.5 and above
* Astra Data Store storage backends

In a cloud connected environment Astra Control Center uses Cloud Insights to provide advanced monitoring and telemetry. In the absence of a Cloud Insights connection, limited (7-days of metrics) monitoring and telemetry is available in Astra Control Center and also exported to Kubernetes native monitoring tools (such as Prometheus and Grafana) through open metrics end points.

Astra Control Center is fully integrated into the AutoSupport and Active IQ ecosystem to provide users and NetApp Support with troubleshooting and usage information.

You can try Astra Control Center out using a 90-day evaluation license. The evaluation version is supported through email and community (Slack channel) options. Additionally, you have access to Knowledgebase articles and documentation from the in-product support dashboard.

To install and use Astra Control Center, you'll need to meet certain https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html[requirements].

At a high level, Astra Control Center works like this:

* You install Astra Control Center in your local environment. Learn more about how to https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc.html[install Astra Control Center].

* You complete some setup tasks such as these:

** Set up licensing.
** Add your first cluster.
** Add storage backend that is discovered when you added the cluster.
** Add an object store bucket that will store your app backups.

Learn more about how to https://docs.netapp.com/us-en/astra-control-center/get-started/setup_overview.html[set up Astra Control Center].

Astra Control Center does this:

* Discovers details about the managed Kubernetes clusters.
* Discovers your Astra Trident or Astra Data Store configuration on the clusters that you choose to manage and lets you monitor the storage backends.
* Discovers apps on those clusters and enables you to manage and protect the apps.

You can add apps to your cluster. Or, if you have some apps already in the cluster being managed, you can use Astra Control Center to discover and manage them. Then, use Astra Control Center to create snapshots, backups, and clones.


== For more information

* https://docs.netapp.com/us-en/astra/index.html[Astra Control Service documentation^]
* https://docs.netapp.com/us-en/astra-control-center/index.html[Astra Control Center documentation^]
* https://docs.netapp.com/us-en/astra-data-store/index.html[Astra Data Store documentation]
* https://docs.netapp.com/us-en/trident/index.html[Astra Trident documentation^]
* https://docs.netapp.com/us-en/astra-automation/index.html[Use the Astra Control API^]
* https://docs.netapp.com/us-en/cloudinsights/[Cloud Insights documentation^]
* https://docs.netapp.com/us-en/ontap/index.html[ONTAP documentation^]
