---
sidebar: sidebar
permalink: get-started/intro.html
keywords: introduction, how astra works, how Astra works, what Astra is, concept, understanding, overview
summary: Astra Control is a Kubernetes application data lifecycle management solution that simplifies operations for stateful applications. Easily protect, back up, and migrate Kubernetes workloads, and instantly create working application clones.
---

= Learn about Astra Control
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

//Remote includes from ACC repo
//include::https://raw.githubusercontent.com/NetAppDocs/astra-control-center/main/_include/source-intro.adoc[]

[.lead]
Astra Control is a Kubernetes application data lifecycle management solution that simplifies operations for stateful applications. Easily protect, back up, and migrate Kubernetes workloads, and instantly create working application clones.

== Features

Astra Control offers critical capabilities for Kubernetes application data lifecycle management:

* Automatically manage persistent storage
* Create application-aware, on-demand snapshots and backups
* Automate policy-driven snapshot and backup operations
* Migrate applications and data from one Kubernetes cluster to another
* Replicate applications to a remote system using NetApp SnapMirror technology (Astra Control Center)
* Clone applications from staging to production
* Visualize application health and protection status
* Work with a web UI or an API to implement your backup and migration workflows

== Deployment models
Astra Control is available in two deployment models:

* *Astra Control Service*: A NetApp-managed service that provides application-aware data management of Kubernetes clusters in multiple cloud provider environments, as well as self-managed Kubernetes clusters.
* *Astra Control Center*: Self-managed software that provides application-aware data management of Kubernetes clusters running in your on-premises environment. Astra Control Center can also be installed  on multiple cloud provider environments with a NetApp Cloud Volumes ONTAP storage backend.

[cols=3*,options="header",cols="1h,2d,2a"]
|===
|
| Astra Control Service
| Astra Control Center
| How is it offered? | As a fully managed cloud service from NetApp | As software that you can download, install, and manage
| Where is it hosted? | On a public cloud of NetApp's choice | On your own Kubernetes cluster
| How is it updated? | Managed by NetApp | You manage any updates
|What are the supported Kubernetes distributions?
a|
* *Cloud providers*
** Amazon Web Services
*** Amazon Elastic Kubernetes Service (EKS) 
** Google Cloud
*** Google Kubernetes Engine (GKE)
** Microsoft Azure
*** Azure Kubernetes Service (AKS)
* *Self-managed clusters*
** Kubernetes (Upstream)
** Rancher Kubernetes Engine (RKE)
** Red Hat OpenShift Container Platform
* *On-premise clusters*
** Red Hat OpenShift Container Platform on-premise
a|
* Azure Kubernetes Service on Azure Stack HCI
* Google Anthos
* Kubernetes (Upstream)
* Rancher Kubernetes Engine (RKE)
* Red Hat OpenShift Container Platform
| What are the supported storage backends?
a|
* *Cloud providers*
** Amazon Web Services
*** Amazon EBS
*** Amazon FSx for NetApp ONTAP
*** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html[Cloud Volumes ONTAP^]
** Google Cloud
*** Google Persistent Disk
*** NetApp Cloud Volumes Service
*** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html[Cloud Volumes ONTAP^]
** Microsoft Azure
*** Azure Managed Disks
*** Azure NetApp Files
*** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-azure.html[Cloud Volumes ONTAP^]
* *Self-managed clusters*
** Amazon EBS
** Azure Managed Disks
** Google Persistent Disk
** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/[Cloud Volumes ONTAP^]
** NetApp MetroCluster
** https://longhorn.io/[Longhorn^]
* *On-premise clusters*
** NetApp MetroCluster
** NetApp ONTAP AFF and FAS systems
** NetApp ONTAP Select
** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/[Cloud Volumes ONTAP^]
** https://longhorn.io/[Longhorn^]
|
* NetApp ONTAP AFF and FAS systems
* NetApp ONTAP Select
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/[Cloud Volumes ONTAP^]
* https://longhorn.io/[Longhorn^]
|===

== How Astra Control Service works

Astra Control Service is a NetApp-managed cloud service that is always on and updated with the latest capabilities. It utilizes several components to enable application data lifecycle management.

At a high level, Astra Control Service works like this:

* You get started with Astra Control Service by setting up your cloud provider and by registering for an Astra account.
ifdef::gcp[]
+
** For GKE clusters, Astra Control Service uses https://cloud.netapp.com/cloud-volumes-service-for-gcp[NetApp Cloud Volumes Service for Google Cloud^] or Google Persistent Disks as the storage backend for your persistent volumes.
endif::gcp[]
ifdef::azure[]
+
** For AKS clusters, Astra Control Service uses https://cloud.netapp.com/azure-netapp-files[Azure NetApp Files^] or Azure managed disks as the storage backend for your persistent volumes.
endif::azure[]
ifdef::aws[]
+
** For Amazon EKS clusters, Astra Control Service uses https://docs.aws.amazon.com/ebs/[Amazon Elastic Block Store^] or https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html[Amazon FSx for NetApp ONTAP^] as the storage backend for your persistent volumes.
endif::aws[]
* You add your first Kubernetes compute to Astra Control Service. Astra Control Service then does the following:

** Creates an object store in your cloud provider account, which is where backup copies are stored.
ifdef::azure[]
+
In Azure, Astra Control Service also creates a resource group, a storage account, and keys for the Blob container.
endif::azure[]
** Creates a new admin role and Kubernetes service account on the cluster.

** Uses that new admin role to install link../concepts/architecture#astra-control-components[Astra Control Provisioner] on the cluster and to create one or more storage classes.

+
** If you use a NetApp cloud service storage offering as your storage backend, Astra Control Service uses Astra Control Provisioner to provision persistent volumes for your apps. If you use Amazon EBS or Azure managed disks as your storage backend, you need to install a provider-specific CSI driver. Installation instructions are provided in link:set-up-amazon-web-services.html[Set up Amazon Web Services^] and link:set-up-microsoft-azure-with-amd.html[Set up Microsoft Azure with Azure managed disks^].

* At this point, you can define apps from your cluster. Persistent volumes will be provisioned on the storage backend through the new default storage class.

* You then use Astra Control Service to manage these apps, and start creating snapshots, backups, and clones.

Astra Control's Free Plan enables you to manage up to 10 namespaces in your account. If you want to manage more than 10 namespaces, then you'll need to set up billing by upgrading from the Free Plan to the Premium Plan.


== How Astra Control Center works

Astra Control Center runs locally in your own private cloud.

Astra Control Center supports Kubernetes clusters with an Astra Control Provisioner-configured storage class with an ONTAP storage backend.


In a cloud connected environment Astra Control Center uses Cloud Insights to provide advanced monitoring and telemetry. In the absence of a Cloud Insights connection, limited (7 days of metrics) monitoring and telemetry is available in Astra Control Center and also exported to Kubernetes native monitoring tools (such as Prometheus and Grafana) through open metrics end points.

Astra Control Center is fully integrated into the AutoSupport and Active IQ ecosystem to provide users and NetApp Support with troubleshooting and usage information.

You can try Astra Control Center out using a 90-day evaluation license. The evaluation version is supported through email and community options. Additionally, you have access to Knowledgebase articles and documentation from the in-product support dashboard.

To install and use Astra Control Center, you'll need to meet certain https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html[requirements].

At a high level, Astra Control Center works like this:

* You install Astra Control Center in your local environment. Learn more about how to https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc.html[install Astra Control Center].

* You complete some setup tasks such as these:

** Set up licensing.
** Add your first cluster.
** Add storage backend that is discovered when you added the cluster.
** Add an object store bucket that will store your app backups.

Learn more about how to https://docs.netapp.com/us-en/astra-control-center/get-started/setup_overview.html[set up Astra Control Center].


You can add applications to your cluster. Or, if you have some applications already in the cluster being managed, you can use Astra Control Center to manage them. Then, use Astra Control Center to create snapshots, backups, clones and replication relationships.


== For more information

* https://docs.netapp.com/us-en/astra-family/[NetApp Astra product family documentation^]
* https://docs.netapp.com/us-en/astra-control-center/index.html[Astra Control Center documentation^]
* https://docs.netapp.com/us-en/astra-automation/index.html[Astra Control API documentation^]
* https://docs.netapp.com/us-en/trident/index.html[Astra Trident documentation^]
* https://docs.netapp.com/us-en/cloudinsights/[Cloud Insights documentation^]
* https://docs.netapp.com/us-en/ontap/index.html[ONTAP documentation^]
