---
sidebar: sidebar
permalink: get-started/intro.html
keywords: introduction, how astra works, how Astra works, what Astra is, concept, understanding, overview
summary: Astra is a Kubernetes application data lifecycle management service that simplifies operations for stateful applications. Easily back up Kubernetes apps, migrate data to a different cluster, and instantly create working application clones.
---

= Intro to Astra
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

Astra is a Kubernetes application data lifecycle management service that simplifies operations for stateful applications. Easily back up Kubernetes apps, migrate data to a different cluster, and instantly create working application clones.

== Features

Astra offers critical capabilities for Kubernetes application data lifecycle management:

* Create a protection policy for each of your apps
* Migrate applications and data from one Kubernetes cluster to another
* Easily clone an application from production to staging
* Create on-demand snapshots and backups
* Identify the health of your apps

== Supported Kubernetes deployments

Astra can manage apps on Google Kubernetes Engine (GKE) clusters.

On-prem Kubernetes clusters and clusters running in other cloud providers aren't supported at this time.

link:requirements.html[Learn about cluster requirements].

== How Astra works

Astra is a NetApp-managed cloud service that is always on and updated with the latest capabilities. It utilizes several components to enable application data lifecycle management.

//The following image shows the relationship between each component:

At a high level, Astra works like this:

* You set up your cloud provider by enabling Cloud Volumes Service for Google Cloud and by creating a GCP service account for Astra.
+
Astra uses https://cloud.netapp.com/cloud-volumes-service-for-gcp[Cloud Volumes Service for Google Cloud^] as the backend storage for your persistent volumes.

* You add your first Kubernetes compute to Astra. Astra then does the following:

** Creates an object store in your cloud provider account, which is where backup copies are sent.

** Creates a new admin role and Kubernetes service account on the cluster.

** Uses that new admin role to install https://netapp-trident.readthedocs.io/[NetApp's Trident^].

** Astra uses Trident to provision persistent volumes backed by NetApp Cloud Volumes Service for Google Cloud.

** Astra creates one or more storage classes that use Cloud Volumes Service for Google Cloud.

* At this point, you can add apps to your cluster. Persistent volumes will be provisioned on the new default storage class. link:../learn/choose-class-and-size.html[Learn about storage classes and persistent volume sizes].

* You then use Astra to manage these apps, and start creating snapshots, backups, and clones.

Note that Astra continually watches your compute for state changes, so it's aware of any new apps that you add along the way.

== Pricing

There are two types of costs associated with using Astra to manage your apps: charges from NetApp for the Astra service and charges from your cloud provider for persistent volumes and object storage.

=== Astra billing

Astra offers two plans:

* *Free Plan*: Manage up to 10 apps for free.
* *Premium Plan*: Manage an unlimited amount of apps at a rate of $.005 per minute per app.

When you create an Astra account, you're automatically signed up for the Free Plan. You can link:../use/set-up-billing.html[upgrade to the Premium Plan at any time]. After you upgrade, Astra starts charging you for _all_ managed apps in the account. The first 10 apps don't stay in the Free Plan.

=== Cloud provider billing

* https://cloud.google.com/solutions/partners/netapp-cloud-volumes/costs[View pricing details for Cloud Volumes Service^].
+
Note that Astra supports all service types and service levels. The service type that you choose depends on your https://cloud.netapp.com/cloud-volumes-global-regions#cvsGcp[Google Cloud region^].

* https://cloud.google.com/storage/pricing[View pricing details for Google Cloud storage buckets^].
