---
sidebar: sidebar
permalink: get-started/intro.html
keywords: introduction, how astra works, how Astra works, what Astra is, concept, understanding, overview
summary: Astra Control Service is a Kubernetes application data lifecycle management service that simplifies operations for stateful applications. Easily back up Kubernetes apps, migrate data to a different cluster, and instantly create working application clones.
---

= Intro to Astra Control Service
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

Astra Control Service is a Kubernetes application data lifecycle management service that simplifies operations for stateful applications. Easily back up Kubernetes apps, migrate data to a different cluster, and instantly create working application clones.

== Features

Astra Control Service offers critical capabilities for Kubernetes application data lifecycle management:

* Create a protection policy for each of your apps
* Migrate applications and data from one Kubernetes cluster to another
* Easily clone an application from production to staging
* Create on-demand snapshots and backups
* Clone and back up across clouds
* Identify the health of your apps

== Supported Kubernetes deployments

Astra Control Service can manage apps that are running on a managed Kubernetes cluster in Google Kubernetes Engine (GKE) and Azure Kubernetes Service (AKS).

* link:set-up-google-cloud.html[Learn how to set up Google Cloud for Astra Control Service].
* link:set-up-microsoft-azure.html[Learn how to set up Microsoft Azure for Astra Control Service].

== Supported apps

Astra Control Service supports all applications running on your Kubernetes clusters. For GKE clusters, note that there is a link:../release-notes/known-limitations.html[known limitation with apps deployed from the Google Marketplace].

NetApp has validated some apps to ensure the safety and consistency of the snapshots and backups. link:../learn/validated-vs-standard.html[Learn the difference between a validated app and a standard app].

No matter which type of app that you use with Astra Control Service, you should always test the backup and restore workflow yourself to ensure that you can meet your disaster recovery requirements.

== How Astra Control Service works

Astra Control Service is a NetApp-managed cloud service that is always on and updated with the latest capabilities. It utilizes several components to enable application data lifecycle management.

//The following image shows the relationship between each component:

At a high level, Astra Control Service works like this:

* You get started with Astra Control Service by setting up your cloud provider and by registering for an Astra account.
+
** For GKE clusters, Astra Control Service uses https://cloud.netapp.com/cloud-volumes-service-for-gcp[NetApp Cloud Volumes Service for Google Cloud^] as the backend storage for your persistent volumes.
+
** For AKS clusters, Astra Control Service uses https://cloud.netapp.com/azure-netapp-files[Azure NetApp Files^] as the backend storage for your persistent volumes.

* You add your first Kubernetes compute to Astra Control Service. Astra Control Service then does the following:

** Creates an object store in your cloud provider account, which is where backup copies are stored.
+
In Azure, Astra Control Service also creates a resource group, a storage account, and keys for the Blob container.

** Creates a new admin role and Kubernetes service account on the cluster.

** Uses that new admin role to install https://netapp-trident.readthedocs.io/[NetApp's Trident^] on the cluster and to create one or more storage classes.
+
Astra Control Service uses Trident to provision persistent volumes for your apps.

* At this point, you can add apps to your cluster. Persistent volumes will be provisioned on the new default storage class.
+
** link:../learn/choose-class-and-size.html[Learn about storage classes for GKE clusters].
** link:../learn/azure-storage.html[Learn about storage classes for AKS clusters].

* You then use Astra Control Service to manage these apps, and start creating snapshots, backups, and clones.

Note that Astra Control Service continually watches your compute for state changes, so it's aware of any new apps that you add along the way.

== Pricing

There are two types of costs associated with using Astra Control Service: charges from NetApp for the Astra Control Service and charges from your cloud provider for persistent volumes and object storage.

=== Astra Control Service billing

Astra Control Service offers three plans:

Free Plan:: Manage up to 10 apps for free.
Premium PayGo:: Manage an unlimited amount of apps at a rate of $.005 per minute, per app.
Premium Subscription:: Pre-pay at a discounted rate with an annual subscription that enables you to manage up to 10 apps per _application pack_. Contact NetApp Sales to purchase as many packs as needed for your organization--for example, purchase 3 packs to manage 30 apps from Astra Control Service. If you manage more apps than allowed by your annual subscription, then you'll be charged at the overage rate of $0.005 per minute, per application (the same as Premium PayGo).
+
If you don't have an Astra Control account yet, purchasing the Premium Subscription automatically creates an Astra Control account for you. If you have an existing Free Plan, then you're automatically converted to the Premium Subscription.

When you create an Astra Control account, you're automatically signed up for the Free Plan. You can link:../use/set-up-billing.html[upgrade to a Premium Plan at any time]. After you upgrade, Astra Control starts charging you for _all_ managed apps in the account. The first 10 apps don't stay in the Free Plan.

=== Google Cloud billing

When you manage GKE clusters with Astra Control Service, persistent volumes are backed by NetApp Cloud Volumes Service and backups of your apps are stored in a Google Cloud Storage bucket.

* https://cloud.google.com/solutions/partners/netapp-cloud-volumes/costs[View pricing details for Cloud Volumes Service^].
+
Note that Astra Control Service supports all service types and service levels. The service type that you use depends on your https://cloud.netapp.com/cloud-volumes-global-regions#cvsGcp[Google Cloud region^].

* https://cloud.google.com/storage/pricing[View pricing details for Google Cloud storage buckets^].

=== Microsoft Azure billing

When you manage AKS clusters with Astra Control Service, persistent volumes are backed by Azure NetApp Files and backups of your apps are stored in an Azure Blob container.

* https://azure.microsoft.com/en-us/pricing/details/netapp[View pricing details for Azure NetApp Files^].

* https://azure.microsoft.com/en-us/pricing/details/storage/blobs[View pricing details for Microsoft Azure Blob storage^].
