---
sidebar: sidebar
permalink: get-started/intro.html
keywords: introduction, how astra works, how Astra works, what Astra is, concept, understanding, overview
summary: Astra Control is a Kubernetes application data lifecycle management solution that simplifies operations for stateful applications. Easily back up Kubernetes apps, migrate data to a different cluster, and instantly create working application clones.
---

= Intro to Astra Control
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

Astra Control is a Kubernetes application data lifecycle management solution that simplifies operations for stateful applications. Easily back up Kubernetes apps, migrate data to a different cluster, and instantly create working application clones.

== Features

Astra Control offers critical capabilities for Kubernetes application data lifecycle management:

* Manage, protect, and migrate your Kubernetes applications
* Manage persistent storage
* Migrate applications and data from one Kubernetes cluster to another
* Easily clone an application from production to staging
* Create application-aware, on-demand snapshots and backups
* Clone and back up across clouds
* Visualize the real-time protection status of your apps
* Use a user interface or an API to implement your backup and migration workflows

== Deployment models

Astra Control is available in two deployment models:

* *Astra Control Service*: A NetApp-managed service that provides application-aware data management of Kubernetes clusters in Google Kubernetes Engine (GKE) and Azure Kubernetes Service (AKS).

* *Astra Control Center*: Self-managed software that provides application-aware data management of Kubernetes clusters running in your on-premises environment.

[cols=3*,options="header",cols="25,25,25"]
|===
|
| Astra Control Service
| Astra Control Center
| How is it offered? | As a fully managed cloud service from NetApp | As software that you download, install, and manage
| Where is it hosted? | On a public cloud of NetApp's choice | On your provided Kubernetes cluster
| How is it updated? | Managed by NetApp | You manage any updates
| What are the app data management capabilities? | Same capabilities on both platforms with exceptions to backend storage or to external services | Same capabilities on both platforms with exceptions to backend storage or to external services
| What is the backend storage support? | NetApp cloud service offerings | NetApp ONTAP AFF and FAS systems
|===

== Supported apps

Astra Control supports all applications running on your Kubernetes clusters. NetApp has validated some apps to ensure the safety and consistency of the snapshots and backups. link:../learn/validated-vs-standard.html[Learn the difference between a validated app and a standard app].

No matter which type of app that you use with Astra Control, you should always test the backup and restore workflow yourself to ensure that you can meet your disaster recovery requirements.

== How Astra Control Service works

Astra Control Service is a NetApp-managed cloud service that is always on and updated with the latest capabilities. It utilizes several components to enable application data lifecycle management.

At a high level, Astra Control Service works like this:

* You get started with Astra Control Service by setting up your cloud provider and by registering for an Astra account.
+
** For GKE clusters, Astra Control Service uses https://cloud.netapp.com/cloud-volumes-service-for-gcp[NetApp Cloud Volumes Service for Google Cloud^] as the backend storage for your persistent volumes.
+
** For AKS clusters, Astra Control Service uses https://cloud.netapp.com/azure-netapp-files[Azure NetApp Files^] as the backend storage for your persistent volumes.

* You add your first Kubernetes compute to Astra Control Service. Astra Control Service then does the following:

** Creates an object store in your cloud provider account, which is where backup copies are stored.
+
In Azure, Astra Control Service also creates a resource group, a storage account, and keys for the Blob container.

** Creates a new admin role and Kubernetes service account on the cluster.

** Uses that new admin role to install https://netapp-trident.readthedocs.io/[NetApp's Trident^] on the cluster and to create one or more storage classes.
+
** Uses Trident to provision persistent volumes for your apps.

* At this point, you can add apps to your cluster. Persistent volumes will be provisioned on the new default storage class.
+
** link:../learn/choose-class-and-size.html[Learn about storage classes for GKE clusters].
** link:../learn/azure-storage.html[Learn about storage classes for AKS clusters].

* You then use Astra Control Service to manage these apps, and start creating snapshots, backups, and clones.
+
Astra Control Service continually watches your compute for state changes, so it's aware of any new apps that you add along the way.

Astra Control's Free Plan enables you to manage up to 10 apps in your account. If you want to manage more than 10 apps, then you'll need to link:../use/set-up-billing.html[set up billing by upgrading from the Free Plan to the Premium Plan].

== How Astra Control Center works

Astra Control Center runs locally in your own private cloud.

For the first release, Astra Control Center will support OpenShift Kubernetes clusters and Trident storage backends with ONTAP 9.5 and above.

In a cloud-connected environment, Astra Control Center uses Cloud Insights to provide advanced monitoring and telemetry. In the absence of a Cloud Insights connection, limited (7-days worth of metrics) monitoring and telemetry is available in Astra Control Center and also exported to Kubernetes native monitoring tools (such as Prometheus and Grafana) through open metrics end points.

Astra Control Center is fully integrated into the AutoSupport and Active IQ ecosystem to provide support and business users with troubleshooting and usage information.

You can try Astra Control Center out using a 90-day evaluation license. The evaluation version is supported through email and community (Slack channel) options. Additionally, you have access to Knowledgebase articles and documentation from the in-product support dashboard.

To install and use Astra Control Center, you'll need some prerequisites. Learn about the https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html[requirements^].

At a high level, Astra Control Center works like this:

* You install Astra Control Center in your local environment.
* Astra Control Center does this:
** Discovers your Kubernetes clusters.
** Discovers your Trident configuration backed by an ONTAP storage backend.
** Creates a new admin role.

Learn more about how to https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc.html[install Astra Control Center^].

You complete some setup tasks such as these:

* Set up licensing.
* Add your first cluster.
* Add backend storage.
* Add an object store bucket that will store your app backups.

Learn more about how to https://docs.netapp.com/us-en/astra-control-center/get-started/setup_overview.html[set up Astra Control Center^].

At this point, you can add apps to your cluster. Some apps are pre-installed in the cluster being managed. Then, use Astra Control Center to manage these apps, and create snapshots, backups, and clones.
