---
sidebar: sidebar
permalink: get-started/intro.html
keywords: introduction, how astra works, how Astra works, what Astra is, concept, understanding, overview
summary: Astra is a Kubernetes application data lifecycle management service that simplifies operations for stateful applications. Easily back up Kubernetes apps, migrate data to a different cluster, and instantly create working application clones.
---

= Intro to Astra
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

Astra is a Kubernetes application data lifecycle management service that simplifies operations for stateful applications. Easily back up Kubernetes apps, migrate data to a different cluster, and instantly create working application clones.

== Features

Astra offers critical capabilities for Kubernetes application data lifecycle management:

* Create a protection policy for each of your apps
* Migrate applications and data from one Kubernetes cluster to another
* Easily clone an application from production to staging
* Create on-demand snapshots and backups
* Identify the health of your apps

== Supported Kubernetes deployments

Astra can manage apps on Google Kubernetes Engine (GKE) clusters.

On-prem Kubernetes clusters and clusters running in other cloud providers aren't supported at this time.

link:requirements.html[Learn about cluster requirements].

== Pricing

Astra offers two plans:

[horizontal]
Free Plan:: Manage up to 10 apps for free.

Premium Plan:: Manage an unlimited amount of apps by paying per minute, per application. https://cloud.netapp.com/project-astra[Learn how much the Premium Plan costs^].

link:../use/set-up-billing.html[Upgrade to the Premium Plan at any time]. After you upgrade to the Premium plan, Astra starts charging you for _all_ managed apps. The first 10 apps don't stay in the Free Plan.

== How Astra works

Astra is a NetApp-managed cloud service that is always on and updated with the latest capabilities. It utilizes several components to enable application data lifecycle management. The following image shows the relationship between each component:

At a high level, Astra works like this:

* You set up your cloud provider by enabling Cloud Volumes Service for Google Cloud and by creating a GCP service account for Astra.

* You add your first Kubernetes cluster to Astra. Astra then does the following:

** Creates an object store in your cloud provider account, which is where backup copies are sent.

** Creates a new admin role and Kubernetes service account on the cluster.

** Uses that new admin role to install https://netapp-trident.readthedocs.io/[NetApp's Trident^].

** Astra uses Trident to provision persistent volumes backed by NetApp Cloud Volumes Service for Google Cloud.

** Astra creates three storage classes that use Cloud Volumes Service for Google Cloud: netapp-cvs-extreme, netapp-cvs-premium, and netapp-cvs-standard.

* At this point, you can add apps to your cluster. Persistent volumes will be provisioned on the new storage classes by default.

* You then use Astra to manage these apps, and start creating snapshots, backups, and clones.

Note that Astra continually watches your clusters for state changes, so it's aware of any new apps that you add along the way.
