---
sidebar: sidebar
permalink: get-started/intro.html
keywords: introduction, how astra works, how Astra works, what Astra is, concept, understanding, overview
summary: Astra Control is a Kubernetes application data lifecycle management solution that simplifies operations for stateful applications. Easily back up Kubernetes apps, migrate data to a different cluster, and instantly create working application clones.
---

= Intro to Astra Control
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

Astra Control is a Kubernetes application data lifecycle management solution that simplifies operations for stateful applications. Easily back up Kubernetes apps, migrate data to a different cluster, and instantly create working application clones.

== Features

Astra Control offers critical capabilities for Kubernetes application data lifecycle management:

* Manage, protect, and migrate your Kubernetes applications
* Manage persistent storage
* Migrate applications and data from one Kubernetes cluster to another
* Easily clone an application from production to staging
* Create application-aware, on-demand snapshots and backups
* Clone and back up across clouds
* Visualize the real-time protection status of your apps
* Use a user interface or an API to implement your backup and migration workflows

== Deployment models

Astra Control is available in two deployment models:

* *Astra Control Service*: A NetApp-managed service that provides application-aware data management of Kubernetes clusters in Google Kubernetes Engine (GKE) and Azure Kubernetes Service (AKS).

* *Astra Control Center*: Self-managed software that provides application-aware data management of Kubernetes clusters running in your on-premises environment.

== Supported apps

Astra Control supports all applications running on your Kubernetes clusters. NetApp has validated some apps to ensure the safety and consistency of the snapshots and backups. link:../learn/validated-vs-standard.html[Learn the difference between a validated app and a standard app].

No matter which type of app that you use with Astra Control, you should always test the backup and restore workflow yourself to ensure that you can meet your disaster recovery requirements.

== How Astra Control Service works

Astra Control Service is a NetApp-managed cloud service that is always on and updated with the latest capabilities. It utilizes several components to enable application data lifecycle management.

At a high level, Astra Control Service works like this:

* You get started with Astra Control Service by setting up your cloud provider and by registering for an Astra account.
+
** For GKE clusters, Astra Control Service uses https://cloud.netapp.com/cloud-volumes-service-for-gcp[NetApp Cloud Volumes Service for Google Cloud^] as the backend storage for your persistent volumes.
+
** For AKS clusters, Astra Control Service uses https://cloud.netapp.com/azure-netapp-files[Azure NetApp Files^] as the backend storage for your persistent volumes.

* You add your first Kubernetes compute to Astra Control Service. Astra Control Service then does the following:

** Creates an object store in your cloud provider account, which is where backup copies are stored.
+
In Azure, Astra Control Service also creates a resource group, a storage account, and keys for the Blob container.

** Creates a new admin role and Kubernetes service account on the cluster.

** Uses that new admin role to install https://netapp-trident.readthedocs.io/[NetApp's Trident^] on the cluster and to create one or more storage classes.
+
** Uses Trident to provision persistent volumes for your apps.

* At this point, you can add apps to your cluster. Persistent volumes will be provisioned on the new default storage class.
+
** link:../learn/choose-class-and-size.html[Learn about storage classes for GKE clusters].
** link:../learn/azure-storage.html[Learn about storage classes for AKS clusters].

* You then use Astra Control Service to manage these apps, and start creating snapshots, backups, and clones.

Note that Astra Control Service continually watches your compute for state changes, so it's aware of any new apps that you add along the way.

== How Astra Control Center works

Astra Control Center runs locally in your own private cloud.

At a high level, Astra Control Center works like this:

* You install Astra Control Center in your local environment.
* Astra Control Center does this:
** Discovers your Kubernetes clusters.
** Discovers your Trident configuration backed by an ONTAP storage backend.
** Creates a new admin role.

You complete some setup tasks such as these:

* Set up licensing.
* Add your first cluster.
* Add backend storage.
* Add an object store bucket that will store your app backups.

At this point, you can add apps to your cluster. Some apps are pre-installed in the cluster being managed. Then, use Astra Control Center to manage these apps, and create snapshots, backups, and clones.
