---
sidebar: sidebar
permalink: get-started/manage-private-cluster.html
keywords: discover private cluster, add cluster, add kubernetes cluster, private, discover kubernetes cluster, add private cluster
summary: After you set up your environment, you're ready to create a Kubernetes cluster and then add it to Astra Control Service.
---

= Manage private clusters from Astra Control Service
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
You can use Astra Control Service to manage private AKS clusters. These instructions assume that you have already created a private AKS cluster and prepared a secure method to remotely access it; for more information about creating and accessing private AKS clusters, refer to the https://docs.microsoft.com/azure/aks/private-clusters[Azure documentation^].
//To do so, you need to install the Astra Connector operator on the private AKS service cluster. You can complete this step before you add the cluster for management or during the process of adding it, when prompted.

* <<Install the Astra Connector operator>>
//* <<Create an Astra Connector object>>
* <<Set up persistent storage>>
* <<Add the private cluster to Astra Control Service>>

////
== Provide access to the private AKS cluster
Using a bastion host, you can enable remote access to the private cluster from external networks. You can create a bastion host by creating an Azure VM that has access to the VNet that is used by the private AKS cluster, and resides in the same Resource Group as the private cluster. Other options for accessing the private AKS cluster remotely include:

* An Azure VM that is in a different VNet and is peered to the private AKS cluster VNet
* A VPN connection
* The AKS `az aks command invoke` command
* A private endpoint
////

== Install the Astra Connector operator
You need to install the Astra Connector operator on private AKS cluster. If you are using a bastion host, issue these commands from the command line of the bastion host. 
//You can complete this step before you add the cluster for management or during the process of adding it, when prompted.

.Steps

. Clone the Astra Connector operator GitHub repository:
+
[source,console]
----
git clone https://github.com/NetApp/astra-connector-operator.git
----
. Change directories to the top level of the unpacked operator package, so that you can see the `astraconnector_operator.yaml` file with the `ls` command.

. Create a namespace for the Astra Connector operator.
+
[source,console]
----
kubectl create ns astra-connector-operator
----

. Apply the `astraconnector_operator.yaml` file to the operator namespace.
+
[source,console]
----
kubectl apply -f astraconnector_operator.yaml -n astra-connector-operator
----

. Create a namespace for the private cluster components.
+
[source,console]
----
kubectl create ns astra-connector
----

. Generate an Astra Control API token using the instructions in the https://docs.netapp.com/us-en/astra-automation/get-started/get_api_token.html[Astra Automation documentation^].

. Modify the example configuration file in the config/samples directory of the Astra Connector operator repository to fit your needs.

. Apply the Astra Connector Custom Resource Definition (CRD).
+
[source,console]
----
kubectl apply -f config/samples/astraconnector_v1.yaml -n astra-connector
----

. Check the status of the Astra Connector.
+
[source,console]
----
kubectl get astraconnector astra-connector -n astra-connector
----
+
You should refer to output similar to the following:
+
[source,console]
----
NAME              REGISTERED   ASTRACONNECTORID
astra-connector   true         22b839aa-8b85-445a-85dd-0b1f53b5ea19
----

== Set up persistent storage
Configure persistent storage for the cluster. You can use Azure NetApp Files or Azure managed disks. Refer to the Get Started documentation for more information about configuring Azure with these options:

* https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-microsoft-azure-with-anf.html[Set up Microsoft Azure with Azure NetApp Files]
* https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-microsoft-azure-with-amd.html[Set up Microsoft Azure with Azure managed disks]

== Add the private cluster to Astra Control Service
You can now add the private AKS cluster to Astra Control Service. Follow the standard workflow to add a cluster to Astra Control Service: https://docs.netapp.com/us-en/astra-control-service/get-started/add-first-cluster.html[Start managing Kubernetes clusters from Astra Control Service]. 
