---
sidebar: sidebar
permalink: get-started/manage-private-cluster.html
keywords: discover private cluster, add cluster, add kubernetes cluster, private, discover kubernetes cluster, add private cluster
summary: After you set up your environment, you're ready to create a Kubernetes cluster and then add it to Astra Control Service.
---

= Manage private clusters from Astra Control Service
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
ifdef::aws+azure+gcp[]
You can use Astra Control Service to manage private Azure Kubernetes Service (AKS) clusters as well as private Red Hat OpenShift clusters in AKS. These instructions assume that you have already created a private AKS or OpenShift cluster and prepared a secure method to remotely access it; for more information about creating and accessing private AKS or OpenShift clusters, refer to the following documentation:

* https://docs.microsoft.com/azure/aks/private-clusters[Azure documentation for private AKS clusters^]
* https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x[Azure documentation for private OpenShift clusters^]
* https://docs.aws.amazon.com/eks/latest/userguide/private-clusters.html[Amazon EKS documentation^]
endif::aws+azure+gcp[]

ifndef::azure,aws[]
You can use Astra Control Service to manage private Azure Kubernetes Service (AKS) and Red Hat OpenShift clusters in AKS. These instructions assume that you have already created a private AKS or OpenShift cluster and prepared a secure method to remotely access it; for more information about creating and accessing private AKS or OpenShift clusters, refer to the following documentation:

* https://docs.microsoft.com/azure/aks/private-clusters[Azure documentation for private AKS clusters^]
* https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x[Azure documentation for private OpenShift clusters^]
endif::azure,aws[]


ifndef::gcp,aws[]
You can use Astra Control Service to manage private Azure Kubernetes Service (AKS) clusters as well as private Red Hat OpenShift clusters in AKS. These instructions assume that you have already created a private AKS or OpenShift cluster and prepared a secure method to remotely access it; for more information about creating and accessing private AKS or OpenShift clusters, refer to the following documentation:

* https://docs.microsoft.com/azure/aks/private-clusters[Azure documentation for private AKS clusters^]
* https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x[Azure documentation for private OpenShift clusters^]
endif::gcp,aws[]

ifndef::azure,gcp[]
You can use Astra Control Service to manage private Amazon Elastic Kubernetes Service (EKS) clusters. These instructions assume that you have already created a private EKS cluster and prepared a secure method to remotely access it; for more information about creating and accessing private EKS clusters, refer to the https://docs.aws.amazon.com/eks/latest/userguide/private-clusters.html[Amazon EKS documentation^].
endif::azure,gcp[]

////
* <<Install the Astra Connector operator>>
* <<Set up persistent storage>>
* <<Add the private cluster to Astra Control Service>>
////
== Install the Astra Connector operator
You need to install the Astra Connector operator on the private cluster. If you are using a bastion host, issue these commands from the command line of the bastion host. 

.Steps

. Clone the Astra Connector operator GitHub repository:
+
[source,console]
----
git clone https://github.com/NetApp/astra-connector-operator.git
----
. Change directories to the top level of the unpacked operator package, so that you can see the `astraconnector_operator.yaml` file with the `ls` command.

. Create a namespace for the Astra Connector operator.
+
[source,console]
----
kubectl create ns astra-connector-operator
----

. Apply the `astraconnector_operator.yaml` file to the operator namespace.
+
[source,console]
----
kubectl apply -f astraconnector_operator.yaml -n astra-connector-operator
----

. Create a namespace for the private cluster components.
+
[source,console]
----
kubectl create ns astra-connector
----

. Generate an Astra Control API token using the instructions in the https://docs.netapp.com/us-en/astra-automation/get-started/get_api_token.html[Astra Automation documentation^].

. Modify the example configuration file in the config/samples directory of the Astra Connector operator repository to include the `spec.natssync-client.cloud-bridge-url` key. For example:
+
----
apiVersion: netapp.astraconnector.com/v1
kind: AstraConnector
metadata:
  name: astra-connector
spec:
  natssync-client:
    image: natssync-client:2.0
    cloud-bridge-url: https://<your.astra.control.service.url>
  nats:
    image: nats:2.6.1-alpine3.14
  httpproxy-client:
    image: httpproxylet:2.0
  echo-client:
    image: echo-proxylet:2.0
  imageRegistry:
    name: theotw
  astra:
    token: <Astra Control API token>
    clusterName: <your-cluster-name>
    accountId: <Astra Control account id>
    acceptEULA: yes
----

. Apply the Astra Connector Custom Resource Definition (CRD).
+
[source,console]
----
kubectl apply -f config/samples/astraconnector_v1.yaml -n astra-connector
----

. Check the status of the Astra Connector.
+
[source,console]
----
kubectl get astraconnector astra-connector -n astra-connector
----
+
You should refer to output similar to the following:
+
[source,console]
----
NAME              REGISTERED   ASTRACONNECTORID
astra-connector   true         22b839aa-8b85-445a-85dd-0b1f53b5ea19
----

== Set up persistent storage
Configure persistent storage for the cluster. Refer to the Get Started documentation for more information about configuring persistent storage:

ifdef::azure,gcp[]
* https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-microsoft-azure-with-anf.html[Set up Microsoft Azure with Azure NetApp Files^]
* https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-microsoft-azure-with-amd.html[Set up Microsoft Azure with Azure managed disks^]
endif::azure,gcp[]
ifdef::aws,gcp[]
* https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-amazon-web-services.html[Set up Amazon Web Services^]
endif::aws,gcp[]


== Add the private cluster to Astra Control Service
You can now add the private cluster to Astra Control Service. Follow the standard workflow to add a cluster to Astra Control Service: https://docs.netapp.com/us-en/astra-control-service/get-started/add-first-cluster.html[Start managing Kubernetes clusters from Astra Control Service]. 
