---
sidebar: sidebar
permalink: get-started/requirements.html
keywords: kubernetes cluster, cluster requirements, version requirements, supported versions, supported regions, google cloud regions, gcp regions, apps, supported apps, mariadb, mysql, postgres
summary: Get started by verifying support for your Kubernetes clusters and apps.
---

= Requirements
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

Get started by verifying support for your Kubernetes clusters, apps, and web browser.

== Supported Kubernetes clusters

* The Project Astra beta program supports Kubernetes clusters that are managed by Google Kubernetes Engine (GKE).
+
On-prem Kubernetes clusters and clusters running in other cloud providers are not supported at this time.

* Clusters must be running in a healthy state, in one of the supported regions:
  ** us-central1
  ** us-east4
  ** us-west2
  ** europe-west3
  ** europe-west2
  ** australia-southeast1

* A cluster must be running Kubernetes version 1.17 or later.

* The cluster must have at least one online worker node.

* The image type for each worker node must be Ubuntu.

* If the cluster is private, it must have the https://cloud.google.com/kubernetes-engine/docs/concepts/private-cluster-concept[master authorized network] set to allow the Astra IP addresses:
  ** 18.232.241.74
  ** 52.72.239.237
  ** 3.210.60.146

== Supported apps

Project Astra supports all applications running on your Kubernetes clusters.

NetApp has validated some apps to ensure the safety and consistency of the snapshots and backups.

link:../learn/validated-vs-standard.html[Learn the difference between a Validated and a Standard app].

No matter which type of app that you use with Project Astra, you should always test the backup and restore workflow yourself to ensure that you can meet your disaster recovery requirements.

== Supported web browsers

Project Astra supports recent versions of Firefox, Safari, and Chrome with a minimum resolution of 1280 x 720.
