---
sidebar: sidebar
permalink: get-started/supported-deployments.html
keywords: gke, aks, google kubernetes engine, azure kubernetes service
summary: "Astra Control Service can manage apps that are running on a managed Kubernetes cluster in cloud provider environments."
---

= Supported Kubernetes deployments
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
ifndef::azure,gcp[]
Astra Control Service can manage apps that are running on a managed Kubernetes cluster in Amazon Elastic Kubernetes Service (EKS) as well as clusters that you manage on your own.
endif::azure,gcp[]

ifndef::azure,aws[]
Astra Control Service can manage apps that are running on a managed Kubernetes cluster in Google Kubernetes Engine (GKE) as well as clusters that you manage on your own.
endif::azure,aws[]

ifndef::gcp,aws[]
Astra Control Service can manage apps that are running on a managed Kubernetes cluster in Azure Kubernetes Service (AKS) as well as clusters that you manage on your own.
endif::gcp,aws[]

ifdef::gcp+azure+aws[]
Astra Control Service can manage apps that are running on a managed Kubernetes cluster in Google Kubernetes Engine (GKE), Amazon Elastic Kubernetes Service (EKS), and Azure Kubernetes Service (AKS). Astra Control Service can also manage clusters that you manage on your own.
endif::gcp+azure+aws[]

ifdef::aws[]
* link:set-up-amazon-web-services.html[Learn how to set up Amazon Web Services for Astra Control Service].
endif::aws[]

ifdef::gcp[]
* link:set-up-google-cloud.html[Learn how to set up Google Cloud for Astra Control Service].
endif::gcp[]

ifdef::azure[]
* link:set-up-microsoft-azure-with-anf.html[Learn how to set up Microsoft Azure with Azure NetApp Files for Astra Control Service].
* link:set-up-microsoft-azure-with-amd.html[Learn how to set up Microsoft Azure with Azure managed disks for Astra Control Service].
endif::azure[]
* link:add-first-cluster.html#start-managing-kubernetes-clusters[Learn how to prepare self-managed clusters before adding them to Astra Control Service].
