---
sidebar: sidebar
permalink: get-started/videos.html
keywords: videos, Astra videos
summary: Many of the pages on this doc site include videos that show how to complete a task using Astra. If you're just interested in videos, we've made it easier for you by collecting all of the videos on this single page (kind of like a playlist).
---

= Astra videos
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

Many of the pages on this doc site include videos that show you how to complete a task for Astra. If you're just interested in videos, we've made it easy for you by collecting all of the videos on this single page (kind of like a playlist).

== Videos for setting up Google Cloud

The following videos show how to complete set up requirements in Google Cloud before you can discover Kubernetes clusters running in GCP.

=== Enable APIs

Your project needs permissions to access specific Google Cloud APIs. The following video shows how to enable the APIs from the Google Cloud console. link:set-up-google-cloud.html#enable-apis-in-your-project[Learn more about enabling APIs].

video::video-enable-gcp-apis.mp4[width=848, height=480]

=== Create a service account

Astra uses a Google Cloud service account to facilitate Kubernetes application data management on your behalf. The following video shows how to create the service account from the Google Cloud console. link:set-up-google-cloud.html#create-a-service-account[Learn more about creating a service account].

video::video-create-gcp-service-account.mp4[width=848, height=480]

=== Create a service account key

Astra uses a service account key to establish the identity of the service account that you just set up. The following video shows how to create the service account key from the Google Cloud console. link:set-up-google-cloud.html#create-a-service-account-key-2[Learn more about creating a service account key].

video::video-create-gcp-service-account-key.mp4[width=848, height=480]

== Videos for using Astra

The following videos show how to complete common tasks using Astra.

=== Add your first cluster to Astra

After you log in to Astra, your first step is to add a Kubernetes cluster. link:add-first-cluster.html[Learn more about adding a cluster].

video::video-manage-cluster.mp4[width=848, height=480]
