---
sidebar: sidebar
permalink: release-notes/known-issues.html
keywords: bugs, known issues, problems
summary: Known issues identify problems that might prevent you from using this release of the product successfully.
---

= Known issues
:hardbreaks:
:icons: font
:imagesdir: ../media/release-notes/

Known issues identify problems that might prevent you from using this release of the product successfully.

The following known issues affect the current release:

////
== Operator-deployed apps and namespaces
An operator and the app it deploys must use the same namespace; you might need to modify the deployment .yaml file for the operator to ensure this is the case.
////

* <<App clones fail after an application is deployed with a set storage class>>
* <<App clones fail using a specific version of PostgreSQL>>
* <<Backup taken from new snapshot instead of existing snapshot>>
* <<Custom app execution hook scripts time out and cause post-snapshot scripts not to execute>>
* <<Clone performance impacted by large persistent volumes>>
* <<Simultaneous app restore operations in the same namespace can fail>>
* <<Snapshots eventually begin to fail when using external-snapshotter version 4.2.0>>
* <<Unable to stop running app backup>>

== App clones fail after an application is deployed with a set storage class
//DOC-3892/ASTRACTL-13183/PI4
After an application is deployed with a storage class explicitly set (for example, `helm install ...-set global.storageClass=netapp-cvs-perf-extreme`), subsequent attempts to clone the application require that the target cluster have the originally specified storage class.
Cloning an application with an explicitly set storage class to a cluster that does not have the same storage class will fail. There are no recovery steps in this scenario.

== App clones fail using a specific version of PostgreSQL
//DOC-3543/ASTRACTL-9408/Q2 and PI4
App clones within the same cluster consistently fail with the Bitnami PostgreSQL 11.5.0 chart. To clone successfully, use an earlier or later version of the chart.

== Backup taken from new snapshot instead of existing snapshot
When you create a backup and select *Backup from existing snapshot*, Astra Control creates an ad-hoc snapshot and uses that snapshot to create the backup. Astra Control doesn't use the existing snapshot.

== Custom app execution hook scripts time out and cause post-snapshot scripts not to execute
//ASTRACTL-12927/DOC-3909
If an execution hook takes longer than 25 minutes to run, the hook will fail, creating an event log entry with a return code of "N/A". Any affected snapshot will timeout and be marked as failed, with a resulting event log entry noting the timeout.

Because execution hooks often reduce or completely disable the functionality of the application they are running against, you should always try to minimize the time your custom execution hooks take to run.

== Clone performance impacted by large persistent volumes
Clones of very large and consumed persistent volumes might be intermittently slow, dependent on cluster access to the object store. If the clone is hung and no data has been copied for more than 30 minutes, Astra Control terminates the clone action.

== Simultaneous app restore operations in the same namespace can fail
//DOC-3910 and ASTRACTL-13362
If you try to restore one or more individually managed apps within a namespace simultaneously, the restore operations can fail after a long period of time. As a workaround, restore each app one at a time.

== Snapshots eventually begin to fail when using external-snapshotter version 4.2.0
// DOC-3891 and ASTRACTL-12523
When you use Kubernetes snapshot-controller (also known as external-snapshotter) version 4.2.0 with Kubernetes 1.20 or 1.21, snapshots can eventually begin to fail. To prevent this, use a different https://kubernetes-csi.github.io/docs/snapshot-controller.html[supported version^] of external-snapshotter, such as version 4.2.1, with Kubernetes versions 1.20 or 1.21.

== Unable to stop running app backup
// DOC-3552/ASTRACTL-9586/DOC-3894/ASTRACTL-13029/Q2 and PI4
There is no way to stop a running backup. If you need to delete the backup, wait until it has completed and then use the instructions in link:../use/protect-apps.html#delete-backups[Delete backups]. To delete a failed backup, use the link:https://docs.netapp.com/us-en/astra-automation/index.html[Astra API^].
