---
sidebar: sidebar
permalink: release-notes/known-issues.html
keywords: bugs, known issues, problems
summary: Known issues identify problems that might prevent you from using this release of the product successfully.
---

= Known issues
:hardbreaks:
:icons: font
:imagesdir: ../media/release-notes/

[.lead]
Known issues identify problems that might prevent you from using this release of the product successfully.

The following known issues affect the current release:


.Apps

//* <<App clones fail after an application is deployed with a set storage class>>
//* <<Applications page loads forever when trying to restore an application belonging to a deleted cluster>>
* <<Unable to define an app on a namespace that has been deleted and recreated>>

.Backup, restore, and clone

//* <<Restore of an app results in PV size larger than original PV>>
* <<App clones fail using a specific version of PostgreSQL>>
* <<App backups and snapshots fail if the volumesnapshotclass is added after a cluster is managed>>
* <<In-place restore operations to ontap-nas-economy storage classes fail>>
* <<Restoring from a backup when using Kerberos in-flight encryption can fail>>
* <<Backup data remains in bucket after deletion for buckets with expired retention policy>>
//* <<Retention time for immutable backups is longer than expected>>

.Other issues

//* <<Snapshots eventually begin to fail when using external-snapshotter version 4.2.0>>
* <<App data management operations fail with Internal Service Error (500) when Astra Trident is offline>>

//== App clones fail after an application is deployed with a set storage class
//DOC-3892/ASTRACTL-13183/PI4
//After an application is deployed with a storage class explicitly set (for example, `helm install ...-set global.storageClass=netapp-cvs-perf-extreme`), subsequent attempts to clone the application require that the target cluster have the originally specified storage class. Cloning an application with an explicitly set storage class to a cluster that does not have the same storage class will fail. There are no recovery steps in this scenario.

//ASTRACTL-20272 - PI6
//== Applications page loads forever when trying to restore an application belonging to a deleted cluster
//When you try to restore an app from a deleted cluster from the Applications page, the Applications page never finishes loading. As a workaround, restore the app from the app's Actions menu in the Applications listing page.

== Unable to define an app on a namespace that has been deleted and recreated
If you define an application with a namespace, delete the namespace, and then reinstall the app in the same namespace, the operation fails with a 409 error code. To define the app using the recreated namespace, delete the old application instance first.

//== Restore of an app results in PV size larger than original PV
// DOC-3562/ASTRACTL-9560/Q2 and PI4
//If you resize a persistent volume after creating a backup and then restore from that backup, the persistent volume size will match the new size of the PV instead of using the size of the backup.

== App clones fail using a specific version of PostgreSQL
//DOC-3543/ASTRACTL-9408/Q2 and PI4
App clones within the same cluster consistently fail with the Bitnami PostgreSQL 11.5.0 chart. To clone successfully, use an earlier or later version of the chart.

== App backups and snapshots fail if the volumesnapshotclass is added after a cluster is managed
Backups and snapshots fail with a UI 500 error in this scenario. As a workaround, refresh the app list.

//== Snapshots eventually begin to fail when using external-snapshotter version 4.2.0
// DOC-3891 and ASTRACTL-12523
//When you use Kubernetes snapshot-controller (also known as external-snapshotter) version 4.2.0 with Kubernetes 1.20 or 1.21, snapshots can eventually begin to fail. To prevent this, use a different https://kubernetes-csi.github.io/docs/snapshot-controller.html[supported version^] of external-snapshotter, such as version 4.2.1, with Kubernetes versions 1.20 or 1.21.

== In-place restore operations to ontap-nas-economy storage classes fail
// ASTRADOC-318 / ASTRACTL-29463
If you perform an in-place restore of an application (restore the app to its original namespace), and the app's storage class uses the `ontap-nas-economy` driver, the restore operation can fail if the snapshot directory is not hidden. Before restoring in-place, follow the instructions in link:../use/protect-apps.html#enable-backup-and-restore-for-ontap-nas-economy-operations[Enable backup and restore for ontap-nas-economy operations^] to hide the snapshot directory.

== Restoring from a backup when using Kerberos in-flight encryption can fail
// ASTRADOC-316 / ASTRACTL-29854
When you restore an application from a backup to a storage backend that is using Kerberos in-flight encryption, the restore operation can fail. This issue does not affect restoring from a snapshot or replicating the application data using NetApp SnapMirror.

//To avoid this, when you install an application that you plan to protect with Kerberos in-flight encryption, ensure the application runs with superuser permissions. You can do so by configuring the app to use the following securityContext settings:
//----
//securityContext:
//  runAsUser: 0
//  runAsGroup: 0
//----
NOTE: When using Kerberos in-flight encryption with NFSv4 volumes, ensure that the NFSv4 volumes are using the correct settings. Refer to the NetApp NFSv4 Domain Configuration section (page 13) of the https://www.netapp.com/media/16398-tr-3580.pdf[NetApp NFSv4 Enhancements and Best Practices Guide^]. 

== Backup data remains in bucket after deletion for buckets with expired retention policy
//ASTRADOC-319 / ASTRACTL-30000
If you delete an app's immutable backup after the bucket's retention policy has expired, the backup is deleted from Astra Control but not from the bucket. As a workaround, if you need to delete the most recent backups or all backups for an application, remove the backups manually from the storage backend.

NOTE: If you have more than one backup for an app, either remove the most recent backups or all of the backups for the app. If you remove any middle incremental backups, you will not be able to recover the app from the latest backup.

//== Retention time for immutable backups is longer than expected
// ASTRADOC-320 / ASTRACTL-30098
//The retention time for an immutable backup in Astra Control is calculated from the starting time of the backup instead of the completion time. This means you cannot delete the backup for a longer period than expected. For example, if you configure a 24 hour retention policy and start a backup that takes 12 hours to complete, you cannot delete the backup for 36 hours.

== App data management operations fail with Internal Service Error (500) when Astra Trident is offline
//DOC-3903/ASTRACTL-13162/PI4
If Astra Trident on an app cluster goes offline (and is brought back online) and 500 internal service errors are encountered when attempting app data management, restart all of the Kubernetes nodes in the app cluster to restore functionality.
