---
sidebar: sidebar
permalink: release-notes/known-limitations.html
keywords: limitations, known limitations, interoperability
summary: Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.
---

= Known limitations
:hardbreaks:
:icons: font
:imagesdir: ../media/release-notes/

Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.

== General limitations

The following limitations affect Astra Control Service's management of Kubernetes clusters in any supported Kubernetes deployment.

=== Unhealthy pods affect app management

If a managed app has pods in an unhealthy state, Astra Control Service can't create new backups and clones.

=== Astra Trident isn't uninstalled from a cluster

When you unmanage a cluster from Astra Control Service, Astra Trident isn't automatically uninstalled from the cluster. To uninstall Astra Trident, you'll need to https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html[follow these steps in the Astra Trident documentation^].

=== Existing connections to a Postgres pod causes failures

When you perform operations on Postgres pods, you shouldn't connect directly within the pod to use the psql command. Astra Control Service requires psql access to freeze and thaw the databases. If there is a pre-existing connection, the snapshot, backup, or clone will fail.

== Limitations for management of GKE clusters

The following limitations apply to the management of Kubernetes clusters in Google Kubernetes Engine (GKE).

=== One GCP project and one service account are supported

Astra Control Service supports one Google Cloud Platform project and one service account. You should not add more than one service account to Astra Control Service and you shouldn’t rotate service account credentials.

=== Google Marketplace apps haven't been validated

NetApp hasn't validated apps that were deployed from the Google Marketplace. Some users report issues with discovery or back up of Postgres, MariaDB, and MySQL apps that were deployed from the Google Marketplace.

No matter which type of app that you use with Astra Control Service, you should always test the backup and restore workflow yourself to ensure that you can meet your disaster recovery requirements.

=== Persistent volume limit

You can have up to 100 volumes per Google Cloud region. If you reach this limit, creation of new clones or volumes will fail. link:../support/get-help.html[Contact support to increase the volume limit].

== App management limitations
The following limitations affect Astra Control Service's management of applications.

=== Clones of apps installed using pass by reference operators can fail
Astra Control supports apps installed with namespace-scoped operators. These operators are generally designed with a "pass-by-value" rather than "pass-by-reference" architecture. The following are some operator apps that follow these patterns:

* https://github.com/k8ssandra/cass-operator/tree/v1.7.1[Apache K8ssandra^]
* https://github.com/jenkinsci/kubernetes-operator[Jenkins CI^]
* https://github.com/percona/percona-xtradb-cluster-operator[Percona XtraDB Cluster^]

Note that Astra Control might not be able to clone an operator that is designed with a “pass-by-reference” architecture (for example, the CockroachDB operator). During these types of cloning operations, the cloned operator attempts to reference Kubernetes secrets from the source operator despite having its own new secret as part of the cloning process. The clone operation might fail because Astra Control is unaware of the Kubernetes secrets in the source operator.
